### ISSUE TITLE
Shorthand syntax formatted over 80 character line limit

### ISSUE THREAD

**Issue by kallentu** [dart-lang/dart_style#1005]
dartfmt forces this formatting where the first line is 81 characters. 
```
class  C {
  ExecutionStatus defaultStatement(Statement node) => throw new UnsupportedError(
        'Statement constant evaluation does not support ${node.runtimeType}.');
}
```
Not entirely sure why it formatted in this way. I expected dartfmt to put the throw on a newline or something similar to respect the 80 character limit.

**Comment by natebosch** [comment]
This may be an off by 1 error, making the line 1 character longer shows correct results.

**Comment by munificent** [comment]
It's because the string literal is so long. It wants to format the result like:

```dart
class C {
  ExecutionStatus defaultStatement(Statement node) =>
      throw new UnsupportedError(
          'Statement constant evaluation does not support ${node.runtimeType}.');
}
```

But it can't because the string overhangs. So it does the next least bad thing which is to have the `UnsupportedError` part hang over. If you split the string in two, you'll get better formatting.

**Comment by natebosch** [comment]
Ah, I see. So the fact that this hit at exactly 81 columns, but not 82, is because of the specific length of the other string. Making the other string longer does let the first line get past 81 columns.
