### ISSUE TITLE
Always split cascades

### ISSUE THREAD

**Issue by ManoyloK** [dart-lang/dart_style#1006]
Input
```
a..doSmth(A())..doSmth(B())
..doSmth(C())..doSmth(D())
..doSmth(E());
```
Output
```
a..doSmth(A())..doSmth(B())..doSmth(C())..doSmth(D())..doSmth(E());
```

Expected output
```
a
      ..doSmth(A())
      ..doSmth(B())
      ..doSmth(C())
      ..doSmth(D())
      ..doSmth(E());
```

**Comment by ManoyloK** [comment]
I've investigated this problem and found this part of the code 
```
var name;
    // We could be more forgiving about what constitutes sections with
    // consistent names but for now we require all sections to have the same
    // method name.
    for (var expression in node.cascadeSections) {
      if (expression is MethodInvocation) {
        if (name == null) {
          name = expression.methodName.name;
        } else if (name != expression.methodName.name) {
          return false;
        }
      } else {
        return false;
      }
    }
```
I believe that it works fine for few chained methods with not complex arguments, but when you use, for example, a service locator and provide a lot of dependencies it could turn into some mess, that very difficult to read and understand

**Comment by ManoyloK** [comment]
@munificent, @natebosch  what do you think about it?

**Comment by natebosch** [comment]
There is more discussion of this at https://github.com/dart-lang/dart_style/issues/479

I don't have strong opinions on this heuristic around using the same member multiple times, it does feel a little magic to me.

@munificent - do you remember what types of changes you saw that looked worse without this?

**Comment by munificent** [comment]
@jacob314 was the one who originally requested packing multiple cascades onto a single line if they're the same name. If it were me, I would always split them.

**Comment by jacob314** [comment]
I'm now happy with always splitting cascades. I think that better aligns with where Dart/Flutter style has moved over the past 5 years.

**Comment by ManoyloK** [comment]
Should I create a PR for that?

**Comment by munificent** [comment]
Yes, that would be rad. I think it's basically just removing the last half of `_allowInlineCascade()` after the `cascadeSections.length` check and then adjusting the tests to match the new behavior.

**Comment by ManoyloK** [comment]
@munificent I've created the [PR](https://github.com/dart-lang/dart_style/pull/1020), please take a look

**Comment by munificent** [comment]
Merged to master now. Thanks, @ManoyloK!
