### ISSUE TITLE
Could not format because the source could not be parsed

### ISSUE THREAD

**Issue by maheshmnj** [dart-lang/dart_style#1009]
Does this package allow formatting a piece of code that is not complete?
e.g
```
void foo(){ print("format this code");}
```
to
```
void foo(){ 
  print("format this code");
}
```
I have a use case wherein I have a source code entered in the text field widget and I would like to get it formatted with the dart style, I tried with the example shown in the readme. 

```
if·(tag=='style'||tag=='script'&&(type==null||type·==·TYPE_JS
······||type==TYPE_DART)||
··tag=='link'&&(rel=='stylesheet'||rel=='import'))·{}
}
```

but I am getting an error.

```
  
════════ Exception caught by gesture ═══════════════════════════════════════════
Could not format because the source could not be parsed:

line 1, column 1 of .: 'if' can't be used as an identifier because it's a keyword.
  ╷
1 │ if (tag=='style'||tag=='script'&&(type==null||type == TYPE_JS
  │ ^^
  ╵
line 1, column 8 of .: Expected to find ')'.
  ╷
1 │ if (tag=='style'||tag=='script'&&(type==null||type == TYPE_JS
  │        ^^
  ╵
════════════════════════════════════════════════════════════════════════════════

```
This is how I am formatting the code

```
ElevatedButton(
    onPressed: () {
       var formatter = new DartFormatter();
       String source = formatter.format(specs.sourceCode);
       textController.text = source;
     },
     child: Text('format code')
);
```
It would be really great if someone could help me.
Let me know if you need any additional info.

**Comment by munificent** [comment]
The command line interface only supports parsing entire compilation units (i.e. Dart source files). Since an `if` statement can't occur at the top level of a Dart program, you get a syntax error. The easiest way to use the CLI to format a single statement is to wrap the input in a function yourself and then strip the wrapper back off from the result, like:

```dart
main() {
// CODE START
  code.you.want.to.format.here();
// CODE END
}
```

If you want to run the formatter by calling it from Dart code, then the DartFormatter class exposes a [`formatStatement()`](https://pub.dev/documentation/dart_style/latest/dart_style/DartFormatter/formatStatement.html) method for parsing and formatting a single statement.

**Comment by maheshmnj** [comment]
I think there some problem with the formatter, I gave this piece of code(Already formatted) to the formatter. It did not threw any error but adding or removing a single white space its throwing the parse error.

```
main() {
  var formatter = new DartFormatter();

  try {
    print(formatter.format("""
    library an_entire_compilation_unit;

    class SomeClass {}
    """));

    print(formatter.formatStatement("aSingle(statement);"));
  } on FormatterException catch (ex) {
    print(ex);
  }
}
```

**Comment by maheshmnj** [comment]
Thanks, I found the issue it was with the textfield it was adding a dot (".")in place of  white space.

**Comment by munificent** [comment]
The code you are trying to format in your second example is no longer a statement. It's a library. For that you need `format()`, not `formatStatement()`.
