### ISSUE TITLE
Unnormal dartfmt behavior.

### ISSUE THREAD

**Issue by kirill-21** [dart-lang/dart_style#1017]
When i use dartfmt(via the latest intellij idea) it formats my code like this: https://i.stack.imgur.com/8YvY1.png
```
if (antivirus.first != 'Windows Defender' &&
              (Directory(antivirus[2]).existsSync() ||
                  File(antivirus[2]).existsSync() ||
                  Directory(antivirus[3]).existsSync() ||
                  File(antivirus[3]).existsSync())) {
            print(1);
          }
```

But normally code should look something like this: https://i.stack.imgur.com/JMzDg.png
```
if (
  antivirus.first != 'Windows Defender' &&
  (Directory(antivirus[2]).existsSync() ||
    File(antivirus[2]).existsSync() ||
    Directory(antivirus[3]).existsSync() ||
    File(antivirus[3]).existsSync()
  )
) {
  print(1);
}
```
Am i wrong and the formatting from picture-1 is good or there is something wrong with dartfmt tool?

**Comment by munificent** [comment]
I'm not sure what you mean by "normally". Dartfmt never puts a `)` on its own line unless there is a trailing comma on the previous one, so the formatting you get is expected.

**Comment by munificent** [comment]
OK, I'm seeing enough unsatisfied users that I'm going to roll this change back to the previous behavior. When the initial request was filed to flatten the indentation, there was almost no pushback, but I guess that's because people happy with the current behavior didn't see the issue.

**Comment by kirill-21** [comment]
> OK, I'm seeing enough unsatisfied users that I'm going to roll this change back to the previous behavior. When the initial request was filed to flatten the indentation, there was almost no pushback, but I guess that's because people happy with the current behavior didn't see the issue.

What does that mean?

**Comment by munificent** [comment]
Oops, sorry. I meant to write that comment in response to a different issue. Sorry for the confusion. :)
