### ISSUE TITLE
Behavior change for nested ternary operators 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart_style#1018]
This is the output from the latest dev compared with 2.12.0 stable. I believe this is new as of the very latest dev release, `2.13.0-211.0.dev`.

Old behavior:

```dart
var x = 1 == 2
    ? 3
    : 4 == 5
        ? 6
        : 7;
```

New behavior:

```dart
var x = 1 == 2
    ? 3
    : 4 == 5
    ? 6
    : 7;
```

**Comment by munificent** [comment]
Yeah, this is working as intended and was a deliberate formatting change. See: #722.

**Comment by jamesderlin** [comment]
The specific PR that introduced this was https://github.com/dart-lang/dart_style/pull/1012.  I left a comment there, although I would have used this issue to voice my concerns had I found it first.

**Comment by a14n** [comment]
Same here the new style is really confusing to read. IMHO it would be clearer to have:

```dart
var x = 1 == 2 ? 3
    : 4 == 5 ? 6
    : 7 == 8 ? 9
    : 10;
```

or 

```dart
var x = 
    1 == 2 ?
      3
  : 4 == 5 ?
      6
  : 7 == 8 ?
      9
  : 
      10;
```

or 

```dart
var x = 1 == 2
      ? 3
    : 4 == 5
      ? 6
    : 7 == 8
      ? 9
      : 10;
```

**Comment by munificent** [comment]
OK, I'm seeing enough unsatisfied users that I'm going to roll this change back to the previous behavior. When the initial request was filed to flatten the indentation, there was almost no pushback, but I guess that's because people happy with the current behavior didn't see the issue.
