### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by YuriCstr** [dart-lang/dart_style#1026]
Hi, check the requirement of 2 spaces. I would like the amount of spaces to be defined by me and not be a requirement of the language.

**Comment by munificent** [comment]
Two spaces of indentation is not a requirement of the Dart language, but it is a deliberate choice for the formatter to not be configurable. See here for more: https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it
