### ISSUE TITLE
[analyzer/format] Format exception when using `@Deprecated` with constructor's argument

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/dart_style#1027]
Run `dart format` for code below.

```dart
class A {
  const A({
    @Deprecated('Some deprecations')
    required this.id,
  });
}
```

And it'll turns into:
```dart
class A {
  const A({
    @Deprecated('Some deprecations')
        required this.id,
  });
}
```

This tracker is for issues related to: Analyzer

* Dart SDK Version: 2.13.1
* macOS BigSur

**Comment by munificent** [comment]
When I try, I get:

```dart
class A {
  const A({
    @Deprecated('Some deprecations') required this.id,
  });
}
```

Is there a larger example that you're running into issues with?

**Comment by AlexV525** [comment]
They're actually the same result, since the `required` keyword is not recognized.

```dart
class A {
  const A({
    @Deprecated('Code is deprecated in 2.0.0. Use status instead.')
        required this.code,
  });

  @Deprecated('Code is deprecated in 2.0.0. Use status instead.')
  final dynamic code;
}
```

![image](https://user-images.githubusercontent.com/15884415/121279587-61575700-c907-11eb-95b0-f8ed9f70f013.png)

**Comment by munificent** [comment]
Ah, so I dug through the history (been working on dart_style so long that sometimes even I forget how it's supposed to behave) and it turns out that this formatting is deliberate. The formatter used to *not* indent parameters when preceding metadata annotations caused it to wrap and I got [fairly clear feedback that the indentation was preferred](https://github.com/dart-lang/dart_style/issues/444). When I fixed it to indent, I don't recall any complaints, so I think the current behavior is probably what most users prefer.

**Comment by AlexV525** [comment]
I agreed with the previous issue you've referenced, but I don't think the `required` keyword works well here. Should I submit a new issue for it?

**Comment by munificent** [comment]
> I don't think the `required` keyword works well here.

I don't know if I'd say it looks *great*, but it looks reasonable to me. I think it would look really weird to indent parameters that don't have `required` but not indent ones that do:

```dart
class A {
  const A({
    @Deprecated('Some deprecations')
    required this.id,

    @Deprecated('Some deprecations')
        this.somethingOptional,

    @Deprecated('Some deprecations')
    required this.anotherMandatory,

    @Deprecated('Some deprecations')
    this.alsoOptional,
  });
}
```

Also, the indentation on `required` is consistent with how it indents parameters marked `final` or `covariant`.

**Comment by AlexV525** [comment]
Sorry, but we seems discussing the different thing? See the screenshot below (the `required` keyword is white which is not recognized as a keyword):

![image](https://user-images.githubusercontent.com/15884415/122317445-229d4e80-cf50-11eb-8bdf-aec01c47248a.png)

**Comment by AlexV525** [comment]
Hmm, if you agree with this, please help me reopen it. I do think the issue is valid, except the indent part.

**Comment by munificent** [comment]
> Sorry, but we seems discussing the different thing? See the screenshot below (the `required` keyword is white which is not recognized as a keyword):

The formatter isn't involved in syntax highlighting. :) That's up to your editor/IDE.

**Comment by AlexV525** [comment]
> The formatter isn't involved in syntax highlighting. :)

Oh sorry, you're right. It should be involved with the analyzer.

**Comment by AlexV525** [comment]
I have to bring this up again because I'm getting different results when using the formatter from `dart_style` and `dart format` with `@Deprecated` and `@deprecated`. More details: https://github.com/FlutterGen/flutter_gen/pull/401

**Comment by AlexV525** [comment]
According to failing checks, `@Deprecated` indents are also different on different platforms.

**Comment by AlexV525** [comment]
Other annotations seem well-formatted so it should be only related to the `@Deprecated` annotation.
![image](https://github.com/dart-lang/dart_style/assets/15884415/56baa978-1ee3-4462-bd5f-ecb51f9554ed)

**Comment by munificent** [comment]
> I have to bring this up again because I'm getting different results when using the formatter from `dart_style` and `dart format` with `@Deprecated` and `@deprecated`. More details: [FlutterGen/flutter_gen#401](https://github.com/FlutterGen/flutter_gen/pull/401)

This is most likely because you're using a different version of dart_style as a package than the version that's embedded in your Dart SDK and run through `dart format`. The formatting for metadata annotations on function parameters [changed in the most recent release](https://github.com/dart-lang/dart_style/blob/main/CHANGELOG.md#232).

If you run:

```sh
dart format --version
```

It will tell you the version of dart_style that's in the SDK. Compare that to the version you see when you run:

```sh
dart run dart_style:format --version
```
