### ISSUE TITLE
Formatting of empty catch blocks can appear misleading

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/dart_style#1029]
`dart format` really likes to collapse empty `{}` blocks onto a single line.  However, in the case of a `try`-`catch`-`finally` chain,  I think that it would be better not to do that if there is an non-empty block of statements later in the chain.  For example:

```dart
void main() {
  try {
    doSomething();
  } on Exception catch (e) {
  } finally {
    cleanupSomething();
  }
}
```
`dart format` (version 2.13.1 stable) formats it as:
```dart
void main() {
  try {
    doSomething();
  } on Exception catch (e) {} finally {
    cleanupSomething();
  }
}
```
which I think is rather misleading since it appears that `cleanupSomething()` is called only in response to a thrown `Exception`.

**Comment by munificent** [comment]
Yeah, I agree the formatting isn't ideal here. It should be fairly straightforward to fix.

However, I'll also point out that having an entirely empty catch block without even a comment explaining why you're ignoring an exception might not be ideal code either. :)
