### ISSUE TITLE
Using '[]' to construct empty list causes indentation to break thereafter.

### ISSUE THREAD

**Issue by Oklahomawhore** [dart-lang/dart_style#1030]
## Description: 
I'm using Android Studio to develop flutter app.
but dartfmt somehow breaks.

## Issue:
dartfmt indent breaks when using a '[]' constructor for empty list,

Sample code: 
```
var emptyList;
    emptyList = _comments!.isEmpty ? [] : _comments; //uses [] to construct empty list here.
    for (int i = 0;i<20;i++) {
      if (emptyList != null) {
        
    } // notice this line loses its indentation, and all the lines below.
      
    }
```

**Comment by munificent** [comment]
Hi, I can't repro the issue you describe here. The output I get is:

```dart
  var emptyList;
  emptyList = _comments!.isEmpty ? [] : _comments;
  for (int i = 0; i < 20; i++) {
    if (emptyList != null) {}
  }
```

Which is what I expected. Can you give me any details on what you're running into?

**Comment by Oklahomawhore** [comment]
@munificent 
Maybe it's related to flutter's build method.

I have a standalone dart source here to repro this.

```test_indent.dart



import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';

class Fabio extends StatelessWidget{
  
  List? _emptyList;
  
  Fabio(bool create) {
    
    _emptyList = create ? [] : List.filled(5, 5);
    if (_emptyList is List) {
      
    }
    
  }
  
  @override
  Widget build(BuildContext context) {
    
    
    var items;
    
    if (kIsWeb) {
      items = _emptyList!.isEmpty ? [] : _emptyList!.getRange(0, _emptyList!.length).toList();
      if (items != null) {
        
    }
  //^actual
  //  ^expected   
    }
    
    return Container();
  }
  
  
}
```

**Comment by Oklahomawhore** [comment]
Notice that on line 30 the closing bracket is not correctly indent.
It's a situation I created to demo this, from line 30 on the indentation system will not work properly.

**Comment by Oklahomawhore** [comment]
if you input after the comment and use return to change line, the closing brackets will not be at it's right place.

**Comment by Oklahomawhore** [comment]
> Hi, I can't repro the issue you describe here. The output I get is:
> 
> ```dart
>   var emptyList;
>   emptyList = _comments!.isEmpty ? [] : _comments;
>   for (int i = 0; i < 20; i++) {
>     if (emptyList != null) {//***Insert Return Here***//}
>   }
> ```
> 
> Which is what I expected. Can you give me any details on what you're running into?

You'll have to use return to change line, and you'll see the problem

**Comment by munificent** [comment]
> if you input after the comment and use return to change line, the closing brackets will not be at it's right place.

Ah, OK. That behavior is not coming from dartfmt. That is the IDE you're using that decides how much indentation to add when you insert a new line. Dartfmt doesn't get involved until you tell it to reformat the entire file. You may want to file an issue on the bug tracker for whatever IDE or editor you're using.
