### ISSUE TITLE
Formatting overflows, different indentation depending on trailing `,`.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart_style#1038]
I have code of the form:
```dart
class Something {
  void func(int arg) {
    if (arg == 0) {
      if (arg == 0) {
        throw ArgumentError.value(
            arg,
            "arg",
            "Long text.........................................................."
                " continued.....................................................");
      }
    }
  }
}
```
This makes the `);` overflow the 80-char line length by precisely 2 characters.
If I add a trailing comma after the second line, I get:
```dart
class Something {
  void func(int arg) {
    if (arg == 0) {
      if (arg == 0) {
        throw ArgumentError.value(
          arg,
          "arg",
          "Long text.........................................................."
              " continued.....................................................",
        );
      }
    }
  }
}
```
which unindents all the arguments by two characters.

Why is there a difference in indentation depending on the trailing comma? (Mostly curious, I though all it did was force elements to be on separate lines, and force a newline after the trailing comma).

Why is the `);` not moved to a new line without the trailing comma, when that would have made the line stay within 80 characters?

**Comment by munificent** [comment]
> Why is there a difference in indentation depending on the trailing comma?

Trailing commas were added to the Dart language at the request of the Flutter team. So when I added support for them, I formatted them based on Flutter's formatting style.

> Why is the `);` not moved to a new line without the trailing comma, when that would have made the line stay within 80 characters?

Without a trailing comma, the formatter never splits before a closing `)`. This is consistent with how people hand-format code in that style and follows similar formatting styles in other languages. It's always worked this way.
