### ISSUE TITLE
Indentation is an accessibility issue that is being unfairly disregarded

### ISSUE THREAD

**Issue by fishpowered** [dart-lang/dart_style#1057]
I read the previous discussion about [tabs vs spaces](https://github.com/dart-lang/dart_style/issues/534) but I am reopening it because I feel the developer unfairly disregarded accessibility issues.

Here is a quote from the developer who decided this:
"_I am very sensitive to this issue, but I have yet to see evidence that the current indentation rules have accessibility problems._"

How exactly does one provide _evidence_ that they struggle to read something? Just because YOU don't have issues doesn't mean others don't.

I'm afraid I don't have any evidence of my struggles but here is a good blog post explaining some examples:
[https://dev.to/alexandersandberg/why-we-should-default-to-tabs-instead-of-spaces-for-an-accessible-first-environment-101f](https://dev.to/alexandersandberg/why-we-should-default-to-tabs-instead-of-spaces-for-an-accessible-first-environment-101f)

We don't enforce fonts, font sizes, line-spacing, letter spacing, and colours on developers so why should we enforce indentation size. This is something that can easily be solved by using tabs as a convention instead of spaces then we get to have our nice one format for all approach without being exclusive to people's needs.

Browser's support [styling tabs](https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size) these days and even if a web site prefers to render code with spaces, it doesn't matter because you are always going to have to reformat code that is pasted into an editor anyway. It can also be easily triggered when saving/comitting.

Some IDE's allow you to reformat indentation on the fly but Android Studio doesn't for dart and besides I've attempted this approach before and it's constantly causing issues. Not using the formatter is not an option either because I obviously want to standardise my formatting but not at the expense of being able to read the code without getting eye strain.

**Comment by fishpowered** [comment]
So if ever someone who works with those languages or at Google ever complains about indentation they're just told "we have this implemented in millions of lines of code and it's used by millions of people so it must be accessible". 

"Because indentation is encoded in the source file itself while all of the other properties you describe are not."

Line length is essentially encoded in the source file but you still mandate that for readability reasons.

Anyway, I have found relief by cranking the font size up and I'm quite sure I won't change your mind so this will be my last post. Feel free to close the thread.

**Comment by munificent** [comment]
> "Because indentation is encoded in the source file itself while all of the other properties you describe are not."
> 
> Line length is essentially encoded in the source file but you still mandate that for readability reasons.

Yes, these two points are consistent with each other. We mandate the visual properties of a program that are stored in the source file (indentation, line length) and not the properties that are not (font size, color, line spacing).
