### ISSUE TITLE
Cascade identation

### ISSUE THREAD

**Issue by duzenko** [dart-lang/dart_style#1064]
Noticed a formatting change after upgrade from flutter 2.2.3 to 2.51
I think flutter upgrades should not cause potentially sweeping reformattings across big projects
Now: 
```
        _connection = HubConnectionBuilder()
            .withUrl(
              '${Config.SIGNALR_BASE_URL}$_hubName$_queryParams',
              HttpConnectionOptions(
                accessTokenFactory: _accessTokenFactory,
                transport: HttpTransportType.webSockets,
              ),
            )
            .build()
          ..keepAliveIntervalInMilliseconds =
              kDefaultKeepAliveIntervalInMilliseconds
          ..serverTimeoutInMilliseconds = kDefaultServerTimeoutInMilliseconds;
```
Was
```
        _connection = HubConnectionBuilder()
            .withUrl(
              '${Config.SIGNALR_BASE_URL}$_hubName$_queryParams',
              HttpConnectionOptions(
                accessTokenFactory: _accessTokenFactory,
                transport: HttpTransportType.webSockets,
              ),
            )
            .build()
              ..keepAliveIntervalInMilliseconds =
                  kDefaultKeepAliveIntervalInMilliseconds
              ..serverTimeoutInMilliseconds =
                  kDefaultServerTimeoutInMilliseconds;
```

**Comment by munificent** [comment]
> I think flutter upgrades should not cause potentially sweeping reformattings across big projects

The change was proposed [here](https://groups.google.com/a/dartlang.org/g/announce/c/vtVNkL90xG8) and discussed [here](https://github.com/dart-lang/dart_style/pull/1033) where it got 73 thumbs up and no negative feedback. I'm always cautious about format changes, but this one was seems to pretty clearly be an improvement.

The output you're seeing now is deliberate and, I think, better. In particular, it makes it clearer that the `..keepAliveIntervalInMilliseconds` applies to the result of `.build()` and not `HubConnectionBuilder()`.
