### ISSUE TITLE
Comments and variables get moved around

### ISSUE THREAD

**Issue by LeoBound** [dart-lang/dart_style#1073]
The formatter shuffles my comments and variables around e.g.

```
/// The following unit conversions convert into the base SI units (kg, m, s)
///
/// e.g. 15 mg/L * `milligramPerLitre` = 0.015 kg/m^3
/// If you wanted this in kg/hl you could then do
/// 0.015 kg/m^3 / `kilogramPerHectolitre` = 0.0015 kg/hl

const double milligramPerLitre = 0.001;
const double kilogramPerHectolitre = 10;
```

Becomes

```
const double kilogramPerHectolitre = 10;

/// The following unit conversions convert into the base SI units (kg, m, s)
///
/// e.g. 15 mg/L * `milligramPerLitre` = 0.015 kg/m^3
/// If you wanted this in kg/hl you could then do
/// 0.015 kg/m^3 / `kilogramPerHectolitre` = 0.0015 kg/hl

const double milligramPerLitre = 0.001;
```

Which as you can imagine is quite irritating.

It also doesn't keep end of line comments with their respective lines e.g.
```
var variableA; //A
var variableC; //C
var variableB; //B
```
gets reordered to
```
var variableA; //A
var variableB; //C
var variableC; //B
```

I'm using VSCode with the setting :"dart.enableSdkFormatter": true

Thanks for your help

**Comment by munificent** [comment]
I'm not sure what's going on, but I'm certain it's not `dart format` that's doing this. It doesn't reorder code at all and in fact has internal sanity checks to ensure that the output non-whitespace characters are always in the exact same order as the input.

This is probably some other VSCode command like "reorder members" that's getting run.
