### ISSUE TITLE
Please let us customize the rules that dartfmt use to format our code

### ISSUE THREAD

**Issue by benjdero** [dart-lang/dart_style#1077]
I've worked for 2 years with Flutter having to do manual code formatting because of how terrible it look if I use this tool to auto format my code. Today I decided to give it another try because it is just so much time consuming to manually format code. Here is some examples of the worst code formatting I've seen in my code base.

Before
```dart
showDialog(
  context: context,
  builder: (context) =>
    AlertDialog(
      content: const Text('Are you sure you want to delete this item?'),
      actions: <Widget>[
        TextButton(
          child: const Text('CANCEL'),
          onPressed: () => Navigator.pop(context, false)
        ),
        TextButton(
          child: const Text('OK'),
          onPressed: () => Navigator.pop(context, true)
        ),
      ],
    ),
)
```
After
```dart
showDialog(
  context: context,
  builder: (context) => AlertDialog(
    content: const Text(
        'Are you sure you want to delete this item?'),
    actions: <Widget>[
      TextButton(
          child: const Text('CANCEL'),
          onPressed: () => Navigator.pop(context, false)),
      TextButton(
          child: const Text('OK'),
          onPressed: () => Navigator.pop(context, true)),
    ],
  ),
)
```
----------------------------------
Before
```dart
DateTime(
  d.year - 1,
  d.month,
  d.day,
  d.hour,
  d.minute,
  d.second,
  d.millisecond,
  d.microsecond
),
```
After
```dart
DateTime(d.year - 1, d.month, d.day, d.hour, d.minute, d.second,
    d.millisecond, d.microsecond),
```
----------------------------------
Before
```dart
theme: ThemeData(
  primarySwatch: kPrimarySwatch, // Primary color palette
  primaryColorLight: kPrimaryColorLight, // Main background color (appbar, card)
  elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        onPrimary: kPrimaryColorLight,
      )
  ),
),
```
After
```dart
theme: ThemeData(
  primarySwatch: kPrimarySwatch,
  // Primary color palette
  primaryColorLight: kPrimaryColorLight,
  // Main background color (appbar, card)
  elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
    onPrimary: kPrimaryColorLight,
  )),
),
```

**PLEASE**. Let us customize the rules that dartfmt use to format our code. Dart is such a terrible language already, at least let us make it prettier and easier to read.

**Comment by srawlins** [comment]
As an aside to the customization request, I think each of the examples you provide can be made as you desire with trailing commas. If you add a trailing comma to:

* `onPressed: () => Navigator.pop(context, false)`,
* `d.microsecond`, and
* `)` (after `onPrimary: kPrimaryColorLight,`),

you'll get the indentation you want. The experimental [require_trailing_commas](https://dart-lang.github.io/linter/lints/require_trailing_commas.html) lint rule will enforce this style.

**Comment by munificent** [comment]
@srawlins is correct here. The formatting you want is available, you just have to tell the formatter you want it by using a trailing comma.

**Comment by 18601673727** [comment]
> As an aside to the customization request, I think each of the examples you provide can be made as you desire with trailing commas. If you add a trailing comma to:
> 
> * `onPressed: () => Navigator.pop(context, false)`,
> * `d.microsecond`, and
> * `)` (after `onPrimary: kPrimaryColorLight,`),
> 
> you'll get the indentation you want. The experimental [require_trailing_commas](https://dart-lang.github.io/linter/lints/require_trailing_commas.html) lint rule will enforce this style.

By setting `require_trailing_commas: true` in `analysis_options.yaml` literally saved my eyes from going blind, thank you sir for greatly improving my health!
