### ISSUE TITLE
Publish a version that is compatible with analyzer 3.0.0

### ISSUE THREAD

**Issue by scheglov** [dart-lang/dart_style#1078]

**Comment by scheglov** [comment]
Note, https://dart-review.googlesource.com/c/sdk/+/224520 which makes a number of experiments expired. This breaks a few `dart_style` tests. I will try to look how to fix these, but wanted to warn sooner.

**Comment by scheglov** [comment]
https://github.com/dart-lang/dart_style/pull/1080 fixes tests that started failing with the CL that marks experiments expired.

**Comment by munificent** [comment]
Published 2.2.1.
