### ISSUE TITLE
Formatter is slow on very deeply nested code

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_style#108]
@leafpetersen brought this fun one to my attention. This is generated code, so it's a bit pathological, but the following statement takes several seconds to format:

```dart
if (javaBooleanAnd(
    javaBooleanAnd(
        javaBooleanAnd(
            javaBooleanAnd(
                javaBooleanAnd(
                    javaBooleanAnd(
                        javaBooleanAnd(
                            javaBooleanAnd(
                                javaBooleanAnd(
                                    javaBooleanAnd(
                                        javaBooleanAnd(
                                            javaBooleanAnd(
                                                _isEqualNodes(
                                                    node.documentationComment,
                                                    toNode.documentationComment),
                                                _isEqualNodeLists(
                                                    node.metadata,
                                                    toNode.metadata)),
                                            _isEqualTokens(
                                                node.externalKeyword,
                                                toNode.externalKeyword)),
                                        _isEqualTokens(
                                            node.constKeyword,
                                            toNode.constKeyword)),
                                    _isEqualTokens(
                                          node.factoryKeyword,
                                          toNode.factoryKeyword)),
                                _isEqualNodes(
                                    node.returnType,
                                    toNode.returnType)),
                            _isEqualTokens(
                                node.period,
                                toNode.period)),
                        _isEqualNodes(
                            node.name,
                            toNode.name)),
                    _isEqualNodes(
                        node.parameters,
                        toNode.parameters)),
                _isEqualTokens(
                    node.separator,
                    toNode.separator)),
            _isEqualNodeLists(node.initializers, toNode.initializers)),
        _isEqualNodes(
            node.redirectedConstructor,
            toNode.redirectedConstructor)),
    _isEqualNodes(node.body, toNode.body))) {
  toNode.element = node.element;
}
```

I hand-formatted the above to show how deeply nested it is. The formatter outputs:

```dart
if (javaBooleanAnd(javaBooleanAnd(javaBooleanAnd(javaBooleanAnd(javaBooleanAnd(
        javaBooleanAnd(javaBooleanAnd(javaBooleanAnd(javaBooleanAnd(
                javaBooleanAnd(javaBooleanAnd(javaBooleanAnd(_isEqualNodes(
                                node.documentationComment,
                                toNode.documentationComment),
                            _isEqualNodeLists(node.metadata, toNode.metadata)),
                        _isEqualTokens(
                            node.externalKeyword, toNode.externalKeyword)),
                    _isEqualTokens(node.constKeyword, toNode.constKeyword)),
                _isEqualTokens(node.factoryKeyword, toNode.factoryKeyword)),
            _isEqualNodes(node.returnType, toNode.returnType)), _isEqualTokens(
            node.period,
            toNode.period)), _isEqualNodes(node.name, toNode.name)),
        _isEqualNodes(node.parameters, toNode.parameters)), _isEqualTokens(
        node.separator, toNode.separator)),
    _isEqualNodeLists(node.initializers, toNode.initializers)), _isEqualNodes(
    node.redirectedConstructor,
    toNode.redirectedConstructor)), _isEqualNodes(node.body, toNode.body))) {
  toNode.element = node.element;
}
```

This statement has 52 params, 13 levels of nesting, 50 spans, and generates about 50k entries in the memoization table.

Code like this is rare in the wild, and hand-written code of this sort is even rarer, but the formatter should still be faster.

One option is to have a formatting threshold (probably based on memoization table size). If the splitter crosses that, it gives up and just enables every single split and produces maximally split output. That would probably produce a more readable result than the compact output it produces here.

**Comment by munificent** [comment]
Also (from Angular.dart):

```dart
class ElementBinder {
  DirectiveInjector bind(
      View view, Scope scope, DirectiveInjector parentInjector, dom.Node node) {
    if (bindAssignableProps.isNotEmpty) {
      _bindAssignablePropsOn.forEach((String eventName) => node
          .addEventListener(eventName, (_) => zone.run(() => bindAssignableProps
              .forEach((propAndExp) => propAndExp[1].assign(
                  scope.context, jsNode[propAndExp[0]])))));
    }
  }
}
```dart

which takes a few seconds and ends up with:

```dart
class ElementBinder {
  DirectiveInjector bind(
      View view, Scope scope, DirectiveInjector parentInjector, dom.Node node) {
    if (bindAssignableProps.isNotEmpty) {
      _bindAssignablePropsOn.forEach((String eventName) => node
          .addEventListener(eventName, (_) => zone.run(() => bindAssignableProps
              .forEach((propAndExp) => propAndExp[1].assign(
                  scope.context, jsNode[propAndExp[0]])))));
    }
  }
}
```dart

It has 23 split params, and 14 levels of nesting.

**Comment by munificent** [comment]
One optimization I had in mind is to discard any nesting levels that are not actually used at the end of any chunk. You can run into a situation where some nesting levels get skipped over because of multiple nest calls before a single token.

The splitter still considers them even though they never get chosen. Before splitting, we can renumber the nesting levels to fill in those holes. Roughly:

```dart
    var nestingLevels = _chunks
        .map((chunk) => chunk.nesting)
        .where((nesting) => nesting != -1)
        .toSet()
        .toList();
    nestingLevels.sort();

    var nestingMap = {-1: -1};
    for (var i = 0; i < nestingLevels.length; i++) {
      nestingMap[nestingLevels[i]] = i;
    }

    for (var chunk in _chunks) {
      chunk.nesting = nestingMap[chunk.nesting];
    }
```

On one example, this led to a 100x improvement, but even so the line still took ~3s to format.

**Comment by munificent** [comment]
Here's another example:

```dart
async.Future<List<dom.StyleElement>> call(String tag, List<String> cssUrls, {Type type}) => (DDC$RT.cast(async.Future.wait((DDC$RT.cast(cssUrls.map((url) => _styleElement(tag, (DDC$RT.cast(url, String, key: "Cast failed: package:angular/core_dom/component_css_loader.dart:17:65")), type)), DDC$RT.type((Iterable<Future<dynamic>> _) {}), key: "Cast failed: package:angular/core_dom/component_css_loader.dart:17:25"))), DDC$RT.type((Future<List<StyleElement>> _) {}), key: "Cast failed: package:angular/core_dom/component_css_loader.dart:17:7"));
```dart

**Comment by patefacio** [comment]
Here might be another example of this issue:

    import 'package:dart_style/dart_style.dart';
    main() {
      final formatter = new DartFormatter();
      var txt = original;
      print(original);
      try {
        print('formatting');
        txt = formatter.format(txt);
      } catch(e) {
        print('Caught exception $e');
      }
      print('Text is still changing ${txt == formatter.format(txt)}\n');
      print(txt);
    }


    final original = r"""
    #!/usr/bin/env dart
    ///
    /// xargs.dart [OPTIONS] [PATTERN...]
    ///
    /// A script for indexing directories for the purpose of doing find/greps
    /// on those indices.
    ///
    /// If no arguments are provided, a list of existing indices will be
    /// displayed.
    ///
    /// If one or more indices is supplied without other arguments, a list of
    /// files in the index (indices) will be output. Effectively a *find*
    /// operation.
    ///
    /// If a single index is supplied with any paths it will be considered an
    /// index definition and first persist the index and then update it.
    ///
    /// If one or more indices is supplied with the update flag set, the
    /// databases for the index (indices) will be updated (e.g. *updatedb*
    /// will be called to re-index)
    ///
    /// If one or more indices is supplied with one additional argument, that
    /// argument is the grep pattern and is grepped on all files in all
    /// specified indices.
    ///
    /// If one positional argument is provided without indices or any other
    /// arguments a the prior search is replacing the grep pattern with the
    /// positional argument.
    ///
    ///

    import 'dart:async';
    import 'dart:io';
    import 'package:args/args.dart';
    import 'package:id/id.dart';
    import 'package:logging/logging.dart';
    import 'package:xgrep/xgrep.dart';

    //! The parser for this script
    ArgParser _parser;

    //! The comment and usage associated with this script
    void _usage() {
      print('''

    xargs.dart [OPTIONS] [PATTERN...]

    A script for indexing directories for the purpose of doing find/greps
    on those indices.

    If no arguments are provided, a list of existing indices will be
    displayed.

    If one or more indices is supplied without other arguments, a list of
    files in the index (indices) will be output. Effectively a *find*
    operation.

    If a single index is supplied with any paths it will be considered an
    index definition and first persist the index and then update it.

    If one or more indices is supplied with the update flag set, the
    databases for the index (indices) will be updated (e.g. *updatedb*
    will be called to re-index)

    If one or more indices is supplied with one additional argument, that
    argument is the grep pattern and is grepped on all files in all
    specified indices.

    If one positional argument is provided without indices or any other
    arguments a the prior search is replacing the grep pattern with the
    positional argument.


    ''');
      print(_parser.getUsage());
    }

    //! Method to parse command line options.
    //! The result is a map containing all options, including positional options
    Map _parseArgs(List<String> args) {
      ArgResults argResults;
      Map result = { };
      List remaining = [];

      _parser = new ArgParser();
      try {
        /// Fill in expectations of the parser
        _parser.addFlag('update',
          help: '''
    If set will update any specified indices
    ''',
          abbr: 'u',
          defaultsTo: false
        );
        _parser.addFlag('remove-index',
          help: '''
    If set will remove any specified indices
    ''',
          abbr: 'r',
          defaultsTo: false
        );
        _parser.addFlag('remove-all',
          help: '''
    Remove all stored indices
    ''',
          abbr: 'R',
          defaultsTo: false
        );
        _parser.addFlag('list',
          help: '''
    For any indices provided, list all files. Effectively *find* on the index.
    ''',
          abbr: 'l',
          defaultsTo: false
        );
        _parser.addFlag('help',
          help: '''
    Display this help screen
    ''',
          abbr: 'h',
          defaultsTo: false
        );

        _parser.addOption('index',
          help: '''
    Id of index associated with command
    ''',
          defaultsTo: null,
          allowMultiple: true,
          abbr: 'i',
          allowed: null
        );
        _parser.addOption('path',
          help: '''
    Colon separated fields specifying path with pruning. Fields are:
     1: The path to include
     2: One or more path names (i.e. unqualified folder names)
        to prune
     e.g. -p /home/gnome/ebisu:cache:.pub:.git

    ''',
          defaultsTo: null,
          allowMultiple: true,
          abbr: 'p',
          allowed: null
        );
        _parser.addOption('prune-name',
          help: '''
    Global prune names excluded from all paths
    ''',
          defaultsTo: null,
          allowMultiple: true,
          abbr: 'P',
          allowed: null
        );
        _parser.addOption('prune-path',
          help: '''
    Fully qualified path existing somewhere within a path to be excluded
    ''',
          defaultsTo: null,
          allowMultiple: true,
          abbr: 'X',
          allowed: null
        );
        _parser.addOption('grep-args',
          help: '''
    Arguments passed directly to grep
    ''',
          defaultsTo: null,
          allowMultiple: true,
          abbr: 'g',
          allowed: null
        );

        /// Parse the command line options (excluding the script)
        argResults = _parser.parse(args);
        if(argResults.wasParsed('help')) {
          _usage();
          exit(0);
        }
        result['index'] = argResults['index'];
        result['path'] = argResults['path'];
        result['prune-name'] = argResults['prune-name'];
        result['prune-path'] = argResults['prune-path'];
        result['update'] = argResults['update'];
        result['remove-index'] = argResults['remove-index'];
        result['remove-all'] = argResults['remove-all'];
        result['list'] = argResults['list'];
        result['grep-args'] = argResults['grep-args'];
        result['help'] = argResults['help'];

        return { 'options': result, 'rest': argResults.rest };

      } catch(e) {
        _usage();
        throw e;
      }
    }

    final _logger = new Logger('xgrep');

    main(List<String> args) {
      Logger.root.onRecord.listen((LogRecord r) =>
          print("${r.loggerName} [${r.level}]:\t${r.message}"));
      Logger.root.level = Level.INFO;
      Map argResults = _parseArgs(args);
      Map options = argResults['options'];
      List positionals = argResults['rest'];

      // custom <xgrep main>
      //Logger.root.level = Level.OFF;
      if (args.isEmpty) {
        print('**** Current Indices ****');
        Indexer.withIndexer((Indexer indexer) async {
          final indices = await indexer.indices;
          if (indices.isEmpty) {
            print('''
    You have no indices created yet. Consider creating some.
    For example:

    xgrep -i my_dart \\
       -p \$HOME/dev/open_source/xgrep:.pub:.git \\
       -p \$HOME/dev/open_source/ebisu:.pub:.git
    ''');
          } else {
            for (final index in indices) {
              print('---------- ${index.id.snake} ----------');
              final paths = index.paths;
              paths.keys.forEach((String path) {
                print('  $path');
                final pruneSpec = index.paths[path];
                pruneSpec.names.forEach((String pruneName) {
                  print('    prune:$pruneName');
                });
                pruneSpec.paths.forEach((String prunePath) {
                  print('    prune:$prunePath');
                });
              });
              index.pruneNames.forEach((String pruneName) {
                print('  prune:$pruneName');
              });
            }
          }
        });
      } else {
        final indices = options['index'];
        final paths = options['path'];
        final prunePaths = options['prune-path'];
        final pruneNames = options['prune-name'];
        final removeIndex = options['remove-index'];
        final removeAll = options['remove-all'];
        final list = options['list'];
        final update = options['update'];
        final grepArgs = options['grep-args'];
        print(options);

        _logger.info(() => 'indices:$indices, paths:$paths, prunePaths:$prunePaths,'
            'pruneNames:$pruneNames, removeAll:$removeAll, list:$list,'
            'removeIndes:$removeIndex, update:$update, grepArgs:$grepArgs');

        if (!indices.isEmpty) {
          if (indices.length == 1 && !paths.isEmpty) {
            // Define the index
            final map = {};
            for (final path in paths) {
              final parts = path.split(':');
              assert(!parts.isEmpty);
              map[parts.first] = (parts.length == 1)
                  ? emptyPruneSpec
                  : new PruneSpec([parts.sublist(1)], []);
            }
            final index = new Index.withPruning(idFromString(indices.first), map);
            Indexer.withIndexer((Indexer indexer) {
              return indexer.saveAndUpdateIndex(index);
            });
          } else {
            if (update) {
              positionalsCheck(positionals, '*update*');
              print('Updating $indices');
              Indexer.withIndexer((Indexer indexer) {
                final futures = [];
                indices.forEach((String idStr) {
                  futures.add(indexer.updateIndexById(idFromString(idStr)));
                });
                return Future.wait(futures);
              });
            } else if(list) {
              Indexer.withIndexer((Indexer indexer) {
                final futures = [];
                indices.forEach((String idStr) =>
                  futures.add(indexer.lookupIndex(idFromString(idStr))
                      .then((Index index) =>
                          (index != null? indexer.processPaths(index, (String path) => print(path)) : index))));
                print('Futures => $futures');
                return Future.wait(futures);
              });
            } else if (removeIndex) {
              positionalsCheck(positionals, '*remove*');
              print('Removing indices $indices');
              Indexer.withIndexer((Indexer indexer) => indices.forEach(
                  (String idStr) => indexer.removeIndex(idFromString(idStr))));
            } else {
              // Not removing specified indices. Either it is a request to update
              // indices or do a grep. If there is one positional arg that is the
              // grep arg, otherwise, it is an update
              if (!positionals.isEmpty || !grepArgs.isEmpty) {
                print(
                    'Doing grep of ${positionals.first} on $indices with args $grepArgs');
                final futures = [];
                positionals.forEach((String positional) => grepArgs.addAll(['-e', positional]));
                for (final id in indices) {
                  futures.add(grep(idFromString(id), grepArgs));
                }
                return Future.wait(futures);
              } else {
                print('Doing an update on $indices');
                Indexer.withIndexer((Indexer indexer) {
                  final futures = [];
                  indices.forEach((String idStr) {
                    final id = idFromString(idStr);
                    futures.add(indexer.lookupIndex(id).then((Index index) {
                      if (index == null) {
                        print('Could not find index <$id> - will not update!');
                      } else {
                        return indexer.updateIndex(index);
                      }
                    }));
                  });
                  return Future.wait(futures);
                });
              }
            }
          }
        } else {
          if (removeAll) {
            print('Are you sure you want to remove all indices: [N/Y]?');
            final ans = stdin.readLineSync();
            const doIt = const ['Y', 'y', 'yes', 'Yes'];
            if (doIt.contains(ans)) {
              print('Deleting all indices');
              Indexer
                  .withIndexer((Indexer indexer) => indexer.removeAllIndices())
                  .then((_) => print('Completed'));
            } else {
              print('Nothing removed: Dodged a bullet there');
            }
          }
        }
      }

      // end <xgrep main>

    }

    // custom <xgrep global>

    positionalsCheck(List<String> positionals, String tag) {
      if (!positionals.isEmpty) {
        print('''
    Will not $tag indices if additional positional args provided.
    The following args remain $positionals.''');
        exit(-1);
      }
    }

    // end <xgrep global>
    """;

**Comment by pq** [comment]
Another repro from #207:

>I tried to run the formatter over dart/pkg/analyzer/lib/src/generated/parser.dart from the Dart SVN repository (revision 44273) and it did not either produce output or exit. I used the version of the formatter from the SDK built from that same revision.

**Comment by munificent** [comment]
Yeah, that's the blob of code at the top of this bug. :)

**Comment by munificent** [comment]
This makes some progress on this: https://chromiumcodereview.appspot.com/987223002/
