### ISSUE TITLE
Indentation of multi-line expression body

### ISSUE THREAD

**Issue by yelliver** [dart-lang/dart_style#1083]
Firstly I thought this is my issue: https://github.com/dart-lang/dart_style/issues/957, but it turns out that it is just a case in a general weird Indentation of multi-line expression body. And moreover, in that issue, the curried functions is not common in Dart so it is not a high priority to fix, but I will give some example that is very common in Dart (especial in Flutter)

### Multiline expression body as the body of a function
```Dart
//GOOD: block body
test0a() {
  func1(() {
    print('foo');
    print('bar');
  });
}

//BAD: multiline expression body
test0b() => func1(() {
      print('foo');
      print('bar');
    });
```

### Multiline expression body as the param of a function
```Dart
test1a() {
  //GOOD: block body
  func1(() {
    func1(() {
      print('foo');
      print('bar');
    });
  });
}

test1b() {
  //BAD: multiline expression body
  func1(() => func1(() {
        print('foo');
        print('bar');
      }));
}

test1c() {
  //GOOD: multiline expression body if we insert an extra last comma in parma list
  func1(
    () => func1(() {
      print('foo');
      print('bar');
    }),
  );
}
```

### Multiline expression body as the 2nd param of a function
```Dart
test2a() {
  //GOOD: block body
  func2(1, () {
    func1(() {
      print('foo');
    });
  });
}

test2b() {
  //GOOD: block body, add extra comma  in param list
  func2(
    1,
    () {
      func1(() {
        print('foo');
      });
    },
  );
}

test2c() {
  //BAD: multiline expression body, not only BAD indentation but also BAD new line
  func2(
      1,
      () => func1(() {
            print('foo');
          }));
}

test2d() {
  //GOOD: multiline expression body, add extra comma  in param list
  func2(
    1,
    () => func1(() {
      print('foo');
    }),
  );
}
```

**Comment by munificent** [comment]
The [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) has quite different rules for handling function expressions inside argument lists. Here's the output the new formatter produces on the "bad" examples:

```dart
//BAD: multiline expression body
test0b() => func1(() {
  print('foo');
  print('bar');
});

test1b() {
  //BAD: multiline expression body
  func1(
    () => func1(() {
      print('foo');
      print('bar');
    }),
  );
}

test2c() {
  //BAD: multiline expression body, not only BAD indentation but also BAD new line
  func2(
    1,
    () => func1(() {
      print('foo');
    }),
  );
}
```

I don't think those are exactly what you had in mind, but that's the output I expect. It's consistent with how closures are handled in more complex argument lists and looks pretty good to me. So I think this is working like it should.
