### ISSUE TITLE
Indentation of name param without extra ending comma

### ISSUE THREAD

**Issue by yelliver** [dart-lang/dart_style#1084]
I give 3 var definitions and the a1 has bad indentation

```Dart
//GOOD
var a0 = A(
  child0: B(
    age: 5,
  ),
);

//BAD indentation
var a1 = A(
    child0: B(
  age: 5,
));

//??? I'm not sure this is by design or not but it's not nice
var a2 = A(
    child0: B(
      age: 5,
    ),
    child1: B(
      age: 5,
    ));
```

**Comment by munificent** [comment]
This is because your code contains a mixture of argument lists with and without trailing commas. The formatter uses different styles for each kind of argument list, so when you mix them, you get strange results. That's why `a0` looks fine.

**Comment by yelliver** [comment]
I agree that a1 is bad because it's mixed, but how about a2? does it look fine?

**Comment by munificent** [comment]
Add a trailing comma to the outer argument list and you get:

```dart
var a2 = A(
  child0: B(
    age: 5,
  ),
  child1: B(
    age: 5,
  ),
);
```
