### ISSUE TITLE
Super strange formatting on simple code

### ISSUE THREAD

**Issue by montella1507** [dart-lang/dart_style#1086]
Before format:
```
import 'package:flutter/material.dart';

void main() => runApp(
     MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            title: Text("Ahoj"),
          ),
          body: Text("haha"),
          bottomSheet: Text("okej"),
        )
    )
);
```

after format:
```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: Text("Ahoj"),
      ),
      body: Text("haha"),
      bottomSheet: Text("okej"),
    )));

```

Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "windows_x64"

**Comment by natebosch** [comment]
This looks like it is working as intended to me. If you prefer for the indentation to match the style common in flutter code you can add trailing commas to argument lists. https://github.com/dart-lang/sdk/commit/91e6801ae70cfa4a80f9c2fc4600d7f6ba11db70

**Comment by montella1507** [comment]
Is it really working as intended? Why should (As an example) the AppBar be intended less than home: Scaffold if home (scaffold) is actually the parent of the AppBar?  

Where can i find that "trailing commas" you talking about please?

Cannot find that in --help, neither on https://dart.dev/tools/dart-format or https://pub.dev/packages/dart_style

**Comment by montella1507** [comment]
Ah you meant in the sourcecode..

**Comment by munificent** [comment]
> Is it really working as intended? Why should (As an example) the AppBar be indented less than home: Scaffold if home (scaffold) is actually the parent of the AppBar?

It's not really *intended* but it's because your code contains a mixture of argument lists with and without trailing commas. Those two kinds of argument lists each have different formatting rules, and when you mix them, you get strange results.

**Comment by montella1507** [comment]
Okej, so the rule is just "place trailing commas everywhere, or nowhere".
