### ISSUE TITLE
New line on chained function calls

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/dart_style#1090]
I'm not sure if it is the right repository to ask this but I find this hard to read:

```dart
    subscription = _userRepository.getUser().takeUntil(closesStream).listen(
          (user) => setState(DataState.loaded(user)),
          onError: (e) => setState(DataError(e)),
        );
```

A better result in my opinion is achieved by adding a comment in the middle

```dart
    subscription = _userRepository
        .getUser() //
        .takeUntil(closesStream)
        .listen(
          (user) => setState(DataState.loaded(user)),
          onError: (e) => setState(DataError(e)),
        );
```

It just seems that adding the comment is a bit hacky. Well it's in the same ball park as is ending arrays with `,`. I don't see what's the gain of having to explicitly define the format in the code instead of a configuration file.

**Comment by munificent** [comment]
I agree, splitting the call chain looks better. I true this example out using the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253). Here's what it produces:

```dart
    subscription = _userRepository
        .getUser()
        .takeUntil(closesStream)
        .listen(
          (user) => setState(DataState.loaded(user)),
          onError: (e) => setState(DataError(e)),
        );
```

So I think we're good now (or at least will be when the new formatter ships).
