### ISSUE TITLE
remove the configurable line_length feature

### ISSUE THREAD

**Issue by NANASHI0X74** [dart-lang/dart_style#1115]
There's been much discussion about `dart format`'s --line-length parameter and the anguish and excess work that the lack of configurability of this parameter on a per-package basis via configuration files is causing in this feature request: #918

As it's apparent that this feature is not something the dart/dart_style team is interested in adding, may I propose going in the other direction and completely removing the ability to configure the line length?

I would personally not be completely happy with that, but the current situation is just a mess (which I do hope you recognize as well) and it needs to be addressed one way or another.

There's this proverb in go: [Gofmt's style is no one's favorite, yet gofmt is everyone's favorite.](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=8m43s) Which I think is pretty astute and instructive in this case. I think there's huge value for developers in having a consistent code format/style enforced and I think that's more valuable than giving developers the freedom to choose their own formatting rules- at least to an extent. I personally don't believe it's a good thing to enforce exacly the same style across the entire ecosystem of a language, I'd say that there are some parameters that it's better to just leave up to project maintainers to choose. But not having those parameters to configure is definitely better than to have them, but then not having any sensible way to enforce them apart from "out of band" methods like using commit hooks or sharing the configuration of the developers' editors (which doesn't work unless everyone uses the same editor, which opens a whole new fun can of worms 🙄)

**Comment by lukepighetti** [comment]
I personally think we should either get rid of the ability to configure line length altogether (as you suggest) or get the green light to implement a pubspec.yaml line length setting. What's not going to work for me is living this in the middle where the only thing it provides is pain.

**Comment by munificent** [comment]
Given how much anger already gets sent my way around line length, I can't imagine taking away control would do anything except make the people who care about this issue even angrier than they already are. And the people who aren't unhappy about this don't use the command line argument anyway, so having it there isn't harmful.

(Also, pragmatically, the formatter needs to support custom line lengths internally because its tests rely on that. So removing the configurability completely wouldn't let me simplify the code any.)

**Comment by NANASHI0X74** [comment]
So I guess that means you will add the project-level line length configuration option then, right?

**Comment by JakeSays** [comment]
Given that personal expression is an anti-goal of the dart project I do not see why this option is even available.

I was thinking of switching from vs code to intellij for a dart project of mine. I open the code, start typing, press enter, and *BAM* my existing code is re-formatted because I violated the style rules of the almighty dart gods.

**Comment by bsutton** [comment]
@munificent 
> Right now, it's not clear that that's the most important thing to spend time on in dart_style.

If there are resources available to work on dart_style, then I would argue this is the most important thing.

I can't think of any other style issue that annoys me more or that I encounter on an almost daily basis.

I won't start back on the whole 'why did we go 80 to begin with', but adding this as a setting to pubspec.yaml would seem to be a way to put this argument to bed once and for all.

**Comment by munificent** [comment]
> If there are resources available to work on dart_style, then I would argue this is the most important thing.

I think the priorities are and should be:

1. Critical bugs that cause crashes or break the user's code. (Fortunately, I don't know of any of these right now.)
2. Support for formatting new language features. Users effectively can't use a new feature if they can't format it.
3. Working towards a unified style for argument lists between the original and Flutter's style so that users don't have to remember to add and remove trailing commas all the time.
4. Everything else.

**Comment by NANASHI0X74** [comment]
Ok, that wasn't clear to me. So you're accepting PRs then? To me it sounded
a bit like you also wanted to avoid adding the feature because of effort
needed to maintain it in the future

**Comment by natebosch** [comment]
I can see the argument that if we aren't fully supporting configurable line length as a feature, it doesn't make sense to advertise it in the help. I think we should hide the option.

@NANASHI0X74 - typically PRs can be accepted. In this case I don't think we've seen a design approach that we'd want to run with. This type of configuration isn't what the pubspec is intended for (despite flutter putting some extra stuff in there).

**Comment by lukepighetti** [comment]
> This type of configuration isn't what the pubspec is intended for (despite flutter putting some extra stuff in there).

Where would you imagine is the right place for this sort of thing?

**Comment by natebosch** [comment]
> Where would you imagine is the right place for this sort of thing?

I'm not sure. That's part of the reason we don't have an official solution. Configurability is not a goal of this project, so we haven't put effort into a design to support configurability.

**Comment by lukepighetti** [comment]
At the risk of being presumptuous, I think it's worth putting your heads together and making a decision so we can contribute with confidence.

**Comment by JakeSays** [comment]
The fact that configurability is a non-goal is absurd.

**Comment by matthewlloyd** [comment]
If I may chime in:

* Many dislike 80-column limits, especially for nest-heavy use cases like Flutter.
* Therefore, it is likely many developers are currently using `--line-length`.
* A likely consequence of removing `--line-length` is that many developers would stop using `dart format`, and either use no formatting tool at all, or switch to something more configurable.

This may create even more style fragmentation within the community over time compared to merely allowing it to be configured. On the other hand, making it easier to configure in the language's standard formatting tool would likely increase adoption of the tool and thereby improve code quality.

The ability to customize line length, and configure it at the project level, appears to be something of an industry standard amongst formatting tools across many other popular languages. For example:

* In Rust, the `rustfmt` tool allows `max_width` to be configured via `rustfmt.toml` at the project level: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#max_width
* In Python, the very popular `black` tool allows `--line-length` to be configured via `pyproject.toml` at the project level: https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
* In Javascript, the `prettier` tool allows `--print-width` to be configured at the project level in a multitude of ways: https://prettier.io/docs/en/configuration.html

**Comment by NANASHI0X74** [comment]
It appears to me like this proposal has effectively been rejected- removing --line-length is out of the question.

The status quo and my own position was nicely summarized by @lukepighetti:

> I personally think we should either get rid of the ability to configure line length altogether (as you suggest) or get the green light to implement a pubspec.yaml line length setting. What's not going to work for me is leaving this in the middle (its current state) where the only thing it provides is pain.

We should move `dart format` out of the netherland of being configurable but not being intended to be configurable.
I personally think the most reasonable place for this configuration would be the pubspec.yml, but this discussion should be continued in #918
