### ISSUE TITLE
Inconsistency with wrapping adjacent strings

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart_style#1118]
I'm not sure where the bug is so I'm not sure how to title this issue. Take this input:

```dart
@Deprecated('loooooooooooooooooooooooong text string' 'loooooooooooooooooooooooong text string')
void f(
  @Deprecated('loooooooooooooooooooooooong text string' 'loooooooooooooooooooooooong text string')
      x,
) {
  'loooooooooooooooooooooooong text string' 'loooooooooooooooooooooooong text string';
}
/*34567 10   15   20   25   30   35   40   45   50   55   60   65   70   75   80*/
```

The formatter rewrites this as:

```dart
@Deprecated('loooooooooooooooooooooooong text string'
    'loooooooooooooooooooooooong text string')
void f(
  @Deprecated('loooooooooooooooooooooooong text string' 'loooooooooooooooooooooooong text string')
      x,
) {
  'loooooooooooooooooooooooong text string'
      'loooooooooooooooooooooooong text string';
}
/*34567 10   15   20   25   30   35   40   45   50   55   60   65   70   75   80*/
```

The 1st and 3rd pairs of adjacent strings are wrapped. But the middle one, a string in an annotation on a funtion parameter, is not wrapped. 🤔 

The only open bug I could find which looks similar is #987

**Comment by munificent** [comment]
Yeah, I think this is likely a different bug. I suspect that this has to do with a very obscure corner of the formatter that would be hard to describe. Thanks for reporting it. :)

**Comment by munificent** [comment]
I honestly don't know what the old formatter was doing, but the simpler argument list splitting style in the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) yields:

```dart
@Deprecated(
  'loooooooooooooooooooooooong text string'
  'loooooooooooooooooooooooong text string',
)
void f(
  @Deprecated(
    'loooooooooooooooooooooooong text string'
    'loooooooooooooooooooooooong text string',
  )
  x,
) {
  'loooooooooooooooooooooooong text string'
      'loooooooooooooooooooooooong text string';
}
```

Looks pretty clear to me.
