### ISSUE TITLE
split ternary expressions if a new-line is needed anywhere

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_style#112]
Example this code (at +4 indentation):
```dart
    var initializers = something == null
        ? {}
        : new Map.fromIterable(
            something.field.where((i) => i is SomeClassGoesHere),
            key: (i) => i.someField.name);
```

is formatted as:
```dart
    var initializers = something == null ? {} : new Map.fromIterable(
        something.field.where((i) => i is SomeClassGoesHere),
        key: (i) => i.someField.name);
```

**Comment by jacob314** [comment]
I also hit this here:
-    var cg = outputDart ?
-        new DartGenerator(
+    var cg = outputDart ? new DartGenerator(
             outputDir, uri, results.libraries, results.rules, formatOutput) :
         new JSGenerator(outputDir, uri, results.libraries, results.rules);
