### ISSUE TITLE
Allow tab space options to be configured

### ISSUE THREAD

**Issue by tekert** [dart-lang/dart_style#1127]
Please?

**Comment by munificent** [comment]
I do appreciate you asking nicely (not everyone does), but non-configurability is [a deliberate design choice](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it) and an intended part of its behavior. dart_style is designed to be a "commons-oriented" formatter and not an "individual-oriented" one. Its goal is to improve the productivity of the entire Dart ecosystem as a whole by making the world's Dart code more consistent so we can read and contribute to each other's code more easily. It does that at the expense of making the formatter less tailored to any individual user's personal style preferences.
