### ISSUE TITLE
[Records] dart_style support

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/dart_style#1128]

**Comment by jr1221** [comment]
Is there any way to make the formatter selectively ignore lines with records usage instead of the whole file while this is still being worked on?

**Comment by munificent** [comment]
No, sorry. The easiest workaround is to just not use the formatter until it has record support.

**Comment by jr1221** [comment]
Ok, thank you!

**Comment by csells** [comment]
oh my goodness; using the Dart 3 alpha is super painful w/o `dart format` support. please type faster! : )

**Comment by munificent** [comment]
This is now done and rolled into the bleeding edge Dart SDK.
