### ISSUE TITLE
Wrong enum formatting breaks the code

### ISSUE THREAD

**Issue by petroniuchacz** [dart-lang/dart_style#1131]
I'm using enhanced enums and the code reformatting breaks the code.

> Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (6 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
>
> Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1889], locale pl-PL)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

Before reformatting:
```
enum InstrumentType {
share("instrumentTypeNames.share", 'A'),
bond("instrumentTypeNames.bond",'O'),
future("instrumentTypeNames.future",'F'),
option("instrumentTypeNames.option","H"),
indexx("instrumentTypeNames.indexx",'I'),
newEmission("instrumentTypeNames.newEmission",'N'),
claimRight("instrumentTypeNames.claimRight",'P'),
tBill("instrumentTypeNames.tBill",'T'),
indexx2("instrumentTypeNames.indexx",'X'),
ipo("instrumentTypeNames.ipo",'E'),
rightForStock("instrumentTypeNames.rightForStock",'D'),
rightForStock2("instrumentTypeNames.rightForStock",'R'),
warrant("instrumentTypeNames.warrant",'W'),
certificate("instrumentTypeNames.certificate",'C');

final String translationCode;
final String letter;

const InstrumentType(this.translationCode,this.letter,);

  String get toJson => letter;
}
```

After reformatting:

```
enum InstrumentType {
  share
(
"
instrumentTypeNames.share
"
,
'
A
'
)
,
bond
("instrumentTypeNames.bond
"
,
'
O
'
)
,
future
("instrumentTypeNames.future
"
,
'
F
'
)
,
option
("instrumentTypeNames.option
"
,
"
H
"
)
,
indexx
("instrumentTypeNames.indexx
"
,
'
I
'
)
,
newEmission
("instrumentTypeNames.newEmission
"
,
'
N
'
)
,
claimRight
("instrumentTypeNames.claimRight
"
,
'
P
'
)
,
tBill
("instrumentTypeNames.tBill
"
,
'
T
'
)
,
indexx2
("instrumentTypeNames.indexx
"
,
'
X
'
)
,
ipo
("instrumentTypeNames.ipo
"
,
'
E
'
)
,
rightForStock
("instrumentTypeNames.rightForStock
"
,
'
D
'
)
,
rightForStock2
("instrumentTypeNames.rightForStock
"
,
'
R
'
)
,
warrant
("instrumentTypeNames.warrant
"
,
'
W
'
)
,
certificate
("instrumentTypeNames.certificate
"
,
'
C
'
);

final String translationCode;
final String letter;

const InstrumentType(this
.
translationCode,this
.
letter,);

String get toJson => letter;}
```

**Comment by srawlins** [comment]
I cannot reproduce this at [DartPad](https://dartpad.dev/?). :( How are you formatting your code? An IDE or something at the command line or...

**Comment by munificent** [comment]
This output doesn't look like anything dart format is capable of reproducing. Can you describe how you ran the formatter?

**Comment by petroniuchacz** [comment]
I'm using autoformatting in Android Studio: menu bar > Code > Reformat Code.
I run dart format from command line and it look okay, seems like an issue with the IDE.

**Comment by EhabSalah** [comment]
Happens with me on Intellij 🤷🏻‍♂️

**Comment by munificent** [comment]
Can you describe how you invoke the formatter in IntelliJ?
