### ISSUE TITLE
Seemingly inconsistent formatting of adjacent strings

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/dart_style#1143]
Create a file containing the following text:
```
var s1 = <String>[
  'a'
  'b' + 'c',
  'd' + 'e'
  'f',
];
var s2 = <String>[
  'a' 'b' + 'c',
  'd' + 'e' 'f',
];
```
and run the formatter on the file (I ran it in the IDE).

Despite the fact that the two pieces of code are identical modulo whitespace they are formatted very differently. I don't know whether this is intentional, but it does seem to be unfortunate.

**Comment by munificent** [comment]
Oof, yeah, that looks totally busted:

```dart
var s1 = <String>[
  'a'
          'b' +
      'c',
  'd' +
      'e'
          'f',
];
var s2 = <String>[
  'a' 'b' + 'c',
  'd' + 'e' 'f',
];
```

```

**Comment by munificent** [comment]
I ran the example through the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) and it produces:

```dart
var s1 = <String>[
  'a'
          'b' +
      'c',
  'd' +
      'e'
          'f',
];
var s2 = <String>[
  'a'
          'b' +
      'c',
  'd' +
      'e'
          'f',
];
```

The indentation is a little silly, but that's to be expected when combining very short adjacent strings and binary operators. Binary operators have a rule that they always split if their operands do, and in the new style adjacent strings always split.

The important bit is that the formatting is now consistent between the two variables, so it's doing what I expect.
