### ISSUE TITLE
dart_format blank lines question

### ISSUE THREAD

**Issue by FKSuperCoder** [dart-lang/dart_style#1146]
![ecc999cd6852f03eb096aa3ec4ee4ce](https://user-images.githubusercontent.com/102714505/194749915-70863b04-9325-4e95-a257-6e9c707ac663.jpg)
![d87df55ba87b5b76514899968b0400b](https://user-images.githubusercontent.com/102714505/194749920-f3ffc701-ed92-4b3c-92af-f5807714d078.jpg)

图上所示已经可以解释我想要询问的问题了，希望dart_format能够支持设置代码之间的空行数

**Comment by munificent** [comment]
Dart format does not support precise style configuration [by design](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it). The goal is to make everyone's code more consistent, across the entire ecosystem.
