### ISSUE TITLE
Nested list operations wrongfully raises require_trailing_commas

### ISSUE THREAD

**Issue by TheCarpetMerchant** [dart-lang/dart_style#1155]
See the [gist](https://gist.github.com/TheCarpetMerchant/4cfa30dc19d22c7a225666f2214b11e7).
require_trailing_commas is raised for each end of line after `total`.

**Comment by srawlins** [comment]
Is this an issue meant for the linter? at https://github.com/dart-lang/linter?

**Comment by TheCarpetMerchant** [comment]
My bad, thanks !
