### ISSUE TITLE
File-level page width configuration

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart_style#1157]
This is a feature request to support the ability to configure the formatting line length from within the target file.

The use case here is that I have a project that's generating very large dart source files; they're generated from wasm files and replicate the operations specified in those files. Roughly, each generated source line corresponds to a wasm instruction. This works well (is readable) except in cases where there's significant nested control flow. In those cases, the indent pushes the contents past the 80-char boundary, and the generated operations start re-flowing into new lines (generally not doing good things for the readability).

To address this I'm experimenting with formatting the files - as the last step of codegen - with a longer line length; ~100 - ~120 chars. That generally works even for the most nested files. However, there are two issues:

- if somebody ever goes into that file and hits save in an editor, the file will be re-formatted using a different line length
- if people use `dart format --output=none --set-exit-if-changed` as part of a CI, it'll fail on these files

The feature request is for a way to configure the line length that a file should be formatted at from within the file itself. So, something like:

```dart
// Generated from foo/bar/...
// @format.length=120

...

```

**Comment by devoncarew** [comment]
Some configuration prior art are the analyzer ignore_for_file directives:

```
// ignore_for_file: unused_local_variable
```

and the dart language directive:

```
// @dart = 1.12
```

**Comment by munificent** [comment]
Phew. This is a thing we *could* do. But given how incredibly heated discussions of line length get, I worry that if we do this, *everyone* will start configuring the line lengths of all of their files. And then when you're bouncing between Dart files in different packages, it will get much harder to decide how to configure the window size in your IDE.

**Comment by TimWhiting** [comment]
Isn't being able to make sense of code more important than having to deal with resizing windows?

Sure, it'd be pretty impossible to make sure every potential piece of code is formatted optimally for readability. So dart format has to do a best effort, which for most cases is wonderful. It is subjective whether 80 vs 100 vs 120 character lines for a particular file is most readable and people will have their own opinions. However, like @devoncarew, I've found that especially for generated files 80 characters is just too little. I know some people have similar feelings about files with lots of flutter widgets with their build methods with lots of nested widgets.

**Comment by dnfield** [comment]
I would personally prefer to see https://github.com/dart-lang/dart_style/issues/918 implemented, which I think would solve this (just put your generated files in a package that configure the line length for all of them to 120).

**Comment by munificent** [comment]
This is working now for files that are formatted using the new tall style. Add:

```dart
// dart format width=123
```

Before any code in the file and the file will be formatted with that given page width.
