### ISSUE TITLE
code comments, are personal to the dev, allow ignoring them from `dart format`, maybe through a lint

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/dart_style#1160]
Hello,

# Example 1

#### Before
```
/**
    This is a clean doc comment
        This is a part of the sbove statement

    But This is a separate point
*/
```

#### After (`dart format`)
```
/**
  This is a clean doc comment
  This is a part of the sbove statement
  But This is a separate point
*/
```

# Example 2

Rarely used by me, but noticed this,

#### Before
```
    var hlo = "hello"; /// greet text
    var av = 32;
```

#### After
```
    var hlo = "hello"; 

    /// greet text
    var av = 32;
```

This just-above example, just blasts the use of single-line doc comments, other than the dart's ugly usage (which use `///` where `/** */` should be used),

This is actually a **sense vs non-sense** issue, im always thankful to the dart team, but we not in china, that the system force, everything on everyone

peace,
thanks

**Comment by srawlins** [comment]
@gintominto5329 can you say what version of dart you are using? I cannot reproduce your first issue:

```none
$ cat << EOF > x.dart
> /**
>     This is a clean doc comment
>         This is part of the sbove statement
>
>     But this is a separate point
> */
> EOF
srawlins-macbookpro2:sdk srawlins$ dart format --output show x.dart
/**
    This is a clean doc comment
        This is part of the sbove statement

    But this is a separate point
*/
Formatted 1 file (0 changed) in 0.11 seconds.
srawlins-macbookpro2:sdk srawlins$ dart --version
Dart SDK version: 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "macos_x64"
```

**Comment by gintominto5329** [comment]
#### `dart --version`
```
Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "linux_x64"
```

#### `~/bin/flutter/bin/flutter --version`
```
Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 52b3dc25f6 (2 months ago) • 2022-11-09 12:09:26 +0800
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0
```

#### Intellij's About
```
IntelliJ IDEA 2022.3.1 (Community Edition)
Build #IC-223.8214.52, built on December 23, 2022
Runtime version: 17.0.5+1 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Linux 6.1.1-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 2
Non-Bundled Plugins:
    Dart (223.8214.16)
    com.markskelton.one-dark-theme (5.7.2)
    io.flutter (71.2.6)

Kotlin: 223-1.7.21-release-272-IJ8214.52
Current Desktop: XFCE
```

With Intellij-IDE's code formatting, which mentions "**Code is formatted using the dart format tool included with the Dart SDK. See FAQ.**", BOTH the cases are producible, re-confirm-ed just now,

With `dart format`, `///` case is producible, but NOT the case of `/** */`, also confirmed, just now



thanks

**Comment by srawlins** [comment]
OK, you'll have to file a bug with IntelliJ for the `/** */` case. Thanks for checking.

**Comment by gintominto5329** [comment]
May i get a confirmation, that this working in vscode, or not, 
Because, im really fed-up with intellij,

thanks

**Comment by gintominto5329** [comment]
> OK, you'll have to file a bug with IntelliJ for the `/** */` case. Thanks for checking.

Also, may i get some clarification regarding "Code is formatted using the dart format tool included with the Dart SDK. See FAQ." statement, made by intellij,

thanks again

**Comment by gintominto5329** [comment]
I opened an [issue](https://github.com/microsoft/vscode/issues/171696) at github/vscode,

Im customizing it currently,

whenever the issue gets resolved, the Intellij would be thrown out, of my computer

**Comment by gintominto5329** [comment]
You may please close this issue, if you do not provide support for "Code is formatted using the dart format tool included with the Dart SDK. See FAQ.",

**Comment by munificent** [comment]
It's not possible for the formatter to produce your example 1 output: it never touches the contents of comments except for when running `--fix`, but the one fix that touches comments would also replace them with `///`.

Example 2 is working as intended. Doc comments are always placed on their own line preceding the declaration they apply to. If you write:

```dart
    var hlo = "hello"; /// greet text
```

The dartdoc isn't going to know that doc comment is associated with `hlo`. It will think it applies to the next line. The formatter makes that clearer.
