### ISSUE TITLE
Lists / arrays / matrices are not formatted as one would expect semantically

### ISSUE THREAD

**Issue by satvikpendem** [dart-lang/dart_style#1163]
I was playing around with `ColorFilter.matrix` in Flutter and was using some of their examples such as

```dart
const ColorFilter invert = ColorFilter.matrix(<double>[
  -1,  0,  0, 0, 255,
   0, -1,  0, 0, 255,
   0,  0, -1, 0, 255,
   0,  0,  0, 1,  0,
]);
```

However, upon formatting the file, the resultant code was

```dart
const ColorFilter identity = ColorFilter.matrix(<double>[
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
]);
```

where I'd have expected the formatter to correspond with the semantic meaning of the matrix.

I also tried with decimals

```dart
const ColorFilter sepia = ColorFilter.matrix(<double>[
  0.393, 0.769, 0.189, 0, 0,
  0.349, 0.686, 0.168, 0, 0,
  0.272, 0.534, 0.131, 0, 0,
  0,     0,     0,     1, 0,
]);
```

and got 

```dart
const ColorFilter sepia = ColorFilter.matrix(<double>[
  0.393,
  0.769,
  0.189,
  0,
  0,
  0.349,
  0.686,
  0.168,
  0,
  0,
  0.272,
  0.534,
  0.131,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
]);
```

Maybe there should be a way to tell the formatter the dimensions of the matrix so that it takes into account the correct formatting.

**Comment by munificent** [comment]
The formatter doesn't support aligning columns within a collection, but it does let you control the line breaking in them. See [here](https://github.com/dart-lang/dart_style/wiki/FAQ#why-does-the-formatter-mess-up-my-collection-literals).

**Comment by satvikpendem** [comment]
Great, thanks!
