### ISSUE TITLE
Weird indentation in chained lambda functions

### ISSUE THREAD

**Issue by a9udn9u** [dart-lang/dart_style#1175]
Actual:
```dart
    return maps
        .where((map) => map != null)
        .expand((map) => map!.entries)
        .fold({}, (merged, entry) {
      merged[kp(entry.key)] = vp(entry.value);  // <- Should indent more
      return merged;                            // <- Should indent more
    });                                         // <- Should indent more
```
Expected:
```dart
    return maps
        .where((map) => map != null)
        .expand((map) => map!.entries)
        .fold({}, (merged, entry) {
          merged[kp(entry.key)] = vp(entry.value);
          return merged;
        });
```

Similarly in function parameter list:
```dart
  static List<V> spaceBetween<V>(
    List<V> collection,
    V spacer, {
    bool? bothEnds = false,  // <- Should indent more
    bool? leftEnd = false,   // <- Should indent more
    bool? rightEnd = false,  // <- Should indent more
  }) {                       // <- Should indent more
```

**Comment by munificent** [comment]
> ```dart
>     return maps
>         .where((map) => map != null)
>         .expand((map) => map!.entries)
>         .fold({}, (merged, entry) {
>       merged[kp(entry.key)] = vp(entry.value);  // <- Should indent more
>       return merged;                            // <- Should indent more
>     });                                         // <- Should indent more
> ```

This formatting is a little weird looking here but is deliberate. It makes more sense when the method chain doesn't itself need to split, as in:

```dart
    return maps.where((map) => map != null) {
      merged[kp(entry.key)] = vp(entry.value);
      return merged;                          
    });                                       
```

Here, the block-like formatting works well and most users seem to like it. It also, I think, works well in code like:

```dart
    return maps.where((map) {
      return map != null;
    }).expand((map) {
      return map!.entries;
    }).fold({}, (merged, entry) {
      merged[kp(entry.key)] = vp(entry.value);
      return merged;                          
    });                                       
```

The formatter does that block-like formatting consistently even if the preceding method chain splits. We've considered whether we should change the closure's indentation based on whether the preceding method chain splits, but it's not clear if that's what users want. It's a big enough change that it would have to go through the [change process](https://github.com/dart-lang/dart_style/wiki/Change-process).

```dart
  static List<V> spaceBetween<V>(
    List<V> collection,
    V spacer, {
    bool? bothEnds = false, 
    bool? leftEnd = false,  
    bool? rightEnd = false, 
  }) {                      
```

This is the deliberate style. It may not be to everyone's taste, but as far as I can tell, most users are OK with it.

**Comment by zedefi** [comment]
Same issue here. A code formatted this way is so hard to read. Please at least provide some way how to customize this, because it is really distracting. Especially the async code with streams that is so difficult to read like this :(

**Comment by munificent** [comment]
I ran these examples through the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) and it produces:

```dart
    return maps
        .where((map) => map != null)
        .expand((map) => map!.entries)
        .fold({}, (merged, entry) {
          merged[kp(entry.key)] = vp(entry.value);
          return merged;
        });
```

So that's exactly as expected.

And:

```dart
static List<V> spaceBetween<V>(
  List<V> collection,
  V spacer, {
  bool? bothEnds = false,
  bool? leftEnd = false,
  bool? rightEnd = false,
}) {
```

As I mentioned in my previous comment, that's the expected style. So I think this is working well in the new formatter.
