### ISSUE TITLE
How to format a String with Records enabled?

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/dart_style#1193]
I am trying to format a source code that has the `Records` experiment, however, even thought the builder is running with `enable-experiment=records`, the formatter throws that it needs the `Records` flag on.

**Comment by jakemac53** [comment]
@munificent is there a version of dart_style published that supports records/patterns/class modifiers yet?

**Comment by jodinathan** [comment]
it seems the version in the repo is with stuff enabled: https://github.com/dart-lang/dart_style/blob/a3f1b041f3c5045d1fee7f1129075d0ad6a4a96e/lib/src/dart_formatter.dart#L212

I will try that

**Comment by jodinathan** [comment]
yeah, it worked by overriding the dep to use the dev version

**Comment by munificent** [comment]
The version rolled into the SDK supports it, but I haven't published it yet. I'll do that soon. (I wanted to make sure it rolled into the SDK without any problems.)
