### ISSUE TITLE
dartfmt removes "?" in "()?" typed field

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/dart_style#1224]
While adding records support to built_value I thought I'd check the base case, and it doesn't quite work as dartfmt eats the `?` in the generated output.

```
> cat foo.dart
class A {
  ()? x;
}
```

```
dartfmt foo.dart
Hit a bug in the formatter when formatting foo.dart.
The formatter produced unexpected output. Input was:
class A {
  ()? x;
}

Which formatted to:
class A {
  () x;
}
```

**Comment by munificent** [comment]
Oof, that's bad. I'll take a look.

**Comment by tekert** [comment]
Seem like a `token(node.question);` is missing when `RecordTypeAnnotation` fields are empty.
https://github.com/dart-lang/dart_style/blob/a36eb2030765592701ec0f54b4085c0932c39991/lib/src/source_visitor.dart#L2508
