### ISSUE TITLE
Dart Line length can not be saved / resets

### ISSUE THREAD

**Issue by DeepSeaPlain** [dart-lang/dart_style#1227]
![image](https://github.com/dart-lang/dart_style/assets/127975868/84aae3a5-aa31-4145-bc7b-c5951f923898)

I open the IntelliJ settings.
-> Editor -> Code Style -> Dart    (see screenshot)

I change the line length from 80 to 150 and I click on apply but nothing happens. 

I managed to kinda work around that problem by doing this:
I open the IntelliJ settings.
-> Editor -> Code Style -> Dart    (see screenshot)
I change the line length to 150 
i click on any other tab in the settings menu
I go back to -> Editor -> Code Style -> Dart
now the line length changes when I click apply 
BUT it resets every time i close IntelliJ
(super annoying)

**Comment by munificent** [comment]
This looks like an issue with the Dart IntelliJ plug-in. @jwren, do you know where this issue should go?
