### ISSUE TITLE
bizarre parameter wrapping when followed by block comment

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart_style#1232]
I don't generally check in code like this, but was commenting out a method's implementation and writing in a new one, and got some weird formatting. Here's a simple repro that works on DartPad:

```dart
int foo(List<int> list) /*
1234567     14     21     28     35     42     49
  */
    => 7;
```

formats to:

```dart
int foo(
        List<int>
            list) /*
1234567     14     21     28     35     42     49
  */
    =>
    7;
```

I think the `=>\n7` is covered in other bugs... but the newline before `List<int>` and the newline before `list` each seem weird. Or at least one of them is. Note that if you remove even one character from the comment text, both of those newlines disappear.

**Comment by munificent** [comment]
Yeah, that's pretty wonky.

**Comment by munificent** [comment]
I have no idea what the old formatter is thinking, but the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) formatter produces:

```dart
int foo(List<int> list) /*
1234567     14     21     28     35     42     49
  */ => 7;
```

That looks OK to me.
