### ISSUE TITLE
Inline classes

### ISSUE THREAD

**Issue by scheglov** [dart-lang/dart_style#1241]
I'm reworking how inline classes are parsed in https://dart-review.googlesource.com/c/sdk/+/311933
There are tests that started failing because `dart_style` does not handle new nodes.
It feels a safe decision for `dart_style`, but it makes taking some obligations, like fixing these crashes.

**Comment by munificent** [comment]
Yeah, sorry about that. I see that @oprypin sent a change to just remove that test, which is fine. I'll also remove the code that uses the `inlineKeyword` getter on the analyzer AST so you can remove that.
