### ISSUE TITLE
Example from dart_style documentation does not work

### ISSUE THREAD

**Issue by pbrisbin** [dart-lang/dart_style#1243]
Hi there! I'm the author of [Restyled](https://restyled.io/), and I'm trying to make a dart-format restyler. As such, I'd like to verify it works by formatting some examples with it; but I found that the primary example in the dart_style docs (linked to from the dart-format docs) doesn't work:

On https://pub.dev/packages/dart_style, it shows:

![](https://files.pbrisbin.com/screenshots/screenshot.133389.png)

But I cannot make this work:

```console
% docker run --rm -it dart bash 
root@58a7438febdd:~# dart --version
Dart SDK version: 3.0.5 (stable) (Mon Jun 12 18:31:49 2023 +0000) on "linux_x64"
root@58a7438febdd:~# cat > example.dart <<'EOM'
> // BEFORE formatting
if (tag=='style'||tag=='script'&&(type==null||type == TYPE_JS
      ||type==TYPE_DART)||
  tag=='link'&&(rel=='stylesheet'||rel=='import')) {}
> EOM
root@58a7438febdd:~# dart format example.dart
Could not format because the source could not be parsed:

line 2, column 1 of example.dart: 'if' can't be used as an identifier because it's a keyword.
  ╷
2 │ if (tag=='style'||tag=='script'&&(type==null||type == TYPE_JS
  │ ^^
  ╵
line 2, column 8 of example.dart: Expected to find ')'.
  ╷
2 │ if (tag=='style'||tag=='script'&&(type==null||type == TYPE_JS
  │        ^^
  ╵
Formatted no files in 0.10 seconds.
root@58a7438febdd:~#
```

What am I missing?

**Comment by srawlins** [comment]
The examples are at the statement level, so you'll have to write them in a position in dart code where statements are legal. For example, inside a function declaration.

**Comment by pbrisbin** [comment]
Awesome, thank you!

In case it's useful, I get a slightly more aligned output when I got the test working:

```dart
          if (tag == 'style' ||
              tag == 'script' &&
                  (type == null || type == TYPE_JS || type == TYPE_DART) ||
              tag == 'link' && (rel == 'stylesheet' || rel == 'import')) {}
```
