### ISSUE TITLE
Current experiment logic prevents us from being able to expire or remove experiment flags sanely

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart_style#1245]
I was recently trying to retire the dart 3.0 experiment flags (https://dart-review.googlesource.com/c/sdk/+/316460) but this ended up breaking most of our internal codebase.

The current way we deal with language features is to just enable the experiment as soon as formatting for it is supported, and we always set the `sdkLanguageVersion` to 2.19.0.  This kind of works, until we go to retire or delete an experiment flag.

As an example my first fix for the current situation was to change the logic to parse with the current language version and _no_ experiments, and then after that try to parse as 2.19.0. That works  except that we have old versions of the formatter out there, and they will no longer work for any Dart 3.0 code.

There is no analyzer api for parsing with the current version plus some experiments that I can find (cc @scheglov I could be missing something) - if we had that we could add a third fallback that enables inline classes with the current language version (that feature has no experimental release version yet, but maybe we should require it to before it gets formatter support?).

We can somewhat alleviate the situation with breaking changes in analyzer any time an experiment is either expired _or_ deleted, but that is very arduous.

Longer term, simply forcing users to explicitly enable features is more maintainable I think. I understand that places a burden on things that use the formatter as a library, but not many things actually do that.

**Comment by leafpetersen** [comment]
Publishing code that relies on experiment flags is really something we should avoid.  Or else we should really re-think our experiment flag story.

**Comment by munificent** [comment]
> Longer term, simply forcing users to explicitly enable features is more maintainable I think. I understand that places a burden on things that use the formatter as a library, but not many things actually do that.

SGTM.

I will have to pass those flags in the formatter's *tests* in order to land support for formatting a new language feature before the experiment ships. And then removing those flags will break the tests.

But that won't break any users. And, in particular, it means that new versions of analyzer that don't allow the flag won't break people using dart_style as a library.
