### ISSUE TITLE
Skip ".hidden" directories

### ISSUE THREAD

**Issue by Fox32** [dart-lang/dart_style#125]
When I run ```dartformat``` on my package as ```dartformat -w .``` it skips links like the ```packages``` folder which nice.
But it includes the ```.pub``` folder, I don't think that that code should be touched. This can be solved either by skipping the ```.pub``` folder or all folders with a leading dot.

**Comment by kaendfinger** [comment]
.pub contains snapshots of scripts in other packages. It should skip them. Does it actually modify anything?
