### ISSUE TITLE
Problem with multi line strings (wrong line endings?)

### ISSUE THREAD

**Issue by Fox32** [dart-lang/dart_style#126]
I start with the following code:
```
void main() {
  print('''
Hello World

Another line....
And another...
  ''');
}
```
The code misses a line ending at the end of the file, everything else seems to be fine.
Executing ```dartformat test.dart``` results in the following output:
```
void main() {
  print('''
Hello World

Another line....
And another...
  ''');
}

```
The output of the console has the right line break at the end of the file.
But in case I use ```dartformat -w test.dart``` to overwrite the input file it writes the following output to the file:
```
void main() {
  print('''

Hello World



Another line....

And another...

  ''');
}

```
I'm using Windows and the input file has Windows style line endings. Multiline strings are the only place were I noticed problems with line endings.

PS: I tried to add the version of dartformat that I'm using (git rev 6a0abc7c21f3b3a1812977ee12ea81cab4cfca95) but there is no way to print that. A ```dartformat --version``` would be nice.
PPS: ```pub global list``` does the trick: 0.1.1-dev

**Comment by munificent** [comment]
Ah, thanks for the bug. I'm probably not stripping out the `\r` when splitting multiline strings. Should be an easy fix.

**Comment by Fox32** [comment]
Thanks!
