### ISSUE TITLE
new lines for member methods

### ISSUE THREAD

**Issue by BentEngbers** [dart-lang/dart_style#1261]
The following code is correctly formatted according to the [dartpad](https://dartpad.dev/).
```dart
class A {
  A.b()
      : assert(true),
        assert(true);
  a() =>
      "a very long string or expression that creates a line longer than 80 characters";
  b() => 7;
}
```
A lack of spacing between the class members makes the code, in my opinion, less readable. 
I would prefer a new line between these methods:
```dart
class A {
  A.b()
      : assert(true),
        assert(true);

  a() =>
      "a very long string or expression that creates a line longer than 80 characters";

  b() => 7;
}
```
Possible duplicate of #930, although i cannot add a function body to these methods.
Perhaps there is another workaround?

**Comment by munificent** [comment]
> I would prefer a new line between these methods

If you place blank lines between the members, it will keep the those blanks there when you format.
