### ISSUE TITLE
Formatting doesn't sort imports

### ISSUE THREAD

**Issue by chrisnorman7** [dart-lang/dart_style#1266]
Hi,
I have the following code:

```dart
import 'package:dart_style/dart_style.dart';

const code = '''
 import 'package:html/html.dart';
import 'dart:io';
''';

void main() {
  final formatter = DartFormatter(fixes: StyleFix.all);
  print(formatter.format(code));
}
```

When I run it, the imports don't get sorted.

Is this intentional? How can I sort imports programatically in dart?

Thank you very much for all your hard work.

**Comment by munificent** [comment]
> When I run it, the imports don't get sorted.
> 
> Is this intentional?

Yes. The formatter only touches whitespace characters. It doesn't modify or even reorder any non-whitespace characters in your code.

> How can I sort imports programatically in dart?

The [Dart linter](https://pub.dev/packages/lint) which is integrated into most IDEs has a lint rule for sorting imports and a quick fix that will sort them for you. I don't know if there is a programmatic API to be able to easily use it from a library. @pq would know.

> Thank you very much for all your hard work.

You're welcome!

**Comment by chrisnorman7** [comment]
Hi,
That's great, thank you so much for the info.

Take care,

Chris Norman
