### ISSUE TITLE
Don't touch files whose contents don't change

### ISSUE THREAD

**Issue by Janamou** [dart-lang/dart_style#127]
If the file is already formatted according to dart style guide, it is changed next time even there was not any change. 

I then have this for every file when committing:
1 file changed, 0 insertions(+), 0 deletions(-)

**Comment by munificent** [comment]
If you run the formatter once, and then run it again on the output of the first run, you should get the same thing back. Is that not what you're seeing? If so, can you give me some details on which code gets modified?

Or is that the file *contents* are the same, but the modification time is still being touched?

**Comment by Janamou** [comment]
Yes, I understand this. It is the second case.
I am running it with -w parameter to directly update files (for example on lib folder):

```
dartformat -w lib
```

And in that moment ALL files in lib folder are updated even nothing was changed (modification time is updated and then Git thinks that there was a change). 

Btw, great tool. Thanks for it! :-)

**Comment by munificent** [comment]
> Yes, I understand this. It is the second case.

Ah, excellent. That is indeed something the formatter should be smarter about. I'll leave this bug open for that until I get a chance to fix it.

Thanks!
