### ISSUE TITLE
Indent problem?

### ISSUE THREAD

**Issue by Fox32** [dart-lang/dart_style#129]
Not sure if this behavior is intentional:
```
void main() {
  if (false) {
    if (false) {
      if (false) {
        if (false) {
          final dsfsdfsdf = sdfsdfsdf(sdfsdfsdfs.sdfsdfsdfsdfsdfsdfsdfsdfs) || dsfdsfsdfsd > sdfsdfsdfdsfsdfsdfffff && sdfsdfsdff > sdfsdfsdfdsfdsfsdfsdf;
        }
      }
    }
  }
}
```
Is formatted to:
```
void main() {
  if (false) {
    if (false) {
      if (false) {
        if (false) {
          final dsfsdfsdf = sdfsdfsdf(sdfsdfsdfs.sdfsdfsdfsdfsdfsdfsdfsdfs) ||
              dsfdsfsdfsd > sdfsdfsdfdsfsdfsdfffff &&
                  sdfsdfsdff > sdfsdfsdfdsfdsfsdfsdf;
        }
      }
    }
  }
}
````
Shouldn't the line after the AND operator have the same indent?

**Comment by munificent** [comment]
This output is as intended. `&&` has higher precedence than `||`. The second line's indentation level represents an operand to `||`. Since the third line is the right operand to `&&`—a subexpression of the right-hand side of the `||`—it gets a different, deeper indentation level.

**Comment by Fox32** [comment]
Thanks for the clarification =D
