### ISSUE TITLE
Break long strings into multiline Strings

### ISSUE THREAD

**Issue by DrMarcII** [dart-lang/dart_style#131]
It would be nice if the formatter could break a String that extends beyond 80-cols to a multi-line string: e.g.
        "arguments[0].dispatchEvent(new MouseEvent(arguments[1], {'button' : arguments[2]}));"
to:
        "arguments[0].dispatchEvent(new MouseEvent(arguments[1], "
        "{'button' : arguments[2]}));",

Not sure what the algorithm should be for breaking though. Maybe after right-most whitespace that fits in 80 cols (if it exists), otherwise at (or slightly before) 80-cols.

If you can't decide on a standard algorithm for this, then at least providing a warning message if any such lines remain after formatting would be good.

**Comment by munificent** [comment]
This would be useful, I agree, but it's out of scope for the formatter. We've deliberately limited its charter to *only* touching whitespace to keep the scope of the project tractable, and to ensure users can be confident running it automatically on their code.

**Comment by DrMarcII** [comment]
So, any change of outputting warnings if there are lines that can't be fit into the line-length?

**Comment by munificent** [comment]
I don't currently plan to add that formatter. It's pretty easy to write a script that reads a file and tells if a line is longer than 80 columns, so rolling it into the formatter doesn't add much value, I think.
