### ISSUE TITLE
marking a `abstract interface class` as `final` breaks formatting

### ISSUE THREAD

**Issue by lucavenir** [dart-lang/dart_style#1319]
Hi, I hope I'm not opening a duplicate, but I couldn't find any info about the following issue.

In a nutshell, take this example:
```dart
abstract interface class A {
  void m
  ();
}

base class B implements A {
  @override
  void m
  () {

  }
}
```
This correctly gets formatted as:
```dart
abstract interface class A {
  void m();
}

base class B implements A {
  @override
  void m() {}
}
```
But if you want `A` to be `final`:
```dart
abstract final interface class A {
  void m
  ();
}

base class B implements A {
  @override
  void m
  () {

  }
}
```
The formatter **will not apply any change**. As a further note I can see the following logs from vs code's output console:
```log
2023-11-12 21:37:46.441 [error] [Dart-Code.dart-code] provider FAILED
2023-11-12 21:37:46.441 [error] Error: An error occurred while handling textDocument/formatting request
	at handleResponse (/home/venir/.vscode/extensions/dart-code.dart-code-3.76.1/out/dist/extension.js:30088:48)
	at handleMessage (/home/venir/.vscode/extensions/dart-code.dart-code-3.76.1/out/dist/extension.js:29868:13)
	at processMessageQueue (/home/venir/.vscode/extensions/dart-code.dart-code-3.76.1/out/dist/extension.js:29885:17)
	at Immediate.<anonymous> (/home/venir/.vscode/extensions/dart-code.dart-code-3.76.1/out/dist/extension.js:29857:13)
	at process.processImmediate (node:internal/timers:476:21)
```

**Comment by munificent** [comment]
It's a bug. Here's what you get if you format on the command line:

```
Hit a bug in the formatter when formatting /Users/rnystrom/Documents/temp.dart.
The formatter produced unexpected output. Input was:
abstract final interface class A {
  void m
  ();
}

Which formatted to:
abstract interface final class A {
  void m();
}
```

So the formatter is incorrectly outputting the modifiers in the wrong order. And then it's own internal sanity check kicks in so it aborts instead of writing the output.

Thank you for filing this! I'll fix it soon.

**Comment by lrhn** [comment]
It's not just a wrong order, the combination of `interface` and `final` is not allowed in *any* order, the two are mutually exclusive modifiers.

I believe the formatter only formats valid syntax, so there is a reason it's not prepared for this case.
The bug is probably somewhere further up the parsing chain, where this input gets accepted to begin with.

**Comment by lucavenir** [comment]
> the two are mutually exclusive modifiers

Wait, what? This sounds as big news to me. This is how I interpreted the relationship between the two, given the documentation:

```dart
// ab.dart
abstract final interface class A {}

final class B implements A {}  // allowed because it's the same library

// c.dart
final class C implements A {} // error: can't implement A cause it's final AND we're outside its library
```

Furthermore an  `abstract final interface class` is very handy for my use case. I can centralize some utility logic that it is meant to be accessed from `static` methods only. Example:

```dart
import 'package:intl/intl.dart';

abstract final class MyCustomFormatter {
  static String dateFormatter(DateTime date, {String pattern = 'yMd'}) {
    final formatter = DateFormat(pattern);
    return formatter.format(date);
  }
}
```

**Comment by lrhn** [comment]
> Wait, what? This sounds as big news to me.

It's the truth, though.

You can have at most *one* of the modifiers `base`, `interface`, `final` or `sealed` on a class declaration.
You can have `abstract` too, except with `sealed`.

A `mixin` or `mixin class` declaration can have `base` or no modifier, and be `abstract` or not.

That's all the places the new modifiers can be placed at all.


The maning of `final` implies the effect of `interface` (cannot be extended - outside of the current library), as well as the effect of `base` (cannot be implemented - outside of the current library), so there is no need to have both, and the grammar doesn't allow it.

The `sealed` also implies not being able to be implemented or extended (outside of the current library), so you don't get to write any of the other modifiers. (Even if `sealed` differs from `final`/`base` in that it doesn't require subclasses to be `base`, `final` or `sealed`, you'll just have to write that on each of the subclasses if you want it, which are all in the same library anyway.)

Which means that *if* `final interface class` was allowed, it would not differ from `final class` in *any* way, so you definitely don't need it for semantic reasons.

As for having a class to contain only static members,
1. It's [against the style guide](https://dart.dev/effective-dart/design#avoid-defining-a-class-that-contains-only-static-members).
2. If you really want it anyway, you can use something that is even *less* usable than a `final` class:
    ```dart
    typedef NameSpace = Never;
    extension MyCustomFormatter on NameSpace {
      static thisAndThat ...
    }
    ````
    (Not that I would recommend it, but it's as close to a pure namespace as you'll get in Dart today. The class 
    still introduces a *type*, `MyCustomFormatter`.)

**Comment by lucavenir** [comment]
Thank you @lrhn, as enlighting and exahustive as always.
Also, I didn't know about that style guide, so now I immediately feel guilty about that implementation 😄
Finally, thank you for that suggestion, I'll definitively do that!

Okay, so should this issue be migrated to `/language` instead?

**Comment by lrhn** [comment]
Probably to `/sdk`, it's an implementation bug. Will have to check if it shows up in other tools too, or it's unique to `dart format`. (But not today.)

**Comment by lucavenir** [comment]
Okay, I'll wait for your green light before closing and opening this, there.
