### ISSUE TITLE
Lost type arguments on super calls

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/dart_style#1321]
```dart
The formatter produced unexpected output. Input was:
class A {
  A(int foo<T>(int a));
}
class B extends A {
  B.sub1(int super.bar1<T1>(int a1),);
  B.sub2(int super.bar2<T2>(int a2),);
}
main() {}
```

Which formatted to:

```dart
class A {
  A(int foo<T>(int a));
}

class B extends A {
  B.sub1(
    int super.bar1(int a1),
  );
  B.sub2(
    int super.bar2(int a2),
  );
}

main() {}
```

(So formatting throws away the `<T1>` and `<T2>`)

**Comment by munificent** [comment]
Oh, wow. It took me several reads to even figure out what's going on here. So it's a super parameter that is passing a generic function to the superclass and the parameter declaration in the subclass uses the old style function-typed parameter syntax. That is indeed a dark corner of the grammar.
