### ISSUE TITLE
Multiline strings should be weighted more towards alignment

### ISSUE THREAD

**Issue by nex3** [dart-lang/dart_style#133]
Currently this:

``` dart
testCase._error(
    'Callback ${id}called ($actualCalls) after test case '  
    '${testCase.description} has already been marked as '
    '${testCase.result}.$reason');
```

is formatted as so:

``` dart
testCase._error('Callback ${id}called ($actualCalls) after test case '  
    '${testCase.description} has already been marked as '
    '${testCase.result}.$reason');
```

I like the heuristic of putting an argument on the opening line in general, but I think when it's a continued multiline string it's more important that each line be aligned.

**Comment by Hixie** [comment]
In #526, the proposed formatting would make the above example format as follows:
```dart
testCase._error(
  'Callback ${id}called ($actualCalls) after test case '  
  '${testCase.description} has already been marked as '
  '${testCase.result}.$reason'
);
```
...which makes it even clearer where the expression starts and ends.

**Comment by munificent** [comment]
In the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253), this code gets formatted as:

```dart
testCase._error(
  'Callback ${id}called ($actualCalls) after test case '  
  '${testCase.description} has already been marked as '
  '${testCase.result}.$reason',
);
```

All of the strings are aligned, so I think this is done now.
