### ISSUE TITLE
Formatter behavior changes with line comment inside parameter list

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/dart_style#1331]
With an inline comment, the last two parameters here get put on the same line, which shouldn't be the case, since the last parameter has a trailing comma:

```dart
        await _loadProfileView(
          userId: profileView.userId,
          setLikeActionType: LikeActionType.block,
          // Remove star too from any user that is blocked
          setStarAction: false, onUserActionChanged: widget.onUserActionChanged,
        );
```

Removing the comment, the last two parameters get put on separate lines, as expected:

```dart
        await _loadProfileView(
          userId: profileView.userId,
          setLikeActionType: LikeActionType.block,
          setStarAction: false,
          onUserActionChanged: widget.onUserActionChanged,
        );
```

Dart version: 3.3.0-91.0.dev

**Comment by munificent** [comment]
This is working as *intended* but I'm not sure at all if it's working as *desired*. When an argument list has a trailing comma, the formatter currently treats it exactly like a collection literal. Collection literals have some special logic where a comment inside the literal triggers [a rule where it preserves the newlines and allows multiple elements/arguments on the same line](https://github.com/dart-lang/dart_style/wiki/FAQ#why-does-the-formatter-mess-up-my-collection-literals).

That's probably not the most useful behavior for an *argument list*, though. We're working on a rewrite of the formatter (#1253) which will likely revisit this behavior. In the meantime, if you add a newline yourself between the last two arguments, it will preserve it.

**Comment by munificent** [comment]
The [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) formatter doesn't have this bug and produces:

```dart
        await _loadProfileView(
          userId: profileView.userId,
          setLikeActionType: LikeActionType.block,
          // Remove star too from any user that is blocked
          setStarAction: false,
          onUserActionChanged: widget.onUserActionChanged,
        );
```

So I'm going to go ahead and close this.
