### ISSUE TITLE
refactor: introduce "code" option to `FormatCommand`

### ISSUE THREAD

**Issue by alestiago** [dart-lang/dart_style#1333]
## Description

The `FormatCommand` should offer a `--code` argument, as in `FixCommand` to apply fixes to specific lint rules instead of using `--fix-<non-standard-code>` (currently documented as used for non-whitespace changes only).

## Additional context

The `FormatCommand` is [being consumed by `dartdev`](https://github.com/dart-lang/sdk/blob/82ca7ec4902babb3d0818b757b1ea841c3d8fd99/pkg/dartdev/lib/dartdev.dart#L116), a command-line utility for Dart development (part of the Dart SDK).

The `package:dartdev` [exposes a `FixCommand`](https://github.com/dart-lang/sdk/blob/82ca7ec4902babb3d0818b757b1ea841c3d8fd99/pkg/dartdev/lib/dartdev.dart#L115) that accepts a [`code` argument](https://github.com/dart-lang/sdk/blob/82ca7ec4902babb3d0818b757b1ea841c3d8fd99/pkg/dartdev/lib/src/commands/fix.dart#L50). This is very useful, since it allows to explicitly resolve fixes for a specific linter rule.

With `FixCommand` you can explicitly solve for [`directives_ordering`](https://dart.dev/tools/linter-rules/directives_ordering), by doing:

```sh
dart fix --apply --code=directives_ordering # Solves for "directives_ordering"
```

> **Note**: The `directives_ordering` code is already well documented in [Dart Linter Rules](https://dart.dev/tools/linter-rules).

However, the `FormatCommand` presents another solution which brings inconsistency to the overall Developer Experience offered by the command-line utility for Dart development.

```sh
dart format . --code=avoid_single_cascade_in_expression_statements # Could not find an option named "code"
dart format . --fix-single-cascade-statements  
```

> **Note**: there is no documented "single-cascade-statements" rule in the [Dart Linter Rules](https://dart.dev/tools/linter-rules), instead there is ["avoid_single_cascade_in_expression_statements"](https://dart.dev/tools/linter-rules/avoid_single_cascade_in_expression_statements).

**Comment by munificent** [comment]
The `--fix` support in dart format is pretty old, which mostly explains why its names don't agree with the linter. Instead of updating the names in `--fix`, I think the better solution that we're working toward (thanks @keertip!) is to make `dart fix` fast enough for users to use it for all of the things where `dart format --fix` is currently supported and faster. That will enable us to remove `dart format --fix` entirely and have one canonical way to apply code fixes: `dart fix`.

Given that, I think it's unlikely that we'll bother changing the API of `FormatCommand`, but if it's urgent or important, I'm up for discussing it.

**Comment by alestiago** [comment]
Thanks @munificent for the quick reply. I'm happy with the suggested _better solution_. Is there a way I can track the work towards making `dart fix` fast enough?

**Comment by munificent** [comment]
I believe @keertip is working on this, or at least was intending to at some point. I'm not sure if she has any tracking issue for it.

**Comment by munificent** [comment]
I'm not sure of the exact status, but I *believe* that `dart fix` has lightweight mode now. We don't have any intention of putting more effort into `dart format --fix`. It's deprecated and will be removed when we move to the new tall style (#1403). So I'm going to go ahead and close this.
