### ISSUE TITLE
When a ternary is too long to fit in a single line, attempt to fit only the condition in that line

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/dart_style#1342]
Consider a case were a ternary is too long to fit within the 80/120 line length.
Currently, it would try to format as:

```dart
var value = 
   conditon ? a : b;
```

Would it be reasonable to format it over multiple lines instead?

```dart
var value = condition
  ? a
  : b;
```

**Comment by srawlins** [comment]
The conditional expression is not too long to fit into one line, in that example. It fits nicely in the second line.

**Comment by rrousselGit** [comment]
It is too long to fit in the lint it is associated with.

**Comment by rrousselGit** [comment]
That random line-break to fit the code in the next line is something I avoid everywhere it can happen.

For example instead of:

```dart
var value = 
  foo(param);
```

I write:

```dart
final value = foo(
  value,
);
```

But we have no equivalent for ternaries

**Comment by munificent** [comment]
I'm going to close this in favor of #1465 which is newer, but has more context about why the new formatter doesn't support it yet.
