### ISSUE TITLE
Move class "extends"/implements/with to a new line when generics take a lot of space

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/dart_style#1348]
Hello!

Consider the following code I dealt with earlier:

```dart
abstract class StreamNotifierProviderBase<
        NotifierT extends AsyncNotifierBase<T>,
        T> extends ProviderWithNotifier<AsyncValue<T>, NotifierT>
    with FutureModifier<T> {
// ...
}
```

With the way `extends` and generics are mixed up, this is fairly unreadable.
It's very hard with a quick glance to know what this class extends exactly.

I propose formatting such cases like the `with`:

```dart
abstract class StreamNotifierProviderBase<
        NotifierT extends AsyncNotifierBase<T>,
        T>
    extends ProviderWithNotifier<AsyncValue<T>, NotifierT>
    with FutureModifier<T> {
// ...
}
```

**Comment by munificent** [comment]
Yeah, I agree the current formatting is pretty bad. The new in-progress style gives you:

```dart
abstract class StreamNotifierProviderBase<
  NotifierT extends AsyncNotifierBase<T>,
  T
> extends ProviderWithNotifier<AsyncValue<T>, NotifierT>
    with FutureModifier<T> {
  // ...
}
```

Which isn't much better, I think. The rule should probably be that if the class type parameters split, then we force any subsequent clauses to move to their own lines too, like:

```dart
abstract class StreamNotifierProviderBase<
      NotifierT extends AsyncNotifierBase<T>,
      T
    >
    extends ProviderWithNotifier<AsyncValue<T>, NotifierT>
    with FutureModifier<T> {
  // ...
}
```

I don't plan to tweak the formatting in the old style, but I'll leave this issue open to improve how the new style handles this case.

**Comment by munificent** [comment]
I recently (#1511) fixed this in the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) formatter. With that change, you get:

```dart
abstract class StreamNotifierProviderBase<
  NotifierT extends AsyncNotifierBase<T>,
  T
>
    extends ProviderWithNotifier<AsyncValue<T>, NotifierT>
    with FutureModifier<T> {
  // ...
}
```

I debated whether the type parameters should be indented so that the `>` lines up with the other clauses, but ultimately decided not to indent. I'm still on the fence. Fortunately, it rarely comes up in practice.
