### ISSUE TITLE
Chained method calls followed by a cascade have bad indentation

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart_style#137]
I would expect the cascade to be indented 2 or 4 spaces more than `lib.*`

      Iterable<DeclarationMirror> _sortedLibraryDeclarations(LibraryMirror lib) =>
          lib.declarations.values
              .where((d) => d is ClassMirror || d is MethodMirror)
              .toList()
        ..sort((a, b) {
          if (a.runtimeType == b.runtimeType) {
            return _declarationName(a).compareTo(_declarationName(b));
          }
          if (a is MethodMirror && b is ClassMirror) return -1;
          if (a is ClassMirror && b is MethodMirror) return 1;
          return 0;
        });

**Comment by alan-knight** [comment]
Actually looking at the example, to me it seems like it should be six.

If I indent it the same as the .toList() it makes it seem like it's being sent to the original receiver. It's being sent to the result of toList(), so it seems like it should be indented relative to that.

**Comment by jakemac53** [comment]
I would be fine with that as well
