### ISSUE TITLE
dart_style `2.3.5` throws when running `build_runner`

### ISSUE THREAD

**Issue by vkammerer** [dart-lang/dart_style#1413]
I got the following Exception when running `build_runner` on a package I just created:
<img width="1360" alt="Screenshot 2024-02-29 at 17 22 53" src="https://github.com/dart-lang/dart_style/assets/1177483/c24e9930-a50e-4123-b88b-88a786550e11">

It seems related to the release of dart_style `2.3.5` a few hours ago: if I create the same package, but assign the exact version `2.3.4` to dart_style, it runs correctly.

I am using Flutter 3.16.9 / Dart 3.2.6.

Reproduction steps:
```zsh
flutter create dart_style_fails --platforms=macos --empty
flutter create dart_style_works --platforms=macos --empty

cd dart_style_fails
dart pub add dev:build_runner
# the command below will generate the exception
dart run build_runner build

cd ../dart_style_works
dart pub add dev:build_runner dev:dart_style:2.3.4
# the command below will work
dart run build_runner build
```

Output of `flutter --version`:
```
Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (5 weeks ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5
```

**Comment by romreed** [comment]
i got the same issue

**Comment by romreed** [comment]
@vkammerer 
fast fix 
Add analyzer: ^5.11.1 to your dev_dependencies and run the following:

```
flutter clean
flutter pub get
dart run build_runner build
```

**Comment by JesseRiemens** [comment]
This issue was also reported [Stackoverflow](https://stackoverflow.com/questions/78079753/build-runner-showing-error-the-getter-macrokeyword-isnt-defined-for-the-class). Rather than pinning back analyzer, it is a less impactful solution to just pin back this package: 
```yml
pubspec.yaml


dev_dependencies:
    dart_style: 2.3.4
```
as a quick workaround.

**Comment by jakemac53** [comment]
Most likely just a `pub upgrade` would fix this issue as well.

It looks at a glance like the min constraint on the analyzer wasn't increased when the formatting for macro classes was added.

**Comment by munificent** [comment]
Crap. Thanks for drawing my attention to this. I'll get a fix out today. In the meantime, as others have said, either pinning dart_style to 2.3.4 or pinning analyzer to a newer version will route around the API conflict.

I'm sorry for the pain this is causing.

**Comment by munificent** [comment]
OK, I've published a new version of dart_style that fixes the compile error while still having the same analyzer constraint. That means if you run `dart pub upgrade`, it should move you off the old broken version.

Sorry again for the trouble.
