### ISSUE TITLE
This indentation is very unsightly

### ISSUE THREAD

**Issue by niuxinyu** [dart-lang/dart_style#1441]
This is  the test code
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
        child: Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        const Text('你好'),
      ],
    ));
  }
}
```

and this is what it looks like
<img width="536" alt="image" src="https://github.com/dart-lang/dart_style/assets/45762373/5b27639d-33c7-47dc-9403-e113c8ccf12b">

At the position of the Row component, the line break is not quite right，i think
Maybe it should look something like this？
<img width="603" alt="image" src="https://github.com/dart-lang/dart_style/assets/45762373/c6243001-1606-4f87-9887-b00b9c04171e">

And ,this is what it looks like in android studio
<img width="562" alt="image" src="https://github.com/dart-lang/dart_style/assets/45762373/0c1ed52e-b001-4883-bcd3-eb4441cb45a7">

**Comment by munificent** [comment]
I agree, the output is not great here. Output like this is one of the reasons why we're rewriting the formatter and moving to a new style (#1253). With the new in-progress style, the output looks like:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [
        const Text('你好'),
      ]),
    );
  }
}
```

**Comment by munificent** [comment]
Since the new formatter does a good job on this code and we're planning to move to that, I'm going to go ahead and close this.
