### ISSUE TITLE
Strange indenting on method chain with nested anonymous function

### ISSUE THREAD

**Issue by DrMarcII** [dart-lang/dart_style#145]
It was formatted as:
```
return _capabilities
    .then((c) => caps = c)
    .then((_) => _testListenerClient.testCaseStarting(currentTestCase))
    .then((_) => buildAngularDartDriver(additionalCapabilities: caps))
    .then((d) {
  webDriver = d;
  pageLoader = new WebDriverPageLoader(d);
});
```

I would expect/prefer something more like this.
```
return _capabilities
    .then((c) => caps = c)
    .then((_) => _testListenerClient.testCaseStarting(currentTestCase))
    .then((_) => buildAngularDartDriver(additionalCapabilities: caps))
    .then((d) {
      webDriver = d;
      pageLoader = new WebDriverPageLoader(d);
    });
```

**Comment by munificent** [comment]
This is a bit surprising at first, but is as designed and follows the Dart style guide. Function and collection bodies are indented relative to the containing statement, not nested like expressions.

**Comment by DrMarcII** [comment]
I assume that you are referring to: https://www.dartlang.org/articles/style-guide/#dont-indent-lines-that-are-continued-with-a-function-expression

I am not sure that I agree with your interpretation, and the example provided there is not  adequate to disambiguate. I interpret this as meaning that the indent should be equal to the line that starts the function expression (which is what my expectation above conforms to).

So you would have:
```
return x.then(() {
  ...
});
```

and:
```
return x
    .then(() {
      ...
     });
```

**Comment by munificent** [comment]
The style guide should definitely be worded better, but given that *I* worded it, I do know the author's intended meaning pretty well. :)

Function bodies and collection literals are indented relative to the left edge of the beginning of the containing statement, regardless of any wrapping that occurred before the function of collection. I *think* cascades may work the same way, but I can't recall offhand. Cascades are really hairy to format.

There are tests in the formatter to this effect. For example: https://github.com/dart-lang/dart_style/blob/master/test/splitting/invocations.stmt#L54

**Comment by sigmundch** [comment]
Could we change the intent of the style guide on this? pretty please? :)

Here is another example I ran into today:
```dart
bool _readAnnotations(Element element) {
  var found = false;
  element.metadata
      // First filter out anything thats not a StaticInitializer
      .where((ElementAnnotation meta) {
        var e = meta.element;
        if (e is PropertyAccessorElement) {
          return _isStaticInitializer(e.variable.evaluationResult.value.type);
        } else if (e is ConstructorElement) {
          return _isStaticInitializer(e.returnType);
        }
        return false;
      })
      // Now filter out the already seen initializers
      .where((ElementAnnotation meta) {
        if (!seenAnnotations.containsKey(element)) {
          seenAnnotations[element] = new Set<ElementAnnotation>();
        }
        return !seenAnnotations[element].contains(meta);
      }).forEach((ElementAnnotation meta) {
        seenAnnotations[element].add(meta);
        initQueue.addLast(new _InitializerData(element, meta));
        found = true;
      });
  return found;
}
```

today the formatter would produce:
```dart
bool _readAnnotations(Element element) {
  var found = false;
  element.metadata
      // First filter out anything thats not a StaticInitializer
      .where((ElementAnnotation meta) {
    var e = meta.element;
    if (e is PropertyAccessorElement) {
      return _isStaticInitializer(e.variable.evaluationResult.value.type);
    } else if (e is ConstructorElement) {
      return _isStaticInitializer(e.returnType);
    }
    return false;
  })
      // Now filter out the already seen initializers
      .where((ElementAnnotation meta) {
    if (!seenAnnotations.containsKey(element)) {
      seenAnnotations[element] = new Set<ElementAnnotation>();
    }
    return !seenAnnotations[element].contains(meta);
  }).forEach((ElementAnnotation meta) {
    seenAnnotations[element].add(meta);
    initQueue.addLast(new _InitializerData(element, meta));
    found = true;
  });
  return found;
}
```

**Comment by sigmundch** [comment]
ok - it seems that my example is worse because of the comments. The formatter works a lot better if I remove them or move them to be within the callbacks.

**Comment by jakemac53** [comment]
I definitely think that the style guide is wrong on this, here is another example I ran into today which has a few other issues, but its primarily caused by this issue:

    (parseCompilationUnit(dartCode,
                suppressErrors: true) as dynamic).declarations.firstWhere(
            (d) => d.name.toString() ==
                'main').functionExpression.body.block.statements.firstWhere(
        (statement) {
      return statement.expression.target.toString() == 'initializers' &&
          statement.expression.methodName.toString() == 'addAll';
    }).expression.argumentList.arguments[0].elements
        .where((arg) => arg is InstanceCreationExpression)
        .forEach((e) => initEntry(e, transaction));

I think something like this is much better:

    (parseCompilationUnit(dartCode,suppressErrors: true) as dynamic)
        .declarations.firstWhere((d) => d.name.toString() == 'main')
        .functionExpression.body.block.statements
        .firstWhere((statement) {
          return statement.expression.target.toString() == 'initializers' &&
              statement.expression.methodName.toString() == 'addAll';
        }).expression.argumentList.arguments[0].elements
        .where((arg) => arg is InstanceCreationExpression)
        .forEach((e) => initEntry(e, transaction));

**Comment by lassedamgaard** [comment]
Does [this](https://github.com/dart-lang/dart_style/issues/145#issuecomment-70012980) mean that the following is really formatted according to the style guide?

```
final confirmationFuture = _dialogService.showConfirmationDialog(
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    new DialogSettings()
  ..primaryButton = DialogSettings.BUTTON_CANCEL
  ..okButtonText = 'OK'
  ..cancelButtonText = 'Kittens');
```
I think it would be much more clear what the cascade ties to if it was indented 6 spaces instead of 2:

```
final confirmationFuture = _dialogService.showConfirmationDialog(
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    new DialogSettings()
      ..primaryButton = DialogSettings.BUTTON_CANCEL
      ..okButtonText = 'OK'
      ..cancelButtonText = 'Kittens');
```

**Comment by munificent** [comment]
No, that looks like a bug, @lassedamgaard. Can you file a separate issue for that? Thanks!

**Comment by lassedamgaard** [comment]
@munificent Filed https://github.com/dart-lang/dart_style/issues/200.

**Comment by munificent** [comment]
Thanks!
