### ISSUE TITLE
Opt-in anonymous usage measurements and crash reporting

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart_style#149]
Initial design:

The first time a user runs the format tool, it display this prompt:

    [?] May dart_style anonymously report usage statistics and crash reports to improve the tool over time? (Y/n) 

If the user types 'n' or 'N', this response is stored and dart_format does not sending anonymous usage stats or crash reports. The prompt is not displayed again.

If the user types `y` or `Y`, dart_style may report usage statistics (e.g. which command-line flags were used, and how long the tool took to run) and exceptions (per Google Analytics policy).

To opt-out of additional analytics data, run dart_format with --no-analytics. Using --no-analytics does not opt-out of update pings. The --no-analytics option is displayed when --help is used.

The usage library (https://pub.dartlang.org/packages/usage) might be useful here. 

A wiki page will clearly outline this behavior, and state that dart_format is covered under the Google Privacy Policy http://www.google.com/policies/privacy/

**Comment by munificent** [comment]
I don't think this is a real priority for dartfmt any more.
