### ISSUE TITLE
Option for setting indent size.

### ISSUE THREAD

**Issue by austincummings** [dart-lang/dart_style#150]
Not sure if this has already been considered, but I was wondering if it would be possible to have a command-line option for setting the indent size? Like `dartformat --indent=4 dartfile.dart`.

**Comment by kevmoo** [comment]
FYI: our general code style is for 2-space indent

https://www.dartlang.org/articles/style-guide/#whitespace

In general, we've discussed the formatting having few options.

**Comment by munificent** [comment]
Yeah, sorry, but non-configurability is a feature, not a bug. The goal of the formatter is to produce consistent code, and more options make the output less consistent from user to user.
