### ISSUE TITLE
Tall style formatter hangs on certain string interpolations

### ISSUE THREAD

**Issue by Mike278** [dart-lang/dart_style#1516]
I tried running the new formatter on my project and it got stuck on a certain file. I eventually narrowed it down to some specific string interpolation code. For example running `dart format --enable-experiment=tall-style example.dart` with SDK 3.5.0

```dart
var _ = '''
${x(1).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
${x(1).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
${x(1).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
${x(1).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
${x(1).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
${x(1).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
${x(1).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
${x(1).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
''';
```

You can play with the number of rows and columns, but the important bits seem to be:
- must contain at least 2 function calls, each with at least 1 argument
- must overflow the 80 character limit

Playing with the above input:
- 4 lines: 300ms
- 5 lines: 1180ms
- 6 lines: 6200ms
- 7 lines: 44360ms
- 8 lines: left this one blank in case it completed by the time I was done writing this post... it did not 🤪 

Note: the formatted output for 4 lines looks like:
```dart
var _ = '''
${x(
  1,
).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
${x(
  1,
).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
${x(
  1,
).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
${x(
  1,
).x(1).xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
''';
```

FWIW, the original code is a generated SQL statement that glues together different query fragments via function calls.

**Comment by munificent** [comment]
Thanks! Yeah, I think large strings with complex interpolation expressions are still a corner where the solver can go pathological. I need to think more about how to handle that.
