### ISSUE TITLE
Tall style: Missing trailling comma when passing a closure with a block body to a function

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/dart_style#1527]
Hello again!
I encountered the following when playing with the new style:

```dart
  Result<Res> chain<Res>(Res Function(T value) cb) {
    return when(
      data: (value) {
        try {
          return Result.data(cb(value));
        } catch (err, stack) {
          return Result.error(err, stack);
        }
      },
      error: Result.error,
    );
  }

  T get dataOrThrow {
    return when(
      data: (value) => value,
      error: (err, stack) {
        // ignore: only_throw_errors
        throw err;
      },
    );
  }
```

Became:

```dart
  Result<Res> chain<Res>(Res Function(T value) cb) {
    return when(data: (value) {
      try {
        return Result.data(cb(value));
      } catch (err, stack) {
        return Result.error(err, stack);
      }
    }, error: Result.error);
  }

  T get dataOrThrow {
    return when(data: (value) => value, error: (err, stack) {
      // ignore: only_throw_errors
      throw err;
    });
  }
```

I don't mind so much that the formatter removes the trailing comma when a "block" is the last parameter of function invocation. So I'm not against the `dataOrThrow` changes.

But I think that for `chain`, that's a big downgrade.

It is very difficult to stop that `error: Result.error` named parameter with the new change. It's easy for the eye to gloss over that parameter, by thinking that it's part of the logic of the block above.

IMO, if a closure with a block body is used and isn't the last function parameter, we should have a trailing comma.
This would make it easier to view all named parameters.

**Comment by munificent** [comment]
Yeah, as I mentioned on #1528, getting the heuristics right for when arguments should get special block-like formatting versus forcing the entire argument list to split is a subtle art. I don't hate the output in your example here, but I also see what you're saying and don't particularly love it either.

Part of the motivation for the current rules is to make sure that we keep block-formatting the function expressions passed to `test()` and `group()`. Those functions [do take other named parameters](https://pub.dev/documentation/test/latest/test/test.html). Even if a user passes, say, `tags` to `test()`, they *really* don't want the whole test closure to end up indented like:

```dart
test(
  'Test stuff',
  () {
    // Oof, too much indentation...
    expect(stuff, otherStuff);
  },
  tags: ['hi'],
);
```

We might tweak things by saying that if a closure argument is *named* and there are other named arguments, then you don't block format the closure. That would address your example without making `test()` and `group()` calls look worse.

**Comment by rrousselGit** [comment]
> ```dart
> test(
>   'Test stuff',
>   () {
>     // Oof, too much indentation...
>     expect(stuff, otherStuff);
>   },
>   tags: ['hi'],
> );
> ```

IMO that's perfectly correct.

But even better:

```dart
test('Test stuff', tags: ['hi'], () {

});
```

Named arguments everywhere solve those cases.

**Comment by rrousselGit** [comment]
I wouldn't differentiate between named or not.
Only on a single information: Is it the last parameter or not.

Folks can then move the parameter around to match their needs.

**Comment by munificent** [comment]
Yeah, the heuristic definitely needs some tweaks. Here's an example from Flutter:

```dart
    // Before:
    return Scaffold(
      body: Center(
        child: AnimatedDigit(value: value % 10),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() { value += 1; });
        },
        tooltip: 'Increment Digit',
        child: const Icon(Icons.add),
      ),
    );

    // After:
    return Scaffold(
      body: Center(child: AnimatedDigit(value: value % 10)),
      floatingActionButton: FloatingActionButton(onPressed: () {
        setState(() {
          value += 1;
        });
      }, tooltip: 'Increment Digit', child: const Icon(Icons.add)),
    );
```
