### ISSUE TITLE
Tall style: Never write expression switches in a single line

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/dart_style#1529]
Consider a codebase using pattern matching.  
I think it is very important for readability to have every "=>" be on a separate newline.

In my codebase, I had:

```dart
    return switch (that) {
      Family() => that,
      $FamilyOverride() => that.from,
    };
```

But it changed to:

```dart
    return switch (that) { Family() => that, $FamilyOverride() => that.from };
```

This change makes it much harder to view all the cases that are matched against.

It's difficult to differentiate `Foo() => really * Long() * expression` from `Foo() => short, Bar() => short2`.
I think that pattern matching is a special case and should always use trailing commas.

**Comment by munificent** [comment]
> It's difficult to differentiate `Foo() => really * Long() * expression` from `Foo() => short, Bar() => short2`.
> I think that pattern matching is a special case and should always use trailing commas.

That's a good point. Let me sit on this issue for a while and see if others chime in. I'm not morally opposed to special casing switch expressions and forcing them to split, even if I can't come up with a particularly principled reason why they should be treated differently from other expressions that contain comma-separated things.

**Comment by rrousselGit** [comment]
The difference between a switch and say `[a, b, c]` is that there's no pattern in the list literal.  
And there's no "right VS left" operand either.


For instance, I'd always use a comma for a Map litteral with multiple key values.
