### ISSUE TITLE
Tall style: Don't expand (single-element?) lists to multiline if you don't have to

### ISSUE THREAD

**Issue by nex3** [dart-lang/dart_style#1533]
I dislike the fact that the single-element list is expanded here:

```dart
void main() {
  ComplexSelector(complex.leadingCombinators, [
    component,
  ], complex.span, lineBreak: false);
}
```

I'd prefer this:

```dart
void main() {
  ComplexSelector(
    complex.leadingCombinators,
    [component],
    complex.span,
    lineBreak: false
  );
}
```

I think generally I'd prefer the latter style until the list is too long to fit on one line, but I can swallow the former more easily as long as the list has more than one element.

**Comment by dcharkes** [comment]
Might be related to:

* https://github.com/dart-lang/dart_style/issues/1540
