### ISSUE TITLE
[tall-style] Erased trailing comma in list literal

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/dart_style#1558]
The formatter _removed_ a trailing comma here:

https://dart-review.googlesource.com/c/sdk/+/383722/1/pkg/compiler/lib/src/js_backend/backend_impact.dart#105

Another example where the erased trailing comma is in the following list:

https://dart-review.googlesource.com/c/sdk/+/383722/1/pkg/compiler/lib/src/js_backend/backend_impact.dart#323

**Comment by munificent** [comment]
Yes, this is by design. The key idea of the new style is that it automates both adding *and removing* trailing commas. See #1539 for lots more discussion, in particular [this comment](https://github.com/dart-lang/dart_style/issues/1539#issuecomment-2297643639).
