### ISSUE TITLE
[tall-style] Trailing comma in argument list dropped

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/dart_style#1559]
I'm not sure why the trailing comma after the single named argument is dropped here: 

https://dart-review.googlesource.com/c/sdk/+/383722/1/pkg/compiler/lib/src/js_backend/backend_impact.dart#434

The net effect for this file is that it is less readable because _sometimes_ the name of the argument is tucked out of sight on the previous line.  The file as a whole is less consistent (compare with line 421).

**Comment by munificent** [comment]
The formatter is giving you "block style" formatting for that argument list. It's the same style you get in a call like:

```dart
test('description', () {
  ...
});
```

PR #1561 will fix this.
