### ISSUE TITLE
Should the languageVersion parameter to DartFormatter() be optional after all?

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_style#1581]
When I first proposed adding language versioning to the formatter (https://github.com/dart-lang/dart_style/issues/1402), one design question was around passing the version to the library API. @jakemac53 [suggested the parameter should be mandatory](https://github.com/dart-lang/dart_style/issues/1402#issuecomment-2252872826).

I went ahead and did that. In 2.7.3, I added the parameter and made it optional. I rolled that into the Dart SDK and over the past couple of weeks, we've been migrating callsites to pass it in. 

Then in 3.0.0 (not yet released), I made the parameter mandatory.

I realized today that we also need to fix all of the callsites in google3 before we can roll dart_style 3.0.0 into google3. There are 64 of them. A handful of those are already fixed or are inside dart_style itself and will get fixed when it's rolled. But there are quite a lot of others that aren't passing a language version and will need to be migrated.

Based on this, I'm guessing there are a lot more uses of dart_style's library API in the wild than I expected too.

When I migrated everything in the Dart SDK, the solution was almost always to unconditionally pass `DartFormatter.latestLanguageVersion`. That's exactly the behavior you get if you leave out the parameter in 2.7.3. I suspect that most of the time, that's what users want. Most of these callsites are little code generation scripts and they know that they'll work fine with the latest version.

This makes me think the parameter should be optional and default to the latest language version. That would make the dart_style changes less painfully breaking (though still breaking in a few ways because of `--fix` going away, CLI changes, etc.). It would certainly make it easier to roll into google3.

Thoughts, @jakemac53 and @natebosch?

**Comment by jakemac53** [comment]
> When I migrated everything in the Dart SDK, the solution was almost always to unconditionally pass `DartFormatter.latestLanguageVersion`.

Are you sure that was really the correct solution? That doesn't sound right to me. What is the scenario where you don't want to use the real language version?

**Comment by munificent** [comment]
> What is the scenario where you don't want to use the real language version?

Most of the uses of the formatter API that I see are some small one-off script is generating some Dart code and then formatting it. Things like "generate a 100 tests of this pattern", etc.

Those scripts could probably hardcode some random language version from when the script was first written (but at this point, who knows what version that was). But they're probably also fine to just use the latest version. That is, after all, exactly how those scripts behaved for their entire existence up to this point.

**Comment by jakemac53** [comment]
If the code is just for some ephemeral purpose then sure it does not matter how it is formatted. But I think for any other purpose it is important that it matches whatever the actual language version is.

I doubt that dart_style ends up being anything more than a dev dependency typically (or a dependency of a dev dependency), which in general makes the pain of breaking versions lower.

The vast majority of the usages internally are from third_party (only 3 remain if you exclude third_party and experimental). Which is both good and bad, it means if you release the change and wait, much of it will get fixed without involvement. But, there might be a long tail of packages that are harder to fix. Many of these do already pass a language version though, and the total number of packages affected isn't all that large, and we own most if not all of them.

**Comment by natebosch** [comment]
I do think it is worth having users of this library make the explicit change to decide whether to look for a package language version or use the default latest.

**Comment by munificent** [comment]
> The vast majority of the usages internally are from third_party (only 3 remain if you exclude third_party and experimental).

That makes it worse. :) Because it means that we can't simply fix them in-place internally.

> Which is both good and bad, it means if you release the change and wait, much of it will get fixed without involvement. But, there might be a long tail of packages that are harder to fix.

The waiting part is the hard part. As far as I can tell, we can't roll dart_style internally until all of these uses are fixed because they will become compile errors.

> Many of these do already pass a language version though, and the total number of packages affected isn't all that large, and we own most if not all of them.

OK, I'll start drilling into them and try to fix them.

**Comment by jakemac53** [comment]
Another (slightly annoying) option is to just deprecate the current constructor, and make a new one (at least for now), which has them as required. Then we can do another breaking change later to remove the new one, and change the old one to match the new one.

**Comment by munificent** [comment]
Yeah, I considered that but it doesn't really add much value. You get a deprecated warning, but that's about all it provides. If we're going to do anything, I'd rather just go back to making the parameter optional since it does have a fairly obvious default value.

**Comment by jakemac53** [comment]
> If we're going to do anything, I'd rather just go back to making the parameter optional since it does have a fairly obvious default value.

I think it has a fairly _easy_, but usually incorrect default value, which is bad.

**Comment by munificent** [comment]
OK, I'll keep it mandatory. Thanks for the discussion.
