### ISSUE TITLE
'formatter_width' YAML key is snake_case

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart_style#1582]
FWIW, all other analysis options keys are kebab-case (`strict-casts`, `enable-experiment`, `cannot-ignore`, etc.).

It would be nice to be consistent within this file.

**Comment by munificent** [comment]
Oof. I was basing it off the lint rules [which are all snake_case](https://github.com/dart-lang/lints/blob/main/lib/core.yaml). Looks like it's already inconsistent? :(

**Comment by srawlins** [comment]
🤷  Depends on how you look at it. I would say the YAML keys are generally kebab-case. There are values and free-form map keys inside different YAML sections that can be snake case, like lint rule names and compile-time error names.

Also we have a few non-snake_case rules like [no_runtimeType_toString](https://dart.dev/tools/linter-rules/no_runtimeType_toString). 🤕 

I'll leave it to you to keep open or closed.

**Comment by munificent** [comment]
As a tie-breaker, I'll note that the file is `analysis_options.yaml` and not `analysis-options.yaml`, so I'll go ahead and keep it snake_case. But this will haunt me for years.
