### ISSUE TITLE
Formatter should prefer not splitting List/Map literals that can fit on a single line

### ISSUE THREAD

**Issue by cbracken** [dart-lang/dart_style#159]
When a list literal can be wrapped to the line below as follows, it should not be split one entry per line:
```dart
var myList =
    const [ 1, 2, 3, 4, 5, 6, ... ];
```

For an example, see https://github.com/cbracken/quiver-dart/compare/dartformat-list

**Comment by munificent** [comment]
Copying diffs here in case that branch goes away. Before:

```dart
const _DAYS_IN_MONTH =
    const [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
```

After:

```dart
const _DAYS_IN_MONTH = const [
  0,
  31,
  28,
  31,
  30,
  31,
  30,
  31,
  31,
  30,
  31,
  30,
  31
];
```

Before:

```dart
      expect(e.map((v) => v.index), [0, 1, 2], reason:
          'should enumerate to the same values a second time');
```

After:

```dart
      expect(e.map((v) => v.index), [
        0,
        1,
        2
      ], reason: 'should enumerate to the same values a second time');
```

**Comment by jakemac53** [comment]
Similar to the last example in the original report, this gets really bad when accessing items in a list or map:

    -      var scriptId = uriToAssetId(
    -          primaryInput.id, mainScriptTag.attributes['src'], logger,
    -          mainScriptTag.sourceSpan);
    +      var scriptId = uriToAssetId(primaryInput.id, mainScriptTag.attributes[
    +          'src'], logger, mainScriptTag.sourceSpan);

**Comment by munificent** [comment]
Closing this one out:

1. The `_DAYS_IN_MONTH` example is annoying but it's sort of a corner case where you have a list that is *long* but where the items happen to be short enough that it would still fit in one line. Tweaking the rules around splitting at `=` to fix this makes more other code look worse. I think it's best to leave this alone.

2. The `expect` example now gets formatted to:

    ```dart
    expect(e.map((v) => v.index), [0, 1, 2],
        reason: 'should enumerate to the same values a second time');
    ```

3. Jake's example now gets formatted to:

    ```dart
    var scriptId = uriToAssetId(primaryInput.id,
        mainScriptTag.attributes['src'], logger, mainScriptTag.sourceSpan);
    ```

So I think we're good.
