### ISSUE TITLE
Support determining the page_width given a list / lists of multiple included files

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart_style#1591]
For https://github.com/dart-lang/sdk/issues/47256, the analyzer recently supports merging multiple include files, in an analysis options file. So before we only supported:

```yaml
include: some_file.yaml
```

and we now additionally support:

```yaml
include:
  - one_file.yaml
  - ../../another.yaml
  - package:foo/thrid.yaml
```

I believe this package has it's own YAML merging logic to read the single (chain of) include files.

**Comment by srawlins** [comment]
@munificent would you mind if I took a whack at this?

**Comment by munificent** [comment]
I was honestly surprised when I first implemented this that only a single include was supported.

> @munificent would you mind if I took a whack at this?

Sure, not at all! Thanks!
