### ISSUE TITLE
Opt to keep a chained method invocation together, even with named args

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart_style#161]
Actual
```dart
    var partOf = unit.directives.firstWhere((d) => d is PartOfDirective,
        orElse: () => null);
```

Expected
```dart
    var partOf = unit.directives
        .firstWhere((d) => d is PartOfDirective, orElse: () => null);
```

**Comment by munificent** [comment]
I think I prefer the actual output here. Even if I didn't, I'm not sure how we'd distinguish this case from others where you do want to wrap at the named argument.

**Comment by kevmoo** [comment]
To be clear, I just want the full method call to stay together

`.firstWhere((d) => d is PartOfDirective, orElse: () => null);`
