### ISSUE TITLE
Change executable name to dartfmt

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart_style#163]
Just a bit confusing... any chance we can unify the names?

**Comment by munificent** [comment]
Yes, I'll change the executable name to dartfmt once the SDK is running the new formatter code. I'm less concerned about the names shadowing on the PATH if they'll be running at least approximately the same application.

**Comment by seaneagan** [comment]
I think @sethladd was wanting to unify the package (dart_style) with the executable name (dartformat), no?  That would be my preference, any of `dart_format`, `dartformat`, dartfmt` SGTM.  There's a parallel discussion going on [over in dart_lint](https://github.com/dart-lang/linter/issues/25).

**Comment by sethladd** [comment]
I can't remember why we decided to use dart_style and dartformat (two different names).

We recently discussed this, and we decided not to have two different tool names, and just have one tool and one name: dartfmt.

So... should we rename this repo?

**Comment by pq** [comment]
The decision we arrived at over in [dart_lint](https://github.com/dart-lang/linter/issues/25) land was in fact to change that package to the more general `linter` with the expectation that it was already scoped by dartlang and publang for repo and package respectively.  If we follow that lead, why not call this simply `formatter`?

**Comment by pq** [comment]
As for the `dartfmt` legacy, that's my bad...  But can't we just make it *go away*?  I doubt if many users would be affected since I'm guessing they mainly invoke it from a tool (such as DartEditor) and so wouldn't know the difference...

**Comment by sethladd** [comment]
Sublime uses (used?) dartfmt. We don't know how many people have integrated the dartfmt script (because we don't track adoption of our tools). We have to assume that removing it from the SDK is a breaking change.

**Comment by munificent** [comment]
> I can't remember why we decided to use dart_style and dartformat (two different names).

I initially expected it to contain more than just the formatter: stuff like the linter, etc.

After talking about it with @pq, he decided to put the linter in a separate package, but by then the name dart_style was already in use. Since then, we have had a bit of discussion about sharing code between the linter and the formatter, so I'm still wondering if it makes sense to unify those packages.

**Comment by seaneagan** [comment]
@munificent I filed #180 for the suggestion from @pq above to rename this package/repo given it's tighter focus after the `linter` package was split out, since that was not addressed here.
