### ISSUE TITLE
Force blank newline between classes

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/dart_style#168]
This would help with machine-generated code (e.g. Streamy, Angular2).

**Comment by cbracken** [comment]
Can you add an example with expected vs actual output?

**Comment by yjbanov** [comment]
You know, I can no longer reproduce. Closing for now.

**Comment by yjbanov** [comment]
Reopening. Input:

```
class Foo {}
class Bar  {}
```

Output is the same as input. Expected output:

```
class Foo {}

class Bar  {}
```

Notice empty line separating classes.
