### ISSUE TITLE
Long function signtature in equality check causes really weird indentation

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart_style#169]
This is just a really hard one, but the formatter should ensure that the two expressions are lined up. 

Original:

    var scripts = document
        .querySelectorAll('script[type="application/dart"]')
        .where((script) =>
            uriToAssetId(entryPoint, script.attributes['src'], transform.logger,
                script.sourceSpan) ==
            originalDartFile)
        .toList();

Formatted:

    var scripts = document
        .querySelectorAll('script[type="application/dart"]')
        .where((script) => uriToAssetId(entryPoint, script.attributes['src'],
                transform.logger, script.sourceSpan) ==
            originalDartFile)
        .toList();

**Comment by munificent** [comment]
It would be nice, but I don't think it's likely the formatter will be able to handle this case, unfortunately. It doesn't align subexpressions in general, and adding a newline to force alignment in particular would be extra tricky.
