### ISSUE TITLE
Multiple prefix operators?

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_style#170]
I think the new formatter may also suffer from [this bug](https://code.google.com/p/dart/issues/detail?id=18743) from the old one:

> dartfmt fails to format source code that contains a double negation, that is, a unary minus applied to a unary minus.
> 
> EXAMPLE INPUT:
> 
> ```
> main() {
>     print(- -2);
> }
> ```
> 
> OUTPUT:
> 
> Unable to format "double-negate.dart": Expected "-" but got "--", at Line: 2, Column: 11.

**Comment by asgerf** [comment]
The same issue occurs when a unary minus is followed by the decrement operator:
```dart
var x = - --y;
```
Becomes:
```dart
var x = ---y;
```

**Comment by munificent** [comment]
Ooh, nice catch. It handles repeated `-`, but not mixed with `--`.
