### ISSUE TITLE
Ensure there is a blank line before and after all block members...

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart_style#173]
...unless they are the last member in a class

```dart
final a = 1;
final b = 2;
class Bar {
  final c = 1;
  final d =1;
  Bar();
  Bar.foo()
    : c = 3,
      d = 4;
}
```

should be

```dart
final a = 1;
final b = 2;

class Bar {
  final c = 1;
  final d =1;
  Bar();

  Bar.foo()
    : c = 3,
      d = 4;
}
```

**Comment by yjbanov** [comment]
Yep, this example explains the problem pretty well. Another good source of information for formatter issues is [Angular 2 transpiled-then-formatted code](https://pub.dartlang.org/packages/angular2).

**Comment by munificent** [comment]
Fixed by: https://github.com/dart-lang/dart_style/commit/1e802c7895c7236ac77aa3adfc96a9d8486d49f7

**Comment by munificent** [comment]
I should note, however, that it doesn't add the newline you suggest after `Bar();`.
