### ISSUE TITLE
breaking nested lists - consider keeping list togeher?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_style#181]
Not sure if there is something here to do, but this example produces some interesting output:

```dart
var ax = [[ a______________________________________c + c____________________________________b ]];
var ax = [[ a______________________________________c___c____________________________________b ]];
```

current output is:
```dart
var ax = [
  [
    a______________________________________c +
        c____________________________________b
  ]
];
var ax = [
  [a______________________________________c___c____________________________________b]
];
```

I was expecting:

```dart
var ax = [[
    a______________________________________c +
        c____________________________________b
  ]];
var ax = [[
    a______________________________________c___c____________________________________b
]];
```

**Comment by munificent** [comment]
This is working as intended. If a list contains any newline—directly or indirectly—it switches to "multiline" mode an places newlines inside the brackets. Since the inner lists contain newlines, that also forces the outer ones into multiline mode too.

**Comment by sigmundch** [comment]
what do you think about the the second case: should the `[]` be treated as separate tokens than the long identifier inside?

**Comment by munificent** [comment]
They are treated as separate tokens, it's just that splitting around them doesn't help. It considers both solutions:

```dart
var ax = [
  [a______________________________________c___c____________________________________b]
];

var ax = [
  [
    a______________________________________c___c____________________________________b
  ]
];
```

But in this case, splitting inside the inner brackets just pushes the identifier out even farther, which is why it goes with the first solution.

**Comment by sigmundch** [comment]
ah, I see. thanks for the clarification!
