### ISSUE TITLE
If statements test clause is wrapped. Probably better to add parentheses and wrap after.

### ISSUE THREAD

**Issue by xxgreg** [dart-lang/dart_style#182]
The following:

    if (object is List && _integerTag.hasMatch(name))
          return object[int.parse(name)];

Is transformed to:

    if (object is List &&
            _integerTag.hasMatch(name)) return object[int.parse(name)];

This probably would be better as:

    if (object is List && _integerTag.hasMatch(name)) {
          return object[int.parse(name)];
    }

Though I agree this is matter of taste and people will disagree.

On a side note - In my own private style guide I often write 2 line if statements as in the top example. I am aware that this doesn't match the Dart style guide. But I'm ok with adding parentheses - just so I can leave formatting to the machines.

**Comment by xxgreg** [comment]
I re-ran using dartformat instead of dartfmt.

Now the output is transformed to:

       if (object is List && _integerTag.hasMatch(name)) return object[
            int.parse(name)];

**Comment by munificent** [comment]
This is as-designed. The formatter's charter is to only touch whitespace, so it doesn't add brackets or any other substantive changes like that. The linter that @pq is working on likely will handle this.

**Comment by pq** [comment]
I expect we'll have a bunch of lints along these lines down the road. Feel free to open a request so we can track this one. 

https://github.com/dart-lang/linter

Thanks!

**Comment by xxgreg** [comment]
Looks like you've got it already. Keep up the good work!

https://github.com/dart-lang/linter/issues/5

**Comment by pq** [comment]
:)  Thanks!  Feel free to chime in with more!
