### ISSUE TITLE
Multiline String argument should force next argument onto its own line.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart_style#185]
const NO_DART_SCRIPT_AND_EXPERIMENTAL = const MessageTemplate(
         const MessageId('polymer', 6),
         'The experimental bootstrap feature doesn\'t support script tags on '
    -    'the main document (for now).',
    -    'Script tags with experimental bootstrap',
    +    'the main document (for now).', 'Script tags with experimental bootstrap',
         'This experimental feature is no longer supported.');

**Comment by munificent** [comment]
Fixed by 346ad0736b5aff21ce5751c818bd4ccfc02d5885!
