### ISSUE TITLE
Lists/Maps in initializer lists should always be indented past the `:`

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart_style#186]
The original below probably should have been modified, but I would have expected everything to be indented with respect to the opening `[`. I think that in general this violates the style guide but for initializer lists it looks really bad if its not done that way.

    return JSON.encode((span == null)
          ? [{'method': kind, 'params': {'message': entry.message}}]
    -      : [{'method': kind,
    -          'params': {
    -            'file': span.sourceUrl.toString(),
    -            'message': entry.message,
    -            'line': span.start.line + 1,
    -            'charStart': span.start.offset,
    -            'charEnd': span.end.offset,
    -          }}]);
    +      : [
    +    {
    +      'method': kind,
    +      'params': {
    +        'file': span.sourceUrl.toString(),
    +        'message': entry.message,
    +        'line': span.start.line + 1,
    +        'charStart': span.start.offset,
    +        'charEnd': span.end.offset,
    +      }
    +    }
    +  ]);

**Comment by munificent** [comment]
Can you give me some more context for what appears above this diff? What am I looking at?

**Comment by jakemac53** [comment]
Oh whoops, I thought this was a constructors initializer list but it wasn't, it was actually part of a ternary expression. It still looks weird though in this situation. I have edited it above to provide more context.
