### ISSUE TITLE
Named argument lined up incorrectly after map literal

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dart_style#187]
The desc: named argument is indented less than the other arguments to the same function. I don't actually know if it's related to it following the map literal or not. I'd like to reiterate how much I dislike the way the map literal is formatted, but there's a different bug for that (#162).   

      String someComplicatedHelpMessage(String numberInputFieldPlaceholder,
            String timeUnitDropdownPlaceholder) => Intl.message(
                'Deflagrate the persimmon to $numberInputFieldPlaceholder golgafrinchans per'
                '$timeUnitDropdownPlaceholder maximum, unless we say otherwise',
                name: 'someComplicatedHelpMessage',
                args: [numberInputFieldPlaceholder, timeUnitDropdownPlaceholder],
                examples: {
          'numberInputFieldPlaceholder': '3',
          'timeUnitDropdownPlaceholder': 'per light-year'
        },
            desc: 'Some very long descriptive text that actually isn\'t obeying the line length limit but the formatter isn\'t allowed to do anything about that, so get used to it.');

**Comment by munificent** [comment]
Fixed by 346ad0736b5aff21ce5751c818bd4ccfc02d5885!
