### ISSUE TITLE
Multiline boolean expressions

### ISSUE THREAD

**Issue by tosh** [dart-lang/dart_style#190]
I didn't find a recommendation on how to format multiline booleans in the style guide or in the "Idiomatic Dart" article. I guess it is obvious how to do it, just not for me? :)

I personally find myself writing them on the left-hand side similar to what the [Webkit style guide](https://www.webkit.org/coding/coding-style.html) recommends but don't have any strong feelings about them.

I also found a counter-example from a [Google C++ style guide](http://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Boolean_Expressions).

Here is the current `dartfmt` behaviour:

BEFORE
```dart
  bool operator ==(other) => other is Datom
                                   && other.entity == entity
                                   && other.attribute == attribute
                                   && other.value == value;
```

AFTER
```dart
  bool operator ==(other) =>
      other is Datom &&
          other.entity == entity &&
          other.attribute == attribute &&
          other.value == value;
```

(remotely related: would it make sense to consolidate/group the style guide, idiomatic dart article & the API naming guide?)

**Comment by munificent** [comment]
From yon style guide:

> DO place the operator on the preceding line in a multi-line expression.
> There are valid arguments for both styles but most of our code seems to go this way, and consistency > matters most.

:)

> would it make sense to consolidate/group the style guide, idiomatic dart article & the API naming guide?

They cover slightly different areas so probably not, though there's definitely some overall clean up we could, especially now that @pq is working on a linter which has its own set of guidelines.

**Comment by tosh** [comment]
Thanks for the pointer & clarification, I've overlooked that :)

**Comment by pq** [comment]
Great discussion.  I should add @tosh, if you have linter ideas, please do chime in.  It's a field day for feature requests over here:

https://github.com/dart-lang/linter/issues
