### ISSUE TITLE
doc comments at the start of line are not aligned with member 

### ISSUE THREAD

**Issue by a14n** [dart-lang/dart_style#192]
With _0.1.5+3_

```dart
class Foo {
/// test
  Foo();
}
```

is not modified but should be 

```dart
class Foo {
  /// test
  Foo();
}
```

Note that if I prepend the doc comment with any number of white spaces the expected formatting is generated.

**Comment by munificent** [comment]
This is working as intended. If you have a comment that starts at the very beginning of the line, the formatter assumes you probably commented out some code and don't want it be re-indented before the `//`.

**Comment by a14n** [comment]
I thing we should distinguish basic comments `// bla` from doc comments `/// my awesome doc`.

I agree for the first kind of comments that it could be used to comment out some code and it's a good use case to not re-indent. But in the case of doc comments it's different and I think it could be re-indented.

**Comment by munificent** [comment]
Ah, good idea!
