### ISSUE TITLE
Cascades should always split when there is a setter in the cascade.

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dart_style#202]
Cascades should always split when there is a setter in the cascade.
Cascades with >= 3 calls should also always split.

**Comment by jmesserly** [comment]
not sure I agree with the >= 3 ... some examples here:
https://github.com/dart-lang/dart_style/issues/172

splitting on setter would be fine w/ me though

**Comment by munificent** [comment]
> Cascades should always split when there is a setter in the cascade.

Even if there's only one?

```dart
return point..x = 3;
```

?

> Cascades with >= 3 calls should also always split.

This sounds like a separate feature request. (And one I'm not inclined to do. I try to avoid magic numbers in the formatter.)

**Comment by jmesserly** [comment]
> This sounds like a separate feature request. (And one I'm not inclined to do. I try to avoid magic numbers in the formatter.)

yeah, in practice the line length would be the limit anyway in most cases, WDYT @jacob314

**Comment by jacob314** [comment]
if you want a magic number that isn't at all magic, use 7 which is the max number of things the typical person can keep in short term memory :)
# of words in camel case names <= 7 :)
Just added a CL to tweak cascade formatting.
https://codereview.appspot.com/212600043

**Comment by munificent** [comment]
Hey, @jacob314, you fixed this now, right?

**Comment by jacob314** [comment]
Fixed with https://codereview.appspot.com/212600043
