### ISSUE TITLE
Formatter not breaking at highest syntactic construction

### ISSUE THREAD

**Issue by bernardyen** [dart-lang/dart_style#206]
For the following code:

```dart
when(mockLoader.loadData(expectedRequestMetricInitialDateCTR))
    .thenReturn(
         _buildMinimalResponseFuture(MetricType.CTR, metricRequest));
```

the formatter converts it to

```dart
when(mockLoader.loadData(
        expectedRequestMetricInitialDateCTR, any)).thenReturn(
    _buildMinimalResponseFuture(MetricType.CTR, metricRequest));
```

which is very difficult to read. I would have expected something like

```dart
when(mockLoader.loadData(....))
    .thenReturn(.....);
```

Not 100% sure this is a bug, but at least I think the .thenReturn( should be at the start of some line?

**Comment by zoechi** [comment]
When you enclose the code in backticks like
```dart
    ```
    some code here
        some more
    ```
``` 
the formatting is preserved.

**Comment by bernardyen** [comment]
Thanks for pointing out this option!

However, if the formatter is eventually going to be applied automatically,
it doesn't seem reasonable to start littering the code with ``` all over
the place. In my instance, there are probably 10-15 places in a single
class where this happens. It probably makes more sense to improve the
formatter itself.

**Comment by zoechi** [comment]
Sorry, it was only for this issue here on GitHub not for the code in your IDE.
Can you please edit your issues and wrap the code with the backticks as explained 
to make it more obvious what's wrong with the formatting.

**Comment by bernardyen** [comment]
Ah, sorry my misunderstanding. Will do

**Comment by zoechi** [comment]
The part which is supposed to show what you expect is still not formatted properly, please have another look.

**Comment by bernardyen** [comment]
Done
