### ISSUE TITLE
Formatter hangs

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/dart_style#207]
I tried to run the formatter over dart/pkg/analyzer/lib/src/generated/parser.dart from the Dart SVN repository (revision 44273) and it did not either produce output or exit. I used the version of the formatter from the SDK built from that same revision.

**Comment by pq** [comment]
Just reproed on r44296.

FWIW, this file was successfully bulk formatted about a week ago.  The suspect change shouldn't be hard to track down if it's worth it.

**Comment by munificent** [comment]
> FWIW, this file was successfully bulk formatted about a week ago. 

Using the new formatter? That's interesting because it's been a while since I've made any changes to the formatter's actual formatting logic.

**Comment by pq** [comment]
I actually meant that the change to the file being formatted, the one that makes the formatter misbehave, was recent. Sorry for the confusion!

**Comment by munificent** [comment]
Ah, that makes a lot more sense!

**Comment by patefacio** [comment]
I have a similar issue of formatter hanging. I can provide the example if it helps.

**Comment by munificent** [comment]
Yes, if you have an isolated repro case, feel free to add it to: #108. Thanks!

**Comment by munificent** [comment]
This is a dupe of #108.
