### ISSUE TITLE
All lines in a flower box comment should be formatted

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dart_style#208]
For example if user code accidentally writes:

```dart
class Foo {
     /**
        * Oops I messed up my indentation.
      * Wow I'm really not paying attention.
      */
   bar();
}
```
it should be formatted as

```dart
class Foo {
  /**
   * Oops I messed up my indentation.
   * Wow I'm really not paying attention.
   */
   bar();
}
```

Currently the formatter fixes the first line of the flower box comment but does not cleanup the rest.

**Comment by munificent** [comment]
I put some time into this while working on #192 before eventually giving up.

It's possible to do, but it's more work than you'd expect. We have to correctly handle a selection within the reformatted block comment which means splitting it into lines, figuring out where the selection markers are within the split up lines, and then pushing that through everything.

Given that we aren't encouraging people to use `/** ... */` anymore, I don't think it's worth the effort to handle this special case.
