### ISSUE TITLE
Option to lint file for style instead of formatting it

### ISSUE THREAD

**Issue by alexschneider** [dart-lang/dart_style#210]
I have a general distrust for auto-formatters, and I like to use tools like [syntastic](https://github.com/scrooloose/syntastic) to highlight errors and styling issues in my files that I can either chose to fix or ignore. 

[pep8](https://pypi.python.org/pypi/pep8) lints for styling issues in Python files, such as the line being too long, undesirable paradigms, or other conventions listed in PEP8. It'd be nice if we can have something similar for Dart. An example of the output would be:

```
$ dartfmt --lint bad_format.dart
bad_format.dart:2:4: Empty constructor body
bad_format.dart:5:2: Line over-indented
bad_format.dart:9:5: Unnecessary wrapping in getters and setters. 
```

**Comment by zoechi** [comment]
You can use 
- `--dry-run` and check the exit code 
- `-m` to get JSON output and process this in a viewer
- not use `-w` and redirect the output to a temporary file and compare original and temporary with a diff viewer. If the diff viewer supports reading one of the files from stdin you could redirecte the output direct to the viewer.

**Comment by munificent** [comment]
You can do what @zoechi suggests, or this could be something that the [linter](https://github.com/dart-lang/linter) package ultimately supports.

**Comment by alexschneider** [comment]
Ah, I didn't know about the linter package. That looks much more like what I want. Thanks.
