### ISSUE TITLE
A bit weird formatting in a corner case

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart_style#212]
See https://github.com/bwu-dart/bwu_polymer_routing/commit/383e3a3102f96fe4f0838f3fc2be821b059c105e#diff-99d3775460d869d0a3cc04dbc0712f17R15

I'm impressed how well this format is preserved or even improved!

That 

```dart
'movies': routeCfg(
    path: '/movies', // /:userId',
    view: 'view-movies',
```
is changed to 

```dart
'movies': routeCfg(path: '/movies', // /:userId',
    view: 'view-movies',
```

probably because of the comment, is a bit weird.
It doesn't bother me much but I thought you might know.

**Comment by munificent** [comment]
Fixed by 346ad0736b5aff21ce5751c818bd4ccfc02d5885!
