### ISSUE TITLE
export src/io.dart

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart_style#215]
I would like to use `processDirectory()` from `src/io.dart` in a grind task, but for this I have to import from a "private" directory (also needs `src/formatter_options`). 
I don't see a reason why this shouldn't be public - doesn't mean there can't be one though ;-)

**Comment by munificent** [comment]
The only real "reason" is that I haven't spent the time to define and decide what should and shouldn't be in the public API. :)

**Comment by zoechi** [comment]
I thought so. It's not very urgent as long as the linter does't complain about this violation.
