### ISSUE TITLE
Splitting parameter lists of anonymous functions results in less-readable code.

### ISSUE THREAD

**Issue by tlarsen4google** [dart-lang/dart_style#222]
dartfmt transformed this:

    clientParams.forEach((k, v) => log.info(() =>
        "&${k}${(v != null) ? '=${v}' : ''}"));

into this:

    clientParams.forEach((k,
        v) => log.info(() => "&${k}${(v != null) ? '=${v}' : ''}"));

For such anonymous functions, the split should be after the "rocket" (=>) operator if the parameters otherwise already fit on the previous line

**Comment by munificent** [comment]
Fixed by 346ad0736b5aff21ce5751c818bd4ccfc02d5885!

**Comment by tlarsen4google** [comment]
Thanks!
