### ISSUE TITLE
Should never split a single line if statement

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart_style#227]
before

```dart
if (type != null) sb..write(type)..write(' ');
```

after

```dart
if (type != null) sb
  ..write(type)
  ..write(' ');
```

**Comment by jakemac53** [comment]
I think this is probably just a result of always putting cascades on the next line regardless of everything else?

**Comment by munificent** [comment]
Yes, this is as-designed. You shouldn't be using a cascade in a single-line if.

**Comment by jakemac53** [comment]
IMO this should not be the A's designed behavior. It takes something which does not violate the style guide (that I could find) and turns it into something which clearly does.

**Comment by munificent** [comment]
The formatter now allows a cascade of multiple calls to the same named method on one line, so this should work like you want now.
