### ISSUE TITLE
Line length exceeded for list of implemented interfaces

### ISSUE THREAD

**Issue by rkj** [dart-lang/dart_style#228]
My Code that is under 80 chars:

    class SomeLongNameForAComponent implements AttachAware, ShadowRootAware,
        DetachAware, SomeExternalViewFactory, AnotherInterface {

Result after running `darfmt`:

    class SomeLongNameForAComponent
      implements AttachAware, ShadowRootAware, DetachAware, SomeExternalViewFactory, AnotherInterface {

**Comment by munificent** [comment]
Yup, this just a straight up bug. The formatter doesn't support splitting long implements lists. Honestly, this is the first one I've seen that's over 80 characters.

**Comment by rkj** [comment]
Another case is comments - they are not splitted into multiple  lines.

**Comment by munificent** [comment]
Comments are as-designed. The formatter only touches whitespace outside of tokens. It considers comments to be opaque to formatting.
