### ISSUE TITLE
Aliases for long imports should not be on a new line

### ISSUE THREAD

**Issue by jefferyjgannon** [dart-lang/dart_style#230]
If I alias an import "import <80+chars> as foo" it would be more readable if the alias was NOT on a new line.

current result:

import <80+ chars>
  as foo

would like:
import <80+chars> as foo

**Comment by munificent** [comment]
It will do that if the alias fits. But if you have a super long import like:

```dart
import 'package:some/embarrasingly/long/import/url/path/that/is/long.dart' as some_prefix;
```

Then it moves it to the next line. Otherwise, it's too easy to not see the prefix hanging out all the way over on the right edge and you may not realize there is one.
