### ISSUE TITLE
Long exportExpressions lists are indented less than starting line

### ISSUE THREAD

**Issue by jefferyjgannon** [dart-lang/dart_style#232]
if I have a long list of export expressions the formatter is nesting the list of expressions less than the exportExpressions declaration.  For example (shortened for sanity):

```dart
    exportExpressions: const ['foo', 'bar']
```

becomes

```dart
    exportExpressions: const [
  'foo', 
  'bar'
]
```

It seems like it should be:

```dart
    exportExpressions: const [
      'foo', 
      'bar'
]
```

thanks!

**Comment by munificent** [comment]
Can you give me a bit more surrounding context? Many of the formatter's decisions are based on optimizing the layout of an entire statement.

**Comment by jefferyjgannon** [comment]
sure thing...

here's an example of the formatter output for the entire component annotation:

@Component(
    selector: 'foo-dialog',
    templateUrl: 'package:path.to.cool.foo/foo_dialog.html',
    exportExpressions: const [
  'nnnnnnnnState',
  'mmmmmmmmTypeName',
  'blockingId',
  'closeTab',
  'formIsValid',
  'zzzzzzzzzNote'
])

i would think it should be:

@Component(
    selector: 'foo-dialog',
    templateUrl: 'package:path.to.cool.foo/foo_dialog.html',
    exportExpressions: const [
      'nnnnnnnnState',
      'mmmmmmmmTypeName',
      'blockingId',
      'closeTab',
      'formIsValid',
      'zzzzzzzzzNote'
])

let me know if I can provide anything else.

**Comment by munificent** [comment]
Nope, that's perfect! Conveniently, some previous changes also fixed this issue.

**Comment by jefferyjgannon** [comment]
cool :)  thanks for the fix!
