### ISSUE TITLE
line breaks should happen at the higher syntactic level

### ISSUE THREAD

**Issue by dskloetg** [dart-lang/dart_style#242]
I believe this code is correctly formatted:

```dart
library foo;

class PartyOrganizerInterviewer {
  PartyOrganizerInterviewer(@MinimumAgeRequirement int minAge)
      : isChampaignIncluded =
            partyModel.isPropertyTrue(Properties.IS_CHAMPAIGN_AVAILABLE) {
    this.isFoodIncluded =
        partyModel.isPropertyTrue(Properties.IS_FOOD_AVAILABLE);
  }
}
```

but dartfmt turns it into this:

```dart
library foo;

class PartyOrganizerInterviewer {
  PartyOrganizerInterviewer(@MinimumAgeRequirement int minAge)
      : isChampaignIncluded = partyModel
          .isPropertyTrue(Properties.IS_CHAMPAIGN_AVAILABLE) {
    this.isFoodIncluded =
        partyModel.isPropertyTrue(Properties.IS_FOOD_AVAILABLE);
  }
}
```

Why split `partModel.isPropertyTrue` on the dot the first time but not the second time?

**Comment by munificent** [comment]
Yeah, I agree the original formatting is better here. I'll see if I can tweak it to handle this.

**Comment by dskloetg** [comment]
By tweaking, do you mean adding additional logic to cover special cases? I was hoping this is just a bug with the algorithm that tries to break at the higher syntactic level.

**Comment by munificent** [comment]
It depends on how you define "special cases" and "higher syntactic level". The formatter has rules that define what regions of code want to stick together and those determine how things get split and indented. Those rules can be pretty specific in some cases. As human readers, our intuition about what code looks "right" is much more subtle than it probably seems.

**Comment by munificent** [comment]
In this case, the end result was *fewer* special cases. There was a bug where the formatter treated the `=` in a constructor initialization list different from `=` in assignment and variable declarations. The fix was to unify those.
