### ISSUE TITLE
Function parameters indented by more than 4 columns on the next line.

### ISSUE THREAD

**Issue by tlarsen4google** [dart-lang/dart_style#248]
In the code below, shouldn't the `new List<int>.filled(...` line only be indented 4 columns more than the `data = new...` line above it? The second line appears to be indented 8 columns by `dartfmt` instead.

    /**
     * Generate a hex string with a minimum width left filled with zeros.
     */
    String hexString(int val, [int width = 0]) {
      var data = val.toRadixString(16);
      if (data.length < width) {
        data = new String.fromCharCodes(
                new List<int>.filled(width - data.length, '0'.codeUnitAt(0))) +
            data;
      }
      return data;
    }

**Comment by munificent** [comment]
This is deliberate—though admittedly funny looking in this specific case. The extra indentation is to show that the `new List<int>...` line is a subexpression of the larger `+` which wraps to the next line.
