### ISSUE TITLE
Formatter messes up const look up table

### ISSUE THREAD

**Issue by mdakin** [dart-lang/dart_style#254]
I have a manually formatted lookup table,16 values in each line:

    const List<int> decode_ = const [
      -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
      -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
      -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -1, -2, -2, -2, -2,
      -1, -2,  0,  1,  2,  3,  4,  5,  6,  7, -2, -2, -2, -2, -2, -2,
      -2, -2, -2,  8, -2, -2,  9, 10, 11, -2, 12, -2, -2, 13, -2, -2,
      14, 15, 16, -2, -2, -2, 17, 18, 19, -2, -2, -2, -2, -2, -2, -2,
      -2, -2, -2,  8, -2, -2,  9, 10, 11, -2, 12, -2, -2, 13, -2, -2,
      14, 15, 16, -2, -2, -2, 17, 18, 19, -2, -2, -2, -2, -2, -2, -2,];

It formats this into:

    const List<int> decode_ = const [
      -2,
      -2,
      -2,
      -2,
      -2,
    ...

Running dart formatter inside Webstorm with latest dart sdk (1.10.1 May 11th). Also tested from command line.

**Comment by zoechi** [comment]
As far as I understand this is as designed.
Some support annotations or comments to indicate the formatter should preserve a section of the code was also declined.
Currently the only way I see is to move such sections in their own file (part) and format each file separately.
It would be great if dartformat would at least support a configuration file where some includes/excludes could be specified using globs for a package, to be able to just run `dartformat -w` in a package and everything intended to be formatted gets formatted.
The best workaround is to create a script that does just that, read a config file and create a list of files to format and run dartformat for exact these files. This doesn't help for dartformat integrated into an IDE though.

**Comment by mdakin** [comment]
That is unfortunate and current formatted result is quite ugly. I believe this kind of lookup tables are common as well: 

https://github.com/dart-lang/bleeding_edge/blob/8e1a24d96cdbda1bc7ad97dfa3f0054911230201/dart/pkg/compiler/lib/src/hash/sha1.dart#L325

Thanks for the comments about workarounds, but I think dartfmt can at least keep if the list items do not overflow 80 col limit and allow it to stay as it is.

**Comment by munificent** [comment]
I have [a patch out](https://chromiumcodereview.appspot.com/1190233002/) for #139. Once that lands, all you have to do is add a single line comment somewhere inside that collection literal and it will preserve your newlines.
