### ISSUE TITLE
chained methods arguments shouldn't be aligned with preceding methods arguments

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart_style#255]
Before:

```dart
return new Rewriter(code, codegen,
       mirrorMode: mirrorMode, writeStaticInit: writeStaticInit)
    .rewrite(parseCompilationUnit(code, name: reflectionEntryPointPath));
```

After (added another named param, so chained call no longer fit on one line): 

```dart
return new Rewriter(code, codegen,
    mirrorMode: mirrorMode, writeStaticInit: writeStaticInit).rewrite(
    parseCompilationUnit(code,
        name: reflectionEntryPointPath, parseFunctionBodies: false));
```

This makes `parseCompilationUnit...` appear to be an argument to `Rewriter`, instead of the chained `rewrite` method.

Expected something like:

```dart
return new Rewriter(code, codegen,
    mirrorMode: mirrorMode, writeStaticInit: writeStaticInit)
    .rewrite(parseCompilationUnit(code,
        name: reflectionEntryPointPath, parseFunctionBodies: false));
```

**Comment by munificent** [comment]
Oh, yeah. This is doing the wrong thing (though I had to limit the line length to 70 in this example to tickle the bug). I think maybe we should force a split on the `.` if the preceding argument list splits.

**Comment by jakemac53** [comment]
sounds like a good solution to me

**Comment by tlarsen4google** [comment]
Just be sure that, when splitting on . or .., that the indentation for the . or .. line is correct. I am currently seeing this sort of indentation when the split is on the . or .. operator:

    FakeHttpDataFetcher mockIdTokenOkRequests() => new MockHttpDataFetcher(
        mockAuthOkFetch()
      ..addAll({'POST': [mockTokensOkPair(), mockIdTokenOkPair()]}));

I would think the indentation should be:


    FakeHttpDataFetcher mockIdTokenOkRequests() => new MockHttpDataFetcher(
        mockAuthOkFetch()
          ..addAll({'POST': [mockTokensOkPair(), mockIdTokenOkPair()]}));

(This is assuming that . and .. indent by 2 on the next level, instead of 4.)

**Comment by munificent** [comment]
You're correct, @tlarsen4google, the indentation is wrong there and your suggestion is right. The latest formatter should do this correctly now.
