### ISSUE TITLE
`[xxx]` splited after the first square bracket

### ISSUE THREAD

**Issue by a14n** [dart-lang/dart_style#256]
The following formatted code looks strange:

```dart
  static final UNKNOWN_ERROR = new MapsEngineStatus._('UNKNOWN_ERROR', context[
      'google']['maps']['visualization']['MapsEngineStatus']['UNKNOWN_ERROR']);
```

imho it should be splitted between `]` and `[`. Something like:

```dart
  static final UNKNOWN_ERROR = new MapsEngineStatus._('UNKNOWN_ERROR',
      context['google']['maps']['visualization']['MapsEngineStatus']
      ['UNKNOWN_ERROR']);
```

**Comment by munificent** [comment]
Just to make sure, are you running the latest version of the formatter? This behavior changed in the last release or two.

**Comment by a14n** [comment]
I'm using the _Format_ command provided by the _Dart Editor version 1.10.0.release (STABLE)_

**Comment by a14n** [comment]
Same result with dart_style-0.1.7 and dart_style-0.1.8

**Comment by munificent** [comment]
OK, thanks!
