### ISSUE TITLE
Incorrect indentation on constructor initializer list

### ISSUE THREAD

**Issue by jefferyjgannon** [dart-lang/dart_style#258]
![screenshot from 2015-05-22 15 05 20](https://cloud.githubusercontent.com/assets/11791211/7780460/12d58f76-0094-11e5-80a1-fcc8050991f3.png)

see screenshot: there is a slightly different indentation on the parameters to the initializer functions after the first call.

**Comment by munificent** [comment]
Can you include this as text so I don't have to try to correctly count the repeated letters in a PNG? Thanks!

**Comment by jefferyjgannon** [comment]
absolutely...  should have thought to do this before.

https://gist.github.com/jefferyjgannon/d8fc6e34201a13cd3737
