### ISSUE TITLE
hard to read formatting for one liners with a return statement that exceed 80chars

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dart_style#363]
Current behavior:
```dart
if (!_checkType(invocation.namedArguments[name],
    parameters[j].type)) return false;
```
expected behavior:
```dart
if (!_checkType(invocation.namedArguments[name],
    parameters[j].type))
  return false;
```
or:
```dart
if (!_checkType(invocation.namedArguments[name],
    parameters[j].type)) {
  return false;
}
```

**Comment by munificent** [comment]
The formatter's charter is to only touch your whitespace. It doesn't change any non-whitespace program text. For that, you'll want something like Phil's linter stuff.

**Comment by jacob314** [comment]
The expected behavior option 1 only touches white space.

**Comment by munificent** [comment]
Yeah, I understand, but there's no value in explicitly adding support for splitting after `if (...)` to the formatter. The style guide explicitly prohibits a newline from occurring there.
