### ISSUE TITLE
Add option to set exit code on dry-run

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/dart_style#365]
It would be useful to have a flag that would cause a dry-run to set the exit code based on whether or not the formatter would make any changes. This would allow you to require the running of the dart formatter before merging by failing a CI build.

Maybe `--set-exit-code` or `--fail-on-unclean`

**Comment by munificent** [comment]
That's not a bad idea. Right now, the canonical answer is to look for any output on stdout to tell if you should fail a presubmit. Would that work for you, or do you really need a separate exit code?

(#225 has some more context on this too.)

**Comment by evanweible-wf** [comment]
Yeah, that's what I'm doing right now. It's fine and it works, but this would be nice ¯\_(ツ)_/¯

**Comment by munificent** [comment]
I have one small feature request out for review, then I'll kick out a release. Sorry for the delay!
