### ISSUE TITLE
Extra indentation on wrapped function literal

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_style#366]
Before:

```dart
    zoop("zoop description here", spang(() {
        ;
      }));
    }));
```

After:

```dart
    zoop(
        "zoop description here",
        spang(() {
            ;
          }));
        }));
```

It would be good if the formatter kept the function argument to `spang` as a top level block argument.

**Comment by mockturtl** [comment]
[duplicate](https://gist.github.com/mockturtl/d2e9dae839f827f43bda#file-sample-diff-L136)?

**Comment by munificent** [comment]
No, that behavior is different (and deliberate). If an argument list has non-function arguments before and after a function literal, it indents the function like a normal argument.
