### ISSUE TITLE
Formatting separates receiver and method

### ISSUE THREAD

**Issue by typotter** [dart-lang/dart_style#373]
The formatted block below would be more readable if the receiver 'iterable' was not separated from the method '.firstWhere'. Below is the original code and the code resulting from dartfmt. I also tried formatting with the latest formatter (0.2.0-rc.1) and the formatting was the same.

```dart
// Original:
TreeNode lookupEntity(Iterable<TreeNode> iterable, int entity) =>
        iterable.firstWhere(
            (node) => (node.entity == entity),
            orElse: () => null);

// Formatted:
TreeNode lookupEntity(Iterable<TreeNode> iterable, int entity) => iterable
        .firstWhere((node) => (node.entity == entity), orElse: () => null);
```

**Comment by zoechi** [comment]
Can you please edit your comment and wrap code with backticks like
\`\`\`code goes here\`\`\`

**Comment by munificent** [comment]
I'm not crazy about the formatter's output here, but I tried many many rules over the past three days to try to do something better here and failed to come up with anything that didn't make even more examples clearly worse. I'm going to have to call this "good enough" unless someone has any ideas for rules that I haven't tried. :confused:
