### ISSUE TITLE
Cascades are now on one line (after 1.11.0 upgrade)

### ISSUE THREAD

**Issue by enyo** [dart-lang/dart_style#374]
If the line  length is long enough, the dart formatter puts cascades on one line.

I don't think that this is intentional? It reads pretty badly and isn't in the style guide.

Before `1.11.0`:

```dart
shadowRoot.querySelector("#slide-out")
  ..onKeyDown.listen(_hideOnEsc)
  ..onClick.listen(hide);
```
After `1.11.0`:

```dart
shadowRoot.querySelector("#slide-out")..onKeyDown.listen(_hideOnEsc)..onClick.listen(hide);
```

I guess I would always limit the number of cascades that can happen in one line to _one_.

**Comment by munificent** [comment]
No, this definitely isn't intentional. Thanks for the bug!

**Comment by maxwellpeterson-wf** [comment]
+1 seeing this as well
