### ISSUE TITLE
Deferred imports seem to produce a line break in the wrong location

### ISSUE THREAD

**Issue by TedSander** [dart-lang/dart_style#381]
For the following input:
```dart
import 'package:ads.acx2.components.material_expansionpanel.examples/examples.dart' deferred as expansion;
```
The following is produced:
```dart
import 'package:ads.acx2.components.material_expansionpanel.examples/examples.dart' deferred
    as expansion;
```
Expected: The import stays on one line, or breaks before the deferred. It is weird that deferred itself seems like a special case.

Note this was reproduced in both the previous version of dartfmt and the new version.

**Comment by munificent** [comment]
Ah, good catch. I agree, it should split before `deferred` here.

**Comment by rkj** [comment]
I would actually love for them to stay on one line, at least until the formatter can sort imports.
If they are one line, then I can sort them with vim, when they are splitted it requires some tool to help.
