### ISSUE TITLE
Special-case decorator-style methods

### ISSUE THREAD

**Issue by nex3** [dart-lang/dart_style#382]
I use the following pattern occasionally to simulate decorators; that is, to wrap the body of a method in some block or another to modify its behavior. It avoids extra indentation and looks nice, without being too complex:

``` dart
Future doThing() => pool.withResource(() {
  // ...
});
```

Currently, the formatter formats this like so:

``` dart
Future doThing() => pool.withResource(() {
      // ...
    });
```

It would be nice if it recognized the specific pattern of a `=>` method with a block-format body and indented it like a normal method body.

**Comment by seaneagan** [comment]
[per the style guide](https://www.dartlang.org/articles/style-guide/#dont-indent-lines-that-are-continued-with-a-function-expression)

**Comment by munificent** [comment]
You're right, @seaneagan, though we also need to tweak the style guide a bit in light of the formatter's more complex handling of nested function arguments. The original style guide rules just produce really nasty output in some cases.

Relevant style guide bug: https://github.com/dart-lang/www.dartlang.org/issues/1397

**Comment by munificent** [comment]
The [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) supports exactly this. You get:

```dart
Future doThing() => pool.withResource(() {
  // ...
});
```
