### ISSUE TITLE
When parameters span lines, each should get own line

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/dart_style#386]
Actual (as of e845f631cb9d2f5c5011e0ede186a3aea662ae77):

```dart
withNamed(List<String> required1, bool required2,
    {int named1: 0, bool named2: false, String named3}) {}

withOptionalPositionals(List<String> required1, bool required2,
    [int named1 = 0, bool named2 = false, String named3]) {}
```

Expected:

```dart
withNamed(
    List<String> required1,
    bool required2,
    {int named1: 0,
     bool named2: false,
     String named3}) {}

withOptionalPositionals(
    List<String> required1,
    bool required2,
    [int named1 = 0,
     bool named2 = false,
     String named3]) {}
```

Also note the extra one character indent for optional parameters to account for the opening delimiter ("{" or "[").

**Comment by seaneagan** [comment]
Ok, so I noticed it does split in this scenario:

```dart
withNamed(List<String> required1, bool required2, Map<String, String> required3,
    required4,
    {int named1: 0,
    bool named2: false,
    String named3,
    Map<String, String> named4}) {}

withOptionalPositionals(List<String> required1, bool required2,
    Map<String, String> required3, required4,
    [int optional1 = 0,
    bool optional2 = false,
    String optional3,
    Map<String, String> optional4]) {}
```

So it seems to split first between sets of required and optional parameters.  Then if the optionals don't fit on a single line, they each get their own line.  But if the required params don't fit on a single line, they just seem to get split normally (fit them on the minumum number of lines possible).

I like splitting between these two parameters sets a lot, but I would tweak it so that when one of the parameter sets doesn't fit on a single line, then either:

* split all parameters (in both sets) onto their own line.
* split all parameter in the set that didn't fit onto their own line (appears to already be handled for the optional parameter set, but not for the required parameter set).

**Comment by munificent** [comment]
The rules are a bit subtle, but the output is as intended here. Required parameters are handled a bit differently than optional ones. For the former, they are allowed to pack into two lines before being forced to split one-per-line.

The required parameter list can split:

1. Not at all.
2. Before any one parameter.
3. Before each of them.

The optional parameters can split:

1. Not at all.
2. Before the first. (I.e. move the entire parameter list to the next line.)
3. Before each of them.

These are handled semi-independently, though some combinations are disallowed. For example, if there is any split in the required parameters, the optional parameters will split either before the first or before each.

**Comment by seaneagan** [comment]
It seems non-intuitive to me to force some of the parameters to one-per-line, but not others.  It does help keep the line count down though.

**Comment by munificent** [comment]
> It seems non-intuitive to me to force some of the parameters to one-per-line, but not others. 

I think it follows how a lot of hand-formatted code was styled. In some cases, the rules you follow intuitively are more complex than you think.
