### ISSUE TITLE
remove extra indent on => functions returning {} literals

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_style#390]
input:

```dart
toJson() => {
    'a1': 'b',
    'a2': 'b',
    'a3': 'b',
    'a4': 'b',
    'a5': 'b',
    'a6': 'b',
    'a7': 'b',
    'a8': 'b',
};
```

dartfmt 0.2.0-rc1 produces a +6 indent:

```dart
toJson() => {
      'a1': 'b',
      'a2': 'b',
      'a3': 'b',
      'a4': 'b',
      'a5': 'b',
      'a6': 'b',
      'a7': 'b',
      'a8': 'b',
    };
```

dartfmt 0.1.8 produced +2 indent.
I'd prefer to keep the +4 indent :-)

**Comment by munificent** [comment]
I think the indent is helpful here (and it's definitely more consistent). I've seen cases where code has a "lambda that returns a map" and if you don't read closely, it's very easy to think the `{}` define a function body, not a map literal. This helps clarify that.
