### ISSUE TITLE
performance regression on some files (10+ seconds from <1)

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dart_style#391]
The file in question is this monstrosity:
https://github.com/dart-lang/dev_compiler/blob/902cab3c54226b28548140ada0c59d4da48cb8c2/lib/src/options.dart

Perf before (1.8.2+2):
```
time pub run dart_style:format -w lib/src/options.dart 
Unchanged lib/src/options.dart

real	0m0.801s
user	0m0.744s
sys	0m0.103s
```
Perf after (https://github.com/dart-lang/dart_style/commit/7db91c53b9c5cd91fb07302f896742314555dfb7)
```
$ time pub run dart_style:format -w lib/src/options.dart 
Formatted lib/src/options.dart

real	0m11.679s
user	0m11.584s
sys	0m0.482s
```
$ dart --version
Dart VM version: 1.12.0-dev.4.0 (Tue Jul 21 03:40:25 2015) on "macos_x64"

**Comment by jmesserly** [comment]
> The file in question is this monstrosity: [...]

by that I mean, the file is really ugly. :)

(side note, I wonder if anyone's found a good pattern to use the args package with a typed "options" class. I haven't seen any that look all that good, always ends up with some boilerplate/repetition between the arg name and the type and the default value. I guess the package was pre-mirrors, so makes sense in historical context.)

**Comment by munificent** [comment]
> it's not very big, only 300ish lines

[55 of which are a single statement](https://github.com/dart-lang/dev_compiler/blob/902cab3c54226b28548140ada0c59d4da48cb8c2/lib/src/options.dart#L209-L264)!

Not that there's anything wrong with that, of course. The formatter should be faster here. This is the kind of code where the old line splitter happened to have a leg up. I have at least one optimization in mind that I believe will address code like this, but I don't know if that will make it into 0.2.0.

In the meantime, ~10s is definitely painfully slow but still within the bounds of "not a show stopper", I believe. Thanks for the repro case! This will be a good one to benchmark.

**Comment by jmesserly** [comment]
> 55 of which are a single statement!

hah, that's basically the style everyone uses for args package tho.

> In the meantime, ~10s is definitely painfully slow but still within the bounds of "not a show stopper", I believe.

yeah, we already run with exclusions (long story, but basically copied code, so formatting churn would make merges harder) ... so I can just have it skip this file for now.

**Comment by zoechi** [comment]
@jmesserly are you looking for something like https://pub.dartlang.org/packages/unscripted ?

**Comment by jmesserly** [comment]
> @jmesserly are you looking for something like https://pub.dartlang.org/packages/unscripted ?

Something like that, yeah. It's a bit different than what I had in mind (seems a bit more focused around the subcommand case, and using parameters instead of an options object), but the metadata annotations look really nice.
