### ISSUE TITLE
Could some indentation be left alone?

### ISSUE THREAD

**Issue by isoos** [dart-lang/dart_style#393]
1) In annotations, we sometimes use multiple indents, e.g.

````
@View(
    directives: const [XComponent, NgIf],
    template:
        '<div>'
          '<div style="display: flex">'
            '<div style="padding-left: 20px">'
            '</div>'
          '</div>'
        '</div>'
  )
````

This becomes really bad when the formatter flattens it. Can't use '''-strings, as Angular complains that it is not a constant.

2) Closures and their arrays need to keep their indent, e.g.

````
env() =>
    new Env.fromStrings('xx')
      .subEnv('a', [
        'b',
        'c',
        'd',
        'e',
        'f',
        'g',
        'h'
      ])
      .subEnv('x', '1')
      .subEnv('y', '2');
````

The formatter will push the array's value to the beginning of the line, making it not really readable.

**Comment by munificent** [comment]
The general answer to your question is [here](https://github.com/dart-lang/dart_style#why-cant-i-tell-the-formatter-to-ignore-a-region-of-code).

> Can't use '''-strings, as Angular complains that it is not a constant.

That seems like an Angular-specific issue. Why would a multi-line string be any more or less a constant than a single-line one? They can both contain interpolation.

> The formatter will push the array's value to the beginning of the line, making it not really readable.

I'm not sure what you mean here. Is the example you're showing before or after formatting? What's wrong with it?

**Comment by isoos** [comment]
1) I'm not sure if it is Angular per se, a preprocessor complains about the multiline part. It may be that the analyzer is grumpy or something...

2) is before formatting.

**Comment by munificent** [comment]
> 2) is before formatting.

What's the resulting output and what don't you like about it?

**Comment by isoos** [comment]
The array items get only 2 spaces of indent, even less than the method call they are in.
