### ISSUE TITLE
Strange indentation with nested lists in function calls

### ISSUE THREAD

**Issue by tonygentilcore** [dart-lang/dart_style#398]
I'm running `dartfmt` from the 1.12.0-dev.3.1 Dart SDK on some [Sky](https://github.com/domokit/sky_engine/) code.

Before:
```
    children.add(new DrawerHeader(children: [
        new Flex([avatar, username],
            justifyContent: FlexJustifyContent.center,
            direction: FlexDirection.vertical)]));
```

After:
```
    children.add(new DrawerHeader(
        children: [
      new Flex([avatar, username],
          justifyContent: FlexJustifyContent.center,
          direction: FlexDirection.vertical)
    ]));
```

The "before" formatting is just one example of several ways that'd be readable, but the "after" formatting is definitely not one of them. The Sky API encourages many levels of nested constructors so this comes up a lot. This is just a simple example, but I could provide many others if it is helpful.

/cc @ksimbili

**Comment by munificent** [comment]
This is mostly working as intended. The style guide says that `]` always goes on the next line when the list is multi-line. One thing we could possibly improve here is to allow `children:` to remain on the preceding line even though the argument contains a split. (In most cases, when an argument contains a newline internally, that forces the surrounding argument list to also split.)
