### ISSUE TITLE
Prevent reformatting with older dartfmt version

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/dart_style#401]
If a file has been formatted with dartfmt version x, a reformat with dartfmt version y < x should fail (or at least warn). 

For this, dartfmt could insert a comment line into the file, specifying the dartfmt version used, which could be read by subsequent dartfmt runs.

**Comment by munificent** [comment]
Sorry, but I don't think users want dartfmt leaving its signature in every one other their source files. :-/
