### ISSUE TITLE
dartftmt should not push passed character limit.

### ISSUE THREAD

**Issue by gggaisano** [dart-lang/dart_style#406]
If a line is shorter than the hard character line limit, it should not re-format the line and push it passed the limit.

**Comment by gggaisano** [comment]
```dart
class TestComponent {
  String get test =>
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmoda ';
}
```

gets re-formatted to:
```dart
class TestComponent {
  String get test =>
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmoda ';
}
```

So the second last line goes from char length 80 to 82.

**Comment by munificent** [comment]
This is working as intended. The formatter can't guarantee that all lines with fit 80 columns. It tries to make things fit by adding splits where it can, but doesn't do things like break string literals. It also doesn't change its own indentation rules.
