### ISSUE TITLE
Split before adjacent strings pushes string to the right

### ISSUE THREAD

**Issue by MilanLi** [dart-lang/dart_style#409]
Before formatting:

``` dart
it('should complete with an error if the name or website is null or both '
    'are unchanged', async(() {
  ICouldDoAnything();
}));
```

After formatting:

``` dart
it(
    'should complete with an error if the name or website is null or both '        //<------ exceeds 80 chars limit
    'are unchanged', async(() {
  ICouldDoAnything();
}));
```

**Comment by maxwellpeterson-wf** [comment]
This is a common issue we see when writing unit tests with the `test` package as well.

**Comment by munificent** [comment]
Right. The [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) gives you:

```dart
it(
  'should complete with an error if the name or website is null or both '
  'are unchanged',
  async(() {
    ICouldDoAnything();
  }),
);
```

As @srawlins says, the formatter doesn't split strings so it may still push a long string past the end of the page, but in this case, it does so less and has the output I expect.
