### ISSUE TITLE
Subexpressions should not be indented less than the surrounding expression

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/dart_style#414]
The following code (from https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/task/dart.dart#L508) is formatted in a rather unfortunate way because a subexpression has less indentation than it's containing expression:

    static final TaskDescriptor DESCRIPTOR = new TaskDescriptor(
        'BuildCompilationUnitElementTask', createTask, buildInputs,
        <ResultDescriptor>[
      COMPILATION_UNIT_ELEMENT,
      RESOLVED_UNIT1,
      COMPILATION_UNIT_CONSTANTS
    ]);

That makes it hard to see the containment structure. I think it would look better as:

    static final TaskDescriptor DESCRIPTOR = new TaskDescriptor(
        'BuildCompilationUnitElementTask', createTask, buildInputs,
        <ResultDescriptor>[
          COMPILATION_UNIT_ELEMENT,
          RESOLVED_UNIT1,
          COMPILATION_UNIT_CONSTANTS
    ]);

**Comment by munificent** [comment]
This is working as intended. Collection and function bodies are often indented relative to the containing statement. That doesn't strictly respect expression nesting, but it avoids sometimes gratuitous indentation.

It's one of the stranger corners of the style guide, but it's always been there. We inherited from Google's JS (and Java?) guidelines.
