### ISSUE TITLE
Very long short if

### ISSUE THREAD

**Issue by asgerf** [dart-lang/dart_style#416]
foo(x) {
      if (!isInt(x)) return; // VERY LONG COMMENT VERY LONG COMMENT VERY LONG COMMENT
    }

Becomes:

    foo(x) {
      if (!isInt(
          x)) return; // VERY LONG COMMENT VERY LONG COMMENT VERY LONG COMMENT
    }

In a perfect world the output might be:

    foo(x) {
      if (!isInt(x)) {
         // VERY LONG COMMENT VERY LONG COMMENT VERY LONG COMMENT
        return;
      }
    }

But I realize that's probably off the table given how dartfmt works.

Is there no rule that penalizes breaking up a short if?

Maybe it would be better to keep the original form when no good format could be found.

**Comment by zoechi** [comment]
Wasn't there a plan to not break lines with a line comment? #139

**Comment by munificent** [comment]
> But I realize that's probably off the table given how dartfmt works.

Right. Reordering code opens a can of worms.

For the reason behind your specific case, see [here](https://github.com/dart-lang/dart_style#why-doesnt-the-formatter-handle-multi-line-if-statements-better).
