### ISSUE TITLE
Split in receiver did not force method to split

### ISSUE THREAD

**Issue by kegluneq** [dart-lang/dart_style#422]
Input:
```
void allTests() {
  describe('inliner', () {
    it('should inline `templateUrl` values', () async {
      expect(view.namedParameters
          .firstWhere((p) => p.name == 'templateUrl').value)
        .toContain('template.html');
    });
  });
}
```

Output:
```
void allTests() {
  describe('inliner', () {
    it('should inline `templateUrl` values', () async {
      expect(view.namedParameters
          .firstWhere((p) => p.name == 'templateUrl')
          .value).toContain('template.html');
    });
  });
}
```

The linebreak added before `.value` seems odd, thought it might be worth mentioning.

**Comment by munificent** [comment]
The newline before `.value` is right. In a method chain, if one method splits, they generally all do, and properties after a method are considered "methods" for that rule.

It is weird that it doesn't split before `.toContain()` though. It probably should.

**Comment by munificent** [comment]
OK, with the latest code, it is doing what I expect with `.toContain()` now.
