### ISSUE TITLE
Wrong formatting of if statement without { }

### ISSUE THREAD

**Issue by rkj** [dart-lang/dart_style#425]
This:

    void foo(computedField) {
      if (computedField == null)
        throw 'invalid field name in dependencies: $depFieldName';
    }

gets formatted into:
```
void foo(computedField) {
  if (computedField ==
      null) throw 'invalid field name in dependencies: $depFieldName';
}
```

**Comment by munificent** [comment]
See: https://github.com/dart-lang/dart_style#why-doesnt-the-formatter-handle-multi-line-if-statements-better
