### ISSUE TITLE
annotation formatting (in angular 2)

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart_style#426]
Really love dart fmt overall, but I have 2 small complaints about how it formats my angular 2 code:
```dart
@View(
    template: '''
    <nav>
      <a [router-link]="['/page1']">Page1</a>
      <a [router-link]="['/page2']">Page2</a>
    </nav>
    <router-outlet></router-outlet>
    ''',
    directives: const [ROUTER_DIRECTIVES])
class App {}
```

1) The +4 indents, instead of the regular +2 indent feels off to me. In fact, when writing angular 2 code, Webstorm constantly asks me, if I from now on want to format my code with 4 indents. 

![image](https://cloud.githubusercontent.com/assets/1035299/9990315/8cca9520-6060-11e5-91ca-409d021e0ead.png)

I know this is more a Webstorm issue, but at least Webstorm agrees with me that it seems inconsistent to have 4 spaces of indents there ;)

2) Having the closing paren `)` not on a new line, looks a bit asymmetric to me. In the same sense that this doesn't look good to me:

```
if (1 + 1 == 2) {
  print("math still works!");}
```

**Comment by munificent** [comment]
Both of these rules are the same as how the formatter handles all other argument lists. Being consistent is important because these things do compose. For example:

```dart
function(
    @Annotation(
        long,
        argument(this, one, has, inner,
            arguments),
        list)
    parameter,
    anotherParameter) {}
```

Special case rules look nice in simple examples, but rarely work out in all of the weird and woolly ways that end users compose code.

**Comment by kasperpeulen** [comment]
@munificent I can see that putting the right paren on a new line can be problematic in some cases
but not totally convinced about the 4 spaces for indents, what is the idea behind this ?

```dart
function(
  @Annotation(
    long,
      argument(this, one, has, inner, arguments),
    list)
  parameter,
  anotherParameter) {}
```

**Comment by munificent** [comment]
A four space indent for wrapped expressions ensures they don't line up with later blocks:

```dart
if (function(long, argumentList,
  that, wraps) {
  oopsLinesUpWithPreviousLine();
}
```

**Comment by kasperpeulen** [comment]
oh I see thanks @munificent
