### ISSUE TITLE
Format Dart code in HTML files

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/dart_style#427]
```
<html>
<body>
<script type="application/dart">
  var               a;
</script>
</body>
</html>
```
Currently if you pass HTML file as a parameter of the `dart_style` tool it tries to parse the whole HTML as a Dart file and reports tons of syntax errors. I'd expect resulting text with untouched HTML part and formatted Dart injections.

**Comment by munificent** [comment]
I think parsing HTML is out of scope for the Dart formatter.

**Comment by kasperpeulen** [comment]
@munificent In polymer, many people the dart logic of a web component inside a html file. See https://github.com/dart-lang/polymer-dart/blob/master/example/component/news/web/news-component.html for an example. I would love to also use the Dart formatter in this case.
