### ISSUE TITLE
Non-intuitive splitting of generic types

### ISSUE THREAD

**Issue by bernardyen** [dart-lang/dart_style#429]
Before formatting

```
  final Map<String, SummaryTabDataRequest_CampaignSkinSubtype>
      _campaignSkinSubtypes =
          new Map.fromIterable(
              SummaryTabDataRequest_CampaignSkinSubtype.values,
              key: (campaignSkinSubtype) => campaignSkinSubtype.name,
              value: (campaignSkinSubtype) => campaignSkinSubtype);
```

After formatting

```
  final Map<String,
          SummaryTabDataRequest_CampaignSkinSubtype> _campaignSkinSubtypes =
      new Map.fromIterable(SummaryTabDataRequest_CampaignSkinSubtype.values,
          key: (campaignSkinSubtype) => campaignSkinSubtype.name,
          value: (campaignSkinSubtype) => campaignSkinSubtype);
```

The formatter should try to keep the generics together if possible and favor moving the variable to the next line.

Also, it's very weird to keep the first param non-line-breaked while the other two does. Recommend breaking all variables if it's necessary to break.

**Comment by munificent** [comment]
> The formatter should try to keep the generics together if possible and favor moving the variable to the next line.

Yeah, I agree. I'm not sure why it's splitting there, but it shouldn't.

> Also, it's very weird to keep the first param non-line-breaked while the other two does.

It considers named parameters looser than positional ones, so it allows the former to split without splitting the latter.

**Comment by queltos** [comment]
Wouldn't it even make sense to have named parameters always in an extra line? At least when the parameter is a function? There's this example from the [dart docs](https://api.dartlang.org/133446/dart-core/Map/Map.fromIterable.html):
```dart
Map<String, int> map = new Map.fromIterable(list,
    key: (item) => item.toString(),
    value: (item) => item * item));
```
And this nice formatting gets lost in current dartfmt:
```dart
  Map<String, int> map = new Map.fromIterable(list,
      key: (item) => item.toString(), value: (item) => item * item);
```
(and in the example in dart docs there's one too many closing parentheses)

**Comment by munificent** [comment]
I try to avoid special-cases as much as I can. While they always look great in good examples, there tend to be even more bad examples where the special case makes things worse. I don't think having a splitting rule for named parameters where some (any? all?) arguments are lambdas cause the argument list to be treated differently would be a net win.
