### ISSUE TITLE
If statement formatted incorrectly

### ISSUE THREAD

**Issue by jrote1** [dart-lang/dart_style#432]
I think this is incorrect formatting but am not 100%

I have the following if statement and it is formatted like this
```
if (generatedMap.instantiate ==
    null) throw "Type '$type' does not have a default constructor, make sure it has a default constructor wuth no paramters";
```

I think it should be formatted like this
```
if (generatedMap.instantiate == null)
    throw "Type '$type' does not have a default constructor, make sure it has a default constructor wuth no paramters";
```

**Comment by munificent** [comment]
See: https://github.com/dart-lang/dart_style#why-doesnt-the-formatter-handle-multi-line-if-statements-better
