### ISSUE TITLE
Optional parameters inconsistently indented.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart_style#433]
Example code: 
```
main([List<String> args, someverylongnamethatensuresthiswontstayononeline,
      int port]) {
  print(args);
}

```
becomes
```
main(
    [List<String> args,
    someverylongnamethatensuresthiswontstayononeline,
    int port]) {
  print(args);
}
```
Here the second and third parameter is not indented to align with the first one - it ignores that the `[` introduces further indentation.

Acceptable results could be:
```
main(
    [List<String> args,
     someverylongnamethatensuresthiswontstayononeline,
     int port]) {
  print(args);
}
```
or
```
main([
    List<String> args,
    someverylongnamethatensuresthiswontstayononeline,
    int port]) {
  print(args);
}
```
or even
```
main([List<String> args,
      someverylongnamethatensuresthiswontstayononeline,
      int port]) {
  print(args);
}
```

**Comment by munificent** [comment]
I know it's a little weird, but it's the intended behavior. When I implemented this, I asked a bunch of people and looked at the a bunch of existing code and the current behavior was the consensus answer for how it should handle it.

Would be nice if we didn't have such a lame syntax for optional parameters. :(
