### ISSUE TITLE
Parse error on Null-Aware operators

### ISSUE THREAD

**Issue by aghassemi** [dart-lang/dart_style#435]
`dartfmt` produces the following parse errors on some null-aware operators.

For instance for 
```
x ??= 'unknown';
```
I get 
```
line 1, column 3 of stdin: Expected a method, getter, setter or operator declaration
x ??= 'unknown';
  ^
line 1, column 3 of stdin: Expected a method, getter, setter or operator declaration
x ??= 'unknown';
  ^
line 1, column 3 of stdin: Unexpected token '?'
x ??= 'unknown';
```

**Comment by munificent** [comment]
What version of dart_style are you using? Null-aware operator support was added in 0.2.0.

**Comment by aghassemi** [comment]
Double checked and also did a fresh project, I am running 0.2.0. Both `dartfmt` and `pub global run dart_style:format` throw the same error on `x ??= 'unknown';`

**Comment by munificent** [comment]
Thanks, I'll take a look!

**Comment by aghassemi** [comment]
btw, I upgraded to the dev channel ( 1.13.0-dev.5.0 ) and now all is good. I was on 1.12 release before.

**Comment by munificent** [comment]
Oh, OK. You must not have been running your locally installed version of the formatter then?
