### ISSUE TITLE
No indent after break of named argument

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/dart_style#441]
Not sure how this should be formatted, but the way the fourth line is not indented is not right:
```dart
getSomeFoo(
    {fooooooooooooooooooooo: const [
  'baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
]}) {
  return 'rhubarb';
}
```

**Comment by munificent** [comment]
I agree this isn't formatted right.

As an aside, if this were my code, I'd put that list in a named constant. A multi-line default value is never going to be easy to read!
