### ISSUE TITLE
allow lines to go over 80 chars when the alternative is worse

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dart_style#450]
The following source line goes over 80 characters:
```dart
  final List<TextDecoration> decoration; // TODO(ianh): Switch this to a Set<> once Dart supports constant Sets
```

I'm not sure exactly what the right solution is, but this (the current output) is the wrong answer:
```dart
  final List<
      TextDecoration> decoration; // TODO(ianh): Switch this to a Set<> once Dart supports constant Sets
```

The right answer is probably either to just let it go over 80 characters, or put the entire comment on the next line or previous line.

Similarly, given this input:
```dart
    debugPrint('------------------------------------------------------------------------');
```
...the following output is worse than the input:
```dart
    debugPrint(
        '------------------------------------------------------------------------');
```

Another example. Input:
```dart
        assert(heroes[tag].keys.where((Key key) => mostValuableKeys.contains(key)).length <= 1);
```
This is better than the current output:
```dart
        assert(heroes[tag]
                .keys
                .where((Key key) => mostValuableKeys.contains(key))
                .length <=
            1);
```

**Comment by munificent** [comment]
```dart
  final List<
      TextDecoration> decoration; // TODO(ianh): Switch this to a Set<> once Dart supports constant Sets```

For this one, I think the right answer is for the author to move the comment to the previous line. Sometimes you have a sort of interactive conversation with the formatter. You throw some code at it and see how it formats that. If it ends up weird, maybe you rearrange and expression or hoist a subexpression to a local variable and reformat it.

This is one of those cases where I think tweaking your code to be harmonious with the formatter is worth doing.

```dart
    debugPrint(
        '------------------------------------------------------------------------');
```

I actually prefer the output here. Of course, ideally you'd split the string so that it can be wrapped to fit in 80 columns. Again, this is a case where you may want to iterate with the formatter a bit.

```dart
        assert(heroes[tag]
                .keys
                .where((Key key) => mostValuableKeys.contains(key))
                .length <=
            1);
```

The annoying thing about this one is that `assert()` isn't abstraction-friendly. It's hard to hoist subexpressions out of it because you don't want them to be evaluated in release builds. You could move the body to a function, maybe. Maybe shorten `mostValuableKeys` to `bestKeys`.

In this case, there's an easier fix:

```dart
        assert(heroes[tag].keys.where(mostValuableKeys.contains).length <= 1);
```

In any case, I think the formatter is generally doing the right thing here. It's job is to try to optimize the line length. It can't control the input you give it, so it does the best it can and sometimes the result is a signal to the reader that they should tweak their code a bit and try again.

**Comment by Hixie** [comment]
I don't think the analyzer should ever make the code worse. If it can't make it better, it should just leave it as-is. Take the first example above:
```dart
  final List<TextDecoration> decoration; // TODO(ianh): Switch this to a Set<> once Dart supports constant Sets
```
If the author has decided that this actually is the optimal way of laying out that line, then the analyzer should respect that and leave it. This is clearly a better rendering than:
```dart
  final List<
      TextDecoration> decoration; // TODO(ianh): Switch this to a Set<> once Dart supports constant Sets
```
If the formatter is of the opinion that the comment should be on the previous line, then it should do that. If it doesn't do that, then it should do nothing.

I don't view using the formatter as a conversation. I view it as a tool that can be used to improve the code quality. Having it be a conversation implies that the formatter is a peer of the programmer, not a tool. Having the tool make the code worse where it thinks the code should be differently structured is kinda passive aggressive, when you think about it. :-)

**Comment by munificent** [comment]
> I don't think the analyzer should ever make the code worse.

Well, sure. The difficulty lies in precisely defining "worse". The formatter's current logic is:

1. Avoiding splits (like after `List<` here) is worse.
2. But any character that overflows the line limit is way worse.
3. If the user put a line comment at the end of a line, they intended that line comment to stick at the end of the line, so don't put a newline before it.

Those rules work fine in most situations, but, like any ruleset, you can always come up with pathological examples that hurt it. A line of code that *can* split but looks really funny if you do followed by a really long line comment that blows the page width is just such an example.

> If it can't make it better, it should just leave it as-is.

It's a non-goal to preserve much of the user's original formatting. (If your goal is to preserve your formatting, `cat` is a generally more reliable and faster formatter. :wink:) We could say, "Well, if there was any overflow than give up and go back to the original code." But that's worse in the majority of cases where even if it can't totally fit the result, it can clean up lots of other issues in that statement.

It's also hard to define the scope of what lines it shouldn't change when that happens. If, for example, you have a long line inside a function body, which is contained in a list, which is an argument to a function, which of those elements get formatted and which don't?

> I don't view using the formatter as a conversation. I view it as a tool that can be used to improve the code quality. 

Sure. Lots of tools are interactive. It's a rare piece of software that can do it's job completely without human supervision, and given that this program's entire purpose is to make stuff "look pretty to people", *some* amount of feedback and iteration doesn't seem unreasonable to me.

Look at it like this: when you hand format your code, do you occasionally run into situations where you don't like the formatting? When that happens, do you sometimes tweak the code—hoist a subexpression, add a local variable—and reformat it to make it look better? This is the same process, it's just that *parts* of it are automated.

> Having the tool make the code worse where it thinks the code should be differently structured is kinda passive aggressive, when you think about it. :-)

Not at passive aggressive as throwing code at the formatter that you know it can't fix and then refusing to help it out a bit!
