### ISSUE TITLE
Convert between "if () ..." and "if () { ... }" based on line length

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dart_style#453]
In the flutter style guide, we have the rule that if a block spans multiple lines, it must have braces, and if it only spans one line, it must be indented by two on its own line. It would be interesting if the formatter could automatically add or remove these braces based on the number of lines.

For example, turning this:
```dart
  if (foo)
    if (bar)
      hello();
  while (baz) {
    goodbye()
  }
```

...into this:
```dart
  if (foo) {
    if (bar)
      hello();
  }
  while (baz)
    goodbye()
```

**Comment by munificent** [comment]
Like I mentioned on #451, this is out of scope for the formatter as it's currently specced.

**Comment by Hixie** [comment]
I don't understand how this is different than whitespace.
