### ISSUE TITLE
"Sort Members in Dart File" to sort imports is not separating my local imports

### ISSUE THREAD

**Issue by davenotik** [dart-lang/dart_style#457]
I'm assuming the WebStorm option of said name is part of dart_style.

IMO, it should automatically do as per this preference in the style guide:

https://www.dartlang.org/effective-dart/style/#prefer-placing-third-party-package-imports-before-other-imports

In my case: http://d.pr/i/1hFHk

**Comment by munificent** [comment]
No, dart_style doesn't do any reordering or separation of imports.

Aside from re-ordering, it can't add separation in general because it doesn't know which of your imports are "third party" and which aren't.

**Comment by enyo** [comment]
@munificent why doesn't dartstyle reorder imports? The most obvious thing would be to put `dart:*` imports first, then separate by a line, then third party imports.

As to differentiate between third party & project imports: maybe `dartfmt` could be invoked with a parameter to provide the library name of the project? Something like `dartfmt --project-name=my_app`. Then other tools or IDEs could use `pubspec.yaml` to provide this parameter as well.

**Comment by munificent** [comment]
See [the FAQ](https://github.com/dart-lang/dart_style/wiki/FAQ#why-doesnt-the-formatter-add-curlies-or-otherwise-clean-up-code).

**Comment by enyo** [comment]
Got it @munificent . Is there a way you would reconsider if you made import reordering optional with a flag?

**Comment by munificent** [comment]
> Is there a way you would reconsider if you made import reordering optional with a flag?

It's not about me reconsidering the feature, it's out of scope for what dartfmt does. I agree it's a useful feature, it just shouldn't be implemented in the formatter. :)

If you use IntelliJ, the Dart plugin there supports sorting imports. I'm not sure if that functionality is exposed to any other editors.

**Comment by enyo** [comment]
@munificent I'm using this feature in IntelliJ. The reason we'd love to have it in `dartfmt` is so we 1) do not depend on any IDE implementation and 2) can add it to our continuous testing to make sure our codebase is uniform.
But I understand your reasoning, so I'll just be sad but will stop bothering you ;)

**Comment by munificent** [comment]
> 1) do not depend on any IDE implementation

The feature in IntelliJ is built on top of [analyzer](https://github.com/dart-lang/sdk/tree/master/pkg/analyzer), which is not IDE specific. It's integrated into a bunch of different editors and IDEs.

> 2) can add it to our continuous testing to make sure our codebase is uniform.

Analyzer has a command-line too (`dartanalyzer`). I don't know if it exposes this command, but it's possible to. The right place to file a feature request is [here](https://github.com/dart-lang/sdk/issues).

**Comment by alexeieleusis** [comment]
@munificient Is there a way to run this from command line so it could sort all files in a project?

**Comment by munificent** [comment]
I'm not sure. That's an analyzer question since dartfmt doesn't do any sorting.

**Comment by jodinathan** [comment]
couldn't find any issue in the sdk repo regarding the sorting command.  
Do you know if there is one @munificent, @enyo ?

**Comment by munificent** [comment]
> Do you know if there is one @munificent, @enyo ?

I don't, sorry.
