### ISSUE TITLE
Weird generic type formatting (also breaks line character limit)

### ISSUE THREAD

**Issue by BlackHC** [dart-lang/dart_style#462]
```
  Future<
      ComponentSettings<
          BiddingStrategyConfiguration>> _biddingStrategyConfigurationFuture;

  Future<
      ComponentSettings<
          BiddingStrategyConfiguration>> get biddingStrategyConfigurationFuture =>
      _biddingStrategyConfigurationFuture;
```

The formatter also goes over 80 characters limit for the second one, though it should be possible to format this while keeping the 80 character constraint.

**Comment by kevmoo** [comment]
Ditto - on d2fe7f4

![dart_style_weird_break_in_generics](https://cloud.githubusercontent.com/assets/17034/11198880/6275b96e-8c7d-11e5-9a02-c5e9f2ff9131.png)
