### ISSUE TITLE
add option to format a single statement with current indent level

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_style#464]
My use case: I want to select a statement line and sent it to dartfmt and to see how the formatting would look like, without having to reformat the entire file I'm working on. I intend to use this when providing a patch to a project that doesn't follow the style guide and changing the entire file is not an option.

I believe this is somewhat similar to what you already have for unit tests, I'm hoping we can provide the feature as a flag to `dartfmt`. We could either provide the indentation explicitly on the flag, or use the leading spaces on the line as the "current" indentation.

We could generalize this feature and provide a segment to dartfmt, but that makes it hard to detect how to parse it - by restricting it to statements, you can assume you can use the statement portion of the parser (similar to how you use the compilation-unit-parser when working on the entire file).

Example usage:
```sh
echo "  this.code('is indented with 2 spaces to begin with .........................');"\
    | dartfmt --statement 
# produces
  this.code(
      'is indented with 2 spaces to begin with');
```

**Comment by munificent** [comment]
Yeah, this is easy to expose to the command-line API.

I'm a little iffy about inferring if from the leading whitespace of the source. In most cases, fixing those kinds of issues is a goal of the formatter. Would an explicit `--indent <n>` command line argument work instead?

**Comment by sigmundch** [comment]
Cool! It would be nice to infer it in the future :), but yes, a flag would work. Can we have a short name for the flag, so for example we could write `-i2` ?

Thanks!

**Comment by munificent** [comment]
Yup, I'll abbreviate it.
