### ISSUE TITLE
If last arg is a list literal, it gets pushed up next to arg N-1 

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart_style#465]
With dart_style @ d2fe7f4

![dart_style_last_arg_array](https://cloud.githubusercontent.com/assets/17034/11198896/8c6e6090-8c7d-11e5-8cfd-165f44733d5b.png)

**Comment by munificent** [comment]
Actual text that I can copy and paste would be really helpful here. Please don't make me retype that by hand. :sob:
