### ISSUE TITLE
Odd reformatting of if statement without curlies

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dart_style#468]
Before:

![screen shot 2015-11-20 at 3 31 58 pm](https://cloud.githubusercontent.com/assets/5479/11314618/05c81bfe-8f9c-11e5-98cf-050b394fd8aa.png)

After:

![screen shot 2015-11-20 at 3 32 03 pm](https://cloud.githubusercontent.com/assets/5479/11314613/fdd70950-8f9b-11e5-925f-ddeb03c92320.png)

Notice that the formatter moves the `variable =` up to the line with the if conditional. I wouldn't have expected that.

**Comment by munificent** [comment]
This should be fixed in the latest code in the repo, would you mind testing this against the latest?

```
$ pub global activate -git https://github.com/dart-lang/dart_style.git
$ dartformat ...
```

**Comment by sethladd** [comment]
Hm, Looks like the latest out of git still moves the variable initialization up to the same line as the if.

```
~/tmp $ ~/.pub-cache/bin/dartfmt blah.dart 
main() {
  var x;
  if (false) x = 1;
}
```

```
~/tmp $ ~/.pub-cache/bin/dartfmt --version
0.2.0+1
```

**Comment by munificent** [comment]
Yeah, that behavior is fine. It's removing an unnecessary newline. That's different from the original bug you filed where a *needed* newline appeared in the wrong place.

**Comment by sethladd** [comment]
Thanks for the explanation.
