### ISSUE TITLE
Formatter is inconsistent about aligning comments

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/dart_style#472]
The example below contains three comments with an unaligned line.  The formatter re-aligns the middle one but not the other two.  Is this intentional?  I'd love it to align comments for me, and it seems to do so for the `//` style comments, but it's surprising to have it do some but not others.

```dart
class A {
/**
   * Comment doesn't get aligned
   */
  int get foo => 3;

 /**
   * Comment gets aligned
   */
  int get bar => 3;

  /**
 * Comment doesn't get aligned
   */
  int get baz => 3;
}
```

**Comment by munificent** [comment]
This is annoying but is as designed. The formatter doesn't touch any characters within a comment since it has no way of knowing which ones are meaningful to you. So, here, it can fix the indentation before the `/**` because that whitespace occurs *before* the comment, but it doesn't touch the indentation on the subsequent lines because those are within the comment token itself.

`//` comments don't have that issue because each line is a separate comment.

Another reason to avoid JavaDoc style comments. ;)

**Comment by leafpetersen** [comment]
That only describes the behavior of the last of the three examples.  Per your description of the intended behavior, I would expect it to fix the indentation of the comment on foo (as it does on bar) even if it won't on baz.  Am I missing something?

**Comment by munificent** [comment]
Ah, yes. There's one other wrinkle I didn't mention. :)

The formatter also has a rule that if a comment starts at column 0, then it is not reindented. This is to ensure commented out code is not "fixed" by having indentation applied to it. It would be annoying if the formatter took code like:

```dart
if (something) {
  while (anotherThing) {
    doStuff();

//    brokenStuff();
//    moreBrokenStuff();

    moreStuff();
  }
}
```

and "corrected" it to:

```dart
if (something) {
  while (anotherThing) {
    doStuff();

    //    brokenStuff();
    //    moreBrokenStuff();

    moreStuff();
  }
}
```

If you add *one* space before the `/**` on `foo`, then you'll see that it does fix its indentation after that.

**Comment by a14n** [comment]
@munificent but `/**` is a doc comment and should be treated like #192

**Comment by leafpetersen** [comment]
Ok, this did actually come up in a code review, but I'm not too fussed, it's a pretty rare case.  Thanks!

**Comment by munificent** [comment]
@a14n, since the style guide [requires /// for doc comments](https://www.dartlang.org/effective-dart/documentation/#do-use--doc-comments-to-document-members-and-types), the formatter only special cases that form.

**Comment by a14n** [comment]
Not a big deal I always follow the style guide ;)
I was pointing this because the [Dart Programming Language Specification](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-408.pdf) (section 20.1.2) states :

>Documentation comments are comments that begin with the tokens `///` or `/**`. Documentation comments are intended to be processed by a tool that produces human readable documentation.

**Comment by munificent** [comment]
I don't think there's any rational reason that the language spec mentions doc comments at all. :-/
