### ISSUE TITLE
format generic method comments?

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dart_style#477]
we're working on "strong mode" generic methods. For experimentation purposes we use comments:
```dart
Object/*=V*/ getResult/*<V>*/ (
      AnalysisTarget target, ResultDescriptor/*<V>*/ result) {
```
it's a tiny issue, but formatting introduces an extra space:
```dart
Object /*=V*/ getResult /*<V>*/ (
      AnalysisTarget target, ResultDescriptor /*<V>*/ result) {
```
I wonder if it would make sense to recognize these special comments and skip the preceding space?

FYI, I'm happy to work on this, but I wanted to see if it sounded like a good idea or not.

(FWIW... with the right flag to the Scanner, it will make a special TokenType for those comments ... that's how the Parser finds them quickly when "strong mode" is on ... so at least that part is pretty easy)

**Comment by munificent** [comment]
Yeah, I'd be happy to do something smarter here. We can just tweak [`_needsSpaceBeforeComment()`](https://github.com/dart-lang/dart_style/blob/master/lib/src/chunk_builder.dart#L636) and [`_needsSpaceAfterLastComment()`](https://github.com/dart-lang/dart_style/blob/master/lib/src/chunk_builder.dart#L655) to look at the comment text and recognize these forms.

Send me a patch!
