### ISSUE TITLE
More prescriptive annotation formatting

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_style#483]
The formatting currently preserves a source newline between a member and a single metadata annotation. This was because in existing code it seemed like there were valid cases for either. After some thought, I think there's a simple rule to distinguish them:

A metadata annotation doesn't get a newline after it if and only if:

* It is on a member (method, field, etc.)
* There is only one annotation on that member
* **It does not have a parameter list**

The last one is the new rule. By adding that, we can automatically handle:

```dart
class Foo {
  @override something() { ... }

  @otherAnnotation(arg)
  anotherThing() { ... }
}
```

**Comment by rkj** [comment]
What would happen to things like `@Input()` ?

**Comment by munificent** [comment]
On it's own line. An empty argument list is still an argument list.

Though, after looking around, it seems this rule isn't a good fit for how people tend to format their annotations. There are 10x more cases of a single parameter-less member annotation on its own line than there are with it on the same line as the member.

Given that, I'm considering an even simpler rule: **every annotation always gets it own line.** That's what we do for metadata on directives and declarations, so this just makes members consistent with that.
