### ISSUE TITLE
Line break expressions within 

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dart_style#486]
It would be nice if the formatter would  line break string templates that exceed 80 chars.
E.g. it would be nice if the formatter converted
```dart
return '${clause.name} ${clause.types.map((type) => getTypeName(type)).join(", ")}';
```

to
```dart
return '${clause.name} ${
    clause.types.map((type) => getTypeName(type)).join(", ")}';
```
This is a P2 issue.
Would just be nice if I could assume that the formatter will do something reasonable for these cases instead of leaving > 0 char lines.
Obviously my code was bad and I should feel bad and kept the template shorter.

**Comment by zoechi** [comment]
dup of #226 ?

**Comment by munificent** [comment]
Yeah, closing this out. I'll use this example in the regression suite if I manage to do something about #226, though.
