### ISSUE TITLE
never split class names and its parameterised types

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/dart_style#487]
We were discussing this on slack today, we thought it may be better to never split the class name from its parameterised types. Basically treating it as one unit.

Otherwise you can get confusing things like this:

```dart
void myFunctionWithALongName(
    SomeComplexClassNameThatTakesUpALotOfSpace<WithTypeArgument,
        AndAnotherTypeArgument> argument,
    SomeComplexClassNameThatTakesUpALotOfSpace<WithTypeArgument,
        AndAnotherTypeArgument> argument2,
    SomeComplexClassNameThatTakesUpALotOfSpace<WithTypeArgument,
        AndAnotherTypeArgument> argument3) {}

class AndAnotherTypeArgument {}

class WithTypeArgument {}

class SomeComplexClassNameThatTakesUpALotOfSpace<S, T> {}
```

Thoughts?

**Comment by munificent** [comment]
> we thought it may be better to never split the class name from its parameterised types.

Any time the formatter has a "never split" rule, it means there is code that may end up overflowing the line limit. How would you prefer to format the example you have here?
