### ISSUE TITLE
mandatory newline after a FunctionDeclarationStatement?

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dart_style#488]
Was wondering about enforcing newlines after local functions:
```dart
fn(x) { ... }
items.forEach(fn);
```

**Comment by jmesserly** [comment]
For what it's worth, I tried to implement this by adding a "twoNewlines();" call in visitFunctionDeclarationStatement, but it seemed to have no effect on the test case I added.

**Comment by munificent** [comment]
Fixed by https://github.com/dart-lang/dart_style/commit/8b5aa7e9d090def190d4ae44a21c9d689928935f.
