### ISSUE TITLE
cascading assignments should try to be on different lines

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dart_style#489]
I'm just reviewed the following change, and the formatting makes the code hard to read.
```
longerNamedFoo..items.add(new Foo()
  ..name = bar.toto
  ..placeUrl = place.toString());
```
It looks as if longerNamedFoo gets its `name` and `placeUrl` set, but in reality these go on `new Foo()`.
In this case the longerNameFoo is not used and the first `..items` should become `.items`, but in general it seems less error-prone to have
```
longerNamedFoo
  ..items.add(new Foo()
    ..name = bar.toto
    ..placeUrl = place.toString());
```

**Comment by floitschG** [comment]
In general I think that ".." should be more open to new-lines.
In most cases, they are two statements, that have been combined to reuse the previous receiver.

**Comment by zoechi** [comment]
Dup of #479 ?

**Comment by munificent** [comment]
No, #479 is different. I agree this is pretty bad output (though I think it says a lot more about Dart's lame cascade syntax than it does dartfmt).

It might be possible to do better here, but it will be hard to do so without impacting other code. In the meantime, this is one of those cases where it's probably best to rearrange your code and avoid the nested cascades.
