### ISSUE TITLE
Named parameters with default values format to less readable code

### ISSUE THREAD

**Issue by Sfshaza** [dart-lang/dart_style#490]
I started with this:

```
doStuff({List<int> list: const[1, 2, 3],
         Map<String, String> gifts: const{'first':  'paper',
                                          'second': 'cotton',
                                          'third':  'leather'}})
{
  print('list:  $list');
  print('gifts: $gifts');
}

main() {
  doStuff();

  doStuff(list:[4,5,6]);

  doStuff(list: null,gifts: null);
}
```

And dartfmt gave me this:

```
doStuff(
    {List<int> list: const [1, 2, 3],
    Map<String, String> gifts: const {
      'first': 'paper',
      'second': 'cotton',
      'third': 'leather'
    }}) {
  print('list:  $list');
  print('gifts: $gifts');
}

main() {
  doStuff();

  doStuff(list: [4, 5, 6]);

  doStuff(list: null, gifts: null);
}
```

I contend that this is less readable.

**Comment by munificent** [comment]
In general, dartfmt does not add extra spaces to align elements on previous lines, so it won't produce something like the way `'second': 'cotton',` has a bunch of extra indentation.

The style guide mandates that you don't split before a `{` for a block.

Given those, I think the output is pretty reasonable. I agree the resulting code isn't super readable, but I think that's more to do with putting a large collection literal as a default parameter than it is with formatting. Hoist that out to a named constant and you'll end up with something easier on the eyes, I think.
