### ISSUE TITLE
Variable declaration split

### ISSUE THREAD

**Issue by xavierhainaux** [dart-lang/dart_style#491]
A simple variable declaration

```
String aVariable; // a long long long long long long long long long long long long comment
```
is split in two lines (version 0.2.2)
```
String
    aVariable; // a long long long long long long long long long long long long comment
```

Is this the right behavior? 
Since the line is longer than 80 chars anyway that seems strange.

**Comment by zoechi** [comment]
Line comments stay at the line where they are added and are not broken to multiline comments by design.
There is nothing the formatter could do.

**Comment by xavierhainaux** [comment]
Of course. My question is why split between the type and the name? It wasn't like this on the previous version.

**Comment by munificent** [comment]
> My question is why split between the type and the name?

It's doing it's best to fit that comment in the column limit. Between the type and name is the only place it can split, so it does.

It allows splitting there because it sometimes has to format code with very long types and and names:

```dart
LinkedHashMap<some_prefix.VeryLongClassName, AnotherLongClassName>
    veryLongVariableName;
```
