### ISSUE TITLE
dart-style NPM package defines a `document` global

### ISSUE THREAD

**Issue by alexeagle** [dart-lang/dart_style#493]
angular/ts2dart now depends on dart-style, as of https://github.com/angular/ts2dart/commit/93e4ee565f8c55ff11642c63c5b1c38cde01408d

This breaks angular build because it exposes a global called `document` when the package is imported/require'd. Later, when we try to bundle with systemjs, we hit some code that looks like
```
  if (typeof document != 'undefined') {
    var head;

    var scripts = document.getElementsByTagName('script');
``` which fails because your document object doesn't have all the typical DOM properties.

Failure looks like this:
https://travis-ci.org/angular/angular/jobs/108304309

I'll hack around this for now...

**Comment by munificent** [comment]
cc @jacob314

**Comment by jacob314** [comment]
I'll modify the wrapper boilerplate that lets the dart2js output work on nodejs so that it does not pollute the global scope.

**Comment by alexeagle** [comment]
any update?

**Comment by jacob314** [comment]
Stuck working on the dartium45 roll at the moment. I expect to be done with it and able to get back to the ts2dart work by Monday.

**Comment by vikerman** [comment]
cc @vsavkin

Any updates? This is breaking our release build step for Angular 2 and need a fix for this soon. We had a hacky workaround to undo the global document but that ended up breaking other parts of our build.

**Comment by jacob314** [comment]
Here's a pull request that fixes the issue.

https://github.com/angular/ts2dart/pull/351

**Comment by alexeagle** [comment]
Is dart-style 0.2.7 published on NPM yet?

**Comment by jacob314** [comment]
It is published to NPM.

**Comment by alexeagle** [comment]
Cool, travis is green now. Thank you!
