### ISSUE TITLE
Unfortunate formatting for a list of lists

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart_style#501]
Perhaps very small lists should be handled better?

```
checkLog(log, [
      [
        [1, 42, 123],
        [2, '', "hello"],
        [3, "<msg>", "<msg>"],
        [
          4,
          [],
          [456]
        ]
      ]
    ]);
```

**Comment by munificent** [comment]
Not a bad idea, though I worry that coming up with a good heuristic for "small" will be tricky.

**Comment by skybrian** [comment]
I don't know how this fits with dartfmt's implementation, but it seems like once it's decided that the outer two lists are vertical, it could iterate over the list items and check if each item fits on one line? If so, keep that item horizontal.

**Comment by hterkelsen** [comment]
One thing we're seeing a lot when running dartfmt on our tests is:
Before:
```dart
var a = [[1]];
```

After:
```dart
var a = [
  [1]
];
```

Can the special case of nested single-element lists be handled?

**Comment by munificent** [comment]
> Can the special case of nested single-element lists be handled?

It could, yes. Note, though, that it wouldn't help the original examples @skybrian listed in the bug here.

**Comment by nex3** [comment]
The single-element case has come up in Dart Sass as well. I wrote code like

```dart
if (foo) a = [[1]];
```

and it got reformatted to

```dart
if (foo)
  a = [
    [1]
  ];
```

Even adding brackets to make that fit the style guide again, it's a lot more verbose than the original, and no easier to read.

**Comment by munificent** [comment]
It's been a long time and it doesn't seem like this issue has attracted much attention, so I think we're fairly settled that the current behavior is acceptable.
