### ISSUE TITLE
Unfortunate formatting for a byte array

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart_style#502]
In dart-protoc-plugin's generated_message_test.dart:

  test('testWriteWholeMessage', () {
    List<int> goldenMessage = const <int>[
      0x08,
      0x65,
      0x10,
      0x66,
      0x18,
[...goes on for 500 lines...]

**Comment by munificent** [comment]
See [the FAQ](https://github.com/dart-lang/dart_style/wiki/FAQ#why-does-the-formatter-mess-up-my-collection-literals).
