### ISSUE TITLE
Bad formatting on ternary conditional operator

### ISSUE THREAD

**Issue by lencinhaus** [dart-lang/dart_style#506]
(the actual symbol names were quite longer than the ones in the example)

Output:

```
SomeClass get someField => firstBool &&
    otherBool ? firstExpr : secondExpr;
```

Expected:

```
SomeClass get someField => 
    firstBool && otherBool
    ? firstVar
    : secondVal;
```

**Comment by zoechi** [comment]
Why would you want that? Ternary if is for concise if-then-else expressions. If you don't want it in one line why not use `if`/`else` instead?

**Comment by munificent** [comment]
> (the actual symbol names were quite longer than the ones in the example)

Can you show an example with the actual names, or names of the same length? Identifier length has a big affect on how it chooses to wrap, for obvious reasons.

**Comment by lencinhaus** [comment]
Sorry for the delay.
Here's the original code, including leading space:

<pre>
  Optional&lt;double&gt; get finiteSignificantCost =&gt; isSignificant && cost.value.isFinite ? cost : const Optional<double>.absent();
</pre>

Which gets indented as:

<pre>
  Optional&lt;double&gt; get finiteSignificantCost =&gt; isSignificant &&
      cost.value.isFinite ? cost : const Optional<double>.absent();
</pre>

While I would expect:

<pre>
  Optional&lt;double&gt; get finiteSignificantCost =&gt;
      isSignificant && cost.value.isFinite
      ? cost
      : const Optional<double>.absent();
</pre>

I'm just flagging this because I think I've seen many cases where dartfmt formatted ternary operators in the latter way, and I personally find it way more readable (ofc only if it doesn't fit in one line).

**Comment by munificent** [comment]
The output you're seeing doesn't seem right to me since `&&` has higher precedence than `?:`. I also can't repro this. I get:

```dart
  Optional<double> get finiteSignificantCost =>
      isSignificant && cost.value.isFinite ? cost : const Optional.absent();
```

Which is what I'd expect. Are you sure you're using the latest version?

I'll close this out for now, but I'll reopen if it turns out this is still an issue.

**Comment by lencinhaus** [comment]
My bad, I didn't paste the right snippet. I confirm the one above is formatted as you say, but not the following one (pasting both for comparison):

Original:

<pre>
  Optional&lt;double&gt; get finiteSignificantCost =&gt; isSignificant && cost.value.isFinite ? cost : const Optional&lt;double&gt;.absent();
  Optional&lt;double&gt; get finiteSignificantCost =&gt; isSignificant && cost.value.isFinite ? cost : const Optional.absent();
</pre>

Formatted:

<pre>
  Optional&lt;double&gt; get finiteSignificantCost =&gt; isSignificant &&
      cost.value.isFinite ? cost : const Optional&lt;double&gt;.absent();
  Optional&lt;double&gt; get finiteSignificantCost =&gt;
      isSignificant && cost.value.isFinite ? cost : const Optional.absent();
</pre>

**Comment by munificent** [comment]
Ah, now I can repro it. Yes, it looks like dartfmt is doing the wrong thing here.
