### ISSUE TITLE
bad formatting on long expression

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/dart_style#507]
See here: https://codereview.chromium.org/2007353002/diff/20001/pkg/compiler/lib/src/dart_types.dart

Before:
```dart
        this.containsMethodTypeVariableType =
          returnType.containsMethodTypeVariableType ||
          parameterTypes.any(_typeContainsMethodTypeVariableType) ||
          optionalParameterTypes.any(_typeContainsMethodTypeVariableType) ||
          namedParameterTypes.any(_typeContainsMethodTypeVariableType) {
```

After:
```dart
        this.containsMethodTypeVariableType = returnType
                .containsMethodTypeVariableType ||
            parameterTypes.any(_typeContainsMethodTypeVariableType) ||
            optionalParameterTypes.any(_typeContainsMethodTypeVariableType) ||
            namedParameterTypes.any(_typeContainsMethodTypeVariableType) {
```

I think it was better before, it was clear that there are 4 parallel expressions being ||'ed

**Comment by munificent** [comment]
Yeah, that is a little suboptimal. I think it's because of the weight we attach to `=`. We might be able to tweak this without disrupting other code, but I'm not sure.

**Comment by munificent** [comment]
The opening `{` is a little confusing here. Am I looking at an assignment statement, or something part of a larger expression? If the latter, can you give me the entire statement or member definition?
