### ISSUE TITLE
formatter not happy with comment in argument list (result >80 char lines)

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dart_style#511]
I tried to do this:
```dart
  static const StaticWarningCode FINAL_NOT_INITIALIZED = const StaticWarningCode(
      'FINAL_NOT_INITIALIZED',
      "The final variable '{0}' must be initialized", /*correction:*/ null, /*strongModeError:*/ false);
```
that's from Analyzer, and those two arguments are currently positional optional, so I'm not able to make it named without a breaking change (which is not something done lightly for Analyzer). I wanted to add the comments for clarity on what "null" and "false" means, but formatter blows past the 80 column limit when I do that.

Interestingly, if I add parens around the argument, it does something nicer:
```dart
  static const StaticWarningCode FINAL_NOT_INITIALIZED =
      const StaticWarningCode(
          'FINAL_NOT_INITIALIZED',
          "The final variable '{0}' must be initialized",
          (/*correction:*/ null),
          (/*strongModeError:*/ false));
```

For now I'll probably just remove the comments. But as far as I can tell there's no valid way to add comments in some positions of code, without formatter leaving the code in an invalid (>80 col) state.

**Comment by munificent** [comment]
Yeah, that looks lame. Should be fixable.
