### ISSUE TITLE
Some flutter widget trees are hard to visually scan after dartfmt

### ISSUE THREAD

**Issue by drewwarren** [dart-lang/dart_style#514]
See the dartdoc comments for details. Compared XML :fearful:, the language most layouts are written in today, dart results in trees that are sometimes hard to visually scan.

```
import "package:flutter/material.dart";

/// The `new Padding` inside of the Flexible can easily get skipped when
/// quickly visually parsing the widget tree. A visual scan may result in:
/// -Column
/// --Text
/// --Flexible
/// ---Text
///
/// Opposed to the reality of:
/// -Column
/// --Text
/// --Flexible
/// ---Padding
/// ----Text
Widget smallTreeWithInlineChild() {
  return new Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
    new Text("Hello world"),
    new Flexible(child: new Padding(
        padding: const EdgeInsets.only(top: 8.0, left: 8.0, right: 8.0),
        child: new Text("Nice to meet you.")))
  ]);
}

/// Children being indented less than their parent makes it difficult to visually scan.
class MyWidget {
  Widget childrenIndentedLessThanParent() {
    final theme = new ThemeData();
    return new Padding(
        padding: const EdgeInsets.all(8.0),
        child:
            new Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          new Text("text1", style: theme.textTheme.caption),
          new Text("text2", style: theme.textTheme.body2),
        ]));
  }
}

```

**Comment by munificent** [comment]
Can you give me some more details about what you wish dartfmt had done here instead?

**Comment by drewwarren** [comment]
I can give you an example of output that makes visually parsing the tree easier. The problem is the output has a very different feel that what dartfmt would normally do.

```
import "package:flutter/material.dart";

Widget smallTreeWithInlineChild() {
  return new Column(
    crossAxisAlignment: CrossAxisAlignment.stretch, 
    children: [
      new Text("Hello world"),
      new Flexible(
        child: new Padding(
          padding: const EdgeInsets.only(top: 8.0, left: 8.0, right: 8.0),
          child: new Text("Nice to meet you.")
        )
      )
    ]
  );
}

class MyWidget {
  Widget childrenIndentedLessThanParent() {
    final theme = new ThemeData();
    return new Padding(
      padding: const EdgeInsets.all(8.0),
      child: new Column(
        crossAxisAlignment: CrossAxisAlignment.start, 
        children: [
          new Text("text1", style: theme.textTheme.caption),
          new Text("text2", style: theme.textTheme.body2),
        ]
      )
    );
  }
}

```

I don't actually expect dartfmt to change to this. It is just an example of output I find makes visually parsing the widget tree easier. The issue is that flutter widget trees are structured and read with very different intentions that most other dart code.

Some things I did here that are very different than dartfmt:
- +2 indent on both list children and constructor named parameters.
- Even the Flexible with only 1 named parameter has the parameter on a new line keeping the indentation of the widget tree consistent.
- Not collapsing closing symbols }]) is debatable, but when you are less focused on logic and more focused on layout trees I greatly prefer them. If you keep your nesting low (~3 levels) it's not as necessary.

**Comment by munificent** [comment]
> ```dart
> myFunc(namedParam: complexFunc(
>     complexParam1: "someValue", complexParam2: "anotherValue");
>
> I personally find it very easy to mistake complexParam1 and complexParam2 as being parameters to myFunc opposed to complexFunc.

Yeah, I think you're right here. dartfmt is generally pretty aggressive about forcing a split in outer expressions when inner expressions contain a split. So, in most cases, if an argument splits, the argument list itself will split too.

But there is an exception for single-argument function calls. That's to avoid egregious splitting in code like:

```dart
function(inner(third(
    someReallyLongArgument)));
```

It would be nasty if dartfmt turned this into:

```dart
function(
    inner(
        third(
            someReallyLongArgument)));
```

But it may be that we should limit that exception some ways. At the very least, it would be good to force a split on a named argument list if an inner named argument list splits. But maybe the rule should be that we only apply the above exception for functions with a single *positional* argument.

I'll do some experiments on a corpus and see what looks best.

For the more sweeping changes, yeah, it would be hard to introduce them without causing massive disruption.

**Comment by munificent** [comment]
> ```dart
> myFunc(namedParam: complexFunc(
>     complexParam1: "someValue", complexParam2: "anotherValue");
> ```
>
> I personally find it very easy to mistake complexParam1 and complexParam2 as being parameters to myFunc opposed to complexFunc.

It turns out this example was erroneous. dartfmt currently formats that to:

```dart
myFunc(
    namedParam: complexFunc(
        complexParam1: "someValue", complexParam2: "anotherValue");
```

Which I think is what you want.

As of https://github.com/dart-lang/dart_style/commit/ad69e8a8a31776a33bbcb0cd9bb9c0afeeede09e, dart_style now formats argument lists and collection literals with trailing commas specially. If there is a trailing comma, it always splits and—for argument lists—it formats them more like they are collections with the `)` on the next line.

This is basically necessary because otherwise you end up with `foo(arg,)` and having `,)` defeats the purpose of the trailing comma. Thanks to this, if you add trailing commas to all of the argument lists in your original example, dartfmt will indeed produce the same thing you want:

```dart
Widget smallTreeWithInlineChild() {
  return new Column(
    crossAxisAlignment: CrossAxisAlignment.stretch,
    children: [
      new Text("Hello world"),
      new Flexible(
        child: new Padding(
          padding: const EdgeInsets.only(top: 8.0, left: 8.0, right: 8.0),
          child: new Text("Nice to meet you."),
        ),
      ),
    ],
  );
}

class MyWidget {
  Widget childrenIndentedLessThanParent() {
    final theme = new ThemeData();
    return new Padding(
      padding: const EdgeInsets.all(8.0),
      child: new Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          new Text("text1", style: theme.textTheme.caption),
          new Text("text2", style: theme.textTheme.body2),
        ],
      ),
    );
  }
}
```

Of course, you have to add the trailing commas, which might not be ideal. But it's the best I can come up with without totally changing how other code looks.

I'm going to close this out because I think that covers what you had in mind here, but please do let me know if there are other things you'd like me to look at.

**Comment by drewwarren** [comment]
> It turns out this example was erroneous. dartfmt currently formats that to:
> 
> ```myFunc(
>    namedParam: complexFunc(
>        complexParam1: "someValue", complexParam2: "anotherValue");

I cannot reproduce that with `dartfmt --version` `0.2.4`. My format does keep `namedParam: complexFunc(` on the same line as `myfunc(`

**Comment by drewwarren** [comment]
Thanks for the quick turnaround.

**Comment by munificent** [comment]
Oh, dang. You're right. I could have sworn I tried repro-ing that exact case and it didn't collapse it. Let me take a look.
