### ISSUE TITLE
Strange formatting of anonymous lists with generic parameter.

### ISSUE THREAD

**Issue by dikmax** [dart-lang/dart_style#519]
This one

```dart
    <int>[1, 2, 3, 4].forEach((int value) {
      print(value);
    });
```

get transformed into

```dart
    <
        int>[1, 2, 3, 4].forEach((int value) {
      print(value);
    });
```

I think it looked much better before formatting, and new line after `<` doesn't makes code more readable.

Tested with dartfmt from SDK 1.18.1.

**Comment by munificent** [comment]
Oh, wow. That's horribly broken. I wonder what I did to cause this?!
