### ISSUE TITLE
Braceless 'if' statements with and without 'else' clauses format differently

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dart_style#524]
This is a follow-up to https://github.com/dart-lang/dart_style/issues/448.

This code:
```dart
      if (t == 0.0)
        t = 1.0;
      if (t == 1.0)
        handleEnd();
      else
        handleValue(t);
```

...formats inconsistently. The if statement with an "else" is handled well, but the one before it ends up all on one line:

```dart
  if (t == 0.0) t = 1.0;
  if (t == 1.0)
    handleEnd();
  else
    handleValue(t);
```

**Comment by munificent** [comment]
I understand this is Flutter's style, but moving the body of an `if` to the next line—or allowing it to remain on the next line—directly goes against the style guide that dartfmt implements, so there's not much I can do here.
