### ISSUE TITLE
Compound expressions in return statements format poorly

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dart_style#525]
This flutter code:
```dart
    return config.direction == DismissDirection.horizontal
        || config.direction == DismissDirection.endToStart
        || config.direction == DismissDirection.startToEnd;
```
...becomes less readable when processed by dartfmt:
```dart
    return config.direction == DismissDirection.horizontal ||
        config.direction == DismissDirection.endToStart ||
        config.direction == DismissDirection.startToEnd;
```

It's not as readable as the original but I would also have accepted:
```dart
    return config.direction == DismissDirection.horizontal ||
           config.direction == DismissDirection.endToStart ||
           config.direction == DismissDirection.startToEnd;
```

**Comment by Hixie** [comment]
Here's another example:
Input (and ideal output, IMHO):
```dart
    return a.storage[0] == 1.0 // col 1
        && a.storage[1] == 0.0
        && a.storage[2] == 0.0
        && a.storage[3] == 0.0
        && a.storage[4] == 0.0 // col 2
        && a.storage[5] == 1.0
        && a.storage[6] == 0.0
        && a.storage[7] == 0.0
        && a.storage[8] == 0.0 // col 3
        && a.storage[9] == 0.0
        && a.storage[10] == 1.0
        && a.storage[11] == 0.0
        && a.storage[12] == 0.0 // col 4
        && a.storage[13] == 0.0
        && a.storage[14] == 0.0
        && a.storage[15] == 1.0;
```
Output:
```dart
    return a.storage[0] == 1.0 // col 1
        &&
        a.storage[1] == 0.0 &&
        a.storage[2] == 0.0 &&
        a.storage[3] == 0.0 &&
        a.storage[4] == 0.0 // col 2
        &&
        a.storage[5] == 1.0 &&
        a.storage[6] == 0.0 &&
        a.storage[7] == 0.0 &&
        a.storage[8] == 0.0 // col 3
        &&
        a.storage[9] == 0.0 &&
        a.storage[10] == 1.0 &&
        a.storage[11] == 0.0 &&
        a.storage[12] == 0.0 // col 4
        &&
        a.storage[13] == 0.0 &&
        a.storage[14] == 0.0 &&
        a.storage[15] == 1.0;
```

**Comment by Hixie** [comment]
Another example, this from the Flutter rendering library:

Input:
```dart
    return (minWidth <= size.width) && (size.width <= maxWidth) &&
           (minHeight <= size.height) && (size.height <= maxHeight);
```
Output:
```dart
    return (minWidth <= size.width) &&
        (size.width <= maxWidth) &&
        (minHeight <= size.height) &&
        (size.height <= maxHeight);
```

The original code here is carefully written so that it forms a two-by-two matrix with the vertical columns being minimum and maximum, and the horizontal rows being width and height, with each column having the form "a < b < c". However, the formatter removes all of this and the code ends up much harder to understand at a glance.

**Comment by Hixie** [comment]
To clarify: I care a little about the first here, the second I think we could work around my moving the comments. The third is the most important IMHO. @sethladd suggests that for the third we could hint to the formatter that things should be kept on one line by putting parens around the first two and the last two expressions. That does seem to work, the output is then:
```dart
  return ((minWidth <= size.width) && (size.width <= maxWidth)) &&
      ((minHeight <= size.height) && (size.height <= maxHeight));
```
It would definitely be better if the second line of the return expression was aligned with the first though.

**Comment by Hixie** [comment]
I've filed the indent thing separately in #532. This means that this issue is really only about the first two examples, which basically boil down to noticing that you can put the `&&` or `||` operators in a chain on the left hand side. @abarth likes that style. I think it's cute but could live without it if it's too hard to implement.

**Comment by munificent** [comment]
It's not hard to implement, but it goes against the style guide and the millions of lines of existing Dart code that are already formatted with binary operators on the previous line.

We did discuss changing this a while back, and the consensus on the team at the time was that keeping the operators on the right was better.
