### ISSUE TITLE
Short compound expressions in return statements format poorly

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dart_style#528]
This is similar to https://github.com/dart-lang/dart_style/issues/525 but relates specifically to expressions that would fit on one line but are more readable when split across multiple lines.

This code:
```dart
    return oldWidget.runtimeType == newWidget.runtimeType
        && oldWidget.key == newWidget.key;
```
...turns into the less readable:
```dart
    return oldWidget.runtimeType == newWidget.runtimeType && oldWidget.key == newWidget.key;
```
...because the formatter decides it fits on one line given the provided line length.

Because the expressions are parallel, the code is more readable as originally written with the line break. The line break is significant, and either dartfmt should leave it there, or it should notice that the expression is more readable when split in this way.

**Comment by Hixie** [comment]
Another example where removing the newline hurts:
```dart
    return _c1 * _r1 * math.pow(math.E, _r1 * time) +
           _c2 * _r2 * math.pow(math.E, _r2 * time);
```

The newline here is critical to a clear understanding of the code.

**Comment by Hixie** [comment]
We could add redundant parens around the expressions here, that would reduce this to https://github.com/dart-lang/dart_style/issues/525.

**Comment by munificent** [comment]
This depends on doing vertical alignment (#508).
