### ISSUE TITLE
Formats long int list with one number per line

### ISSUE THREAD

**Issue by silvianacmp** [dart-lang/dart_style#537]
I have a long int list (the bytes used for a file in a test case) and it is formatted to contain one number per line. This leads to having ~ 100 lines of code occupied by the list.
Wouldn't it be better to have it formatted like this:
```
final _bytes = [137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68,
    82, 0, 0, 0, 1, 0, 0, 0, 1, 1, 3, 0, 0, 0, 37, 219, 86, 202, 0, 0, 0, 4,
    103, 65, 77, 65, 0, 0, 177, 143, 11, 252, 97, 5, 0, 0, 0, 3, 80, 76, 84, 69,
    0, 0, 0, 167, 122, 61, 218, 0, 0, 0, 1, 116, 82, 78, 83, 0, 64, 230, 216,
    102, 0, 0, 0, 10, 73, 68, 65, 84, 8, 153, 99, 96, 0, 0, 0, 2, 0, 1, 244,
    113, 100, 166, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130];
```

**Comment by zoechi** [comment]
AFAIK you can force line breaks in list literals by adding `//` at the end of the line

```dart 
final _bytes = [
    137, //
    80, // 
    78, // 
    7, //
     ...
```

**Comment by smanilov** [comment]
+1

**Comment by munificent** [comment]
See here:

https://github.com/dart-lang/dart_style/wiki/FAQ#why-does-the-formatter-mess-up-my-collection-literals

**Comment by silvianacmp** [comment]
Thanks!
