### ISSUE TITLE
Splitting short list literals too much.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/dart_style#539]
Input:
```
main() {
  foo([1], [[1]]);
}
```
Output

```
main() {
  foo([
    1
  ], [
    [1]
  ]);
}
```

I would prefer at least the first list literal to be kept in one line, and possibly the whole expression.

**Comment by munificent** [comment]
This is working as intended. If a collection literal is nested, the outer one always splits. Likewise, if an argument list has a series of collection literals, they either all split, or none of them do.

In practice, we found that this tends to make most code look better, though some cases may end up looking a little funny.
