### ISSUE TITLE
please publish 0.2.10

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart_style#540]
Need the cascading analyzer dependency to be able to be bumped

**Comment by matanlurey** [comment]
+1, difficult to develop against the set of constraints internally due to this.

**Comment by matanlurey** [comment]
In particular I need `0.28.2-alpha.0` or > of `analyzer`, and I can't :(

**Comment by munificent** [comment]
I have one small feature request out for review, then I'll kick out a release. Sorry for the delay!

**Comment by munificent** [comment]
Published 0.2.10 which allows analyzer 0.29.0-alpha.0.
