### ISSUE TITLE
Support a dart_style:check executable for use in presubmit scripts

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart_style#544]
My poor man's approach via a `presubmit.sh` script today:

``` bash
#!/bin/bash

# Make sure dartfmt is run on everything
# This assumes you have dart_style as a dev_dependency
echo "Checking dartfmt..."
NEEDS_DARTFMT="$(find bin lib test -name "*.dart" | xargs pub run dart_style:format -n)"
if [[ ${NEEDS_DARTFMT} != "" ]]
then
  echo "FAILED"
  echo "${NEEDS_DARTFMT}"
  exit 1
fi
echo "PASSED"
```

It would be nice to simplify this for our users, and they could simply add:

``` bash
pub run dartfmt_check
```

(I don't mind contributing this - just want to run it by everyone first)

**Comment by munificent** [comment]
My bash is weak. :(

Is the goal both:

1. Produce a non-zero exit code if there are any formatting changes to make.
2. Don't write any output.

If so, `--set-exit-if-changed` gives you that. If you care about the latter, we could add a `--quiet` flag to suppress output. Would that work?

**Comment by matanlurey** [comment]
Yep, `--set-exit-if-changed` with `--quiet` is likely what we want.

(Though with the script above, you're told what files are missing dartfmt - but in reality that probably isn't a huge deal since users are likely just to re-run dartfmt on all files)

**Comment by munificent** [comment]
> Though with the script above, you're told what files are missing dartfmt

`-n` does that. If you want just a list of the files that would be changed and to have the exit code set, you can do:

```
dartfmt --dry-run --set-exit-if-changed <dir>
```

**Comment by munificent** [comment]
Is there anything I should do here, or does `--dry-run --set-exit-if-changed` give you what you want?

**Comment by matanlurey** [comment]
We can close this!

**Comment by munificent** [comment]
\o/
