### ISSUE TITLE
dart_fmt breaks code with `// ignore: ...` comments at end of line

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart_style#546]
I have generated code like

```dart
import 'package:fhir_client_api/fhir_client_api.dart' show
  FhirDate, // ignore: unused_shown_name
  FhirXhtml, // ignore: unused_shown_name
  PropertyMetadata, ElementDefinitionBindingMeta, ReferenceMeta, // ignore: unused_shown_name
  ClassMetadata
```

after `dartfmt` I get something like

```dart
import 'package:fhir_client_api/fhir_client_api.dart' show
  FhirDate, // ignore: unused_shown_name
  FhirXhtml, // ignore: unused_shown_name
  PropertyMetadata, 
  ElementDefinitionBindingMeta, ReferenceMeta, // ignore: unused_shown_name
  ClassMetadata
```

This shows a warning that `PropertyMetadata` is shown but not used (according to the linter rule `unused_shown_name`)

I think lines with `// ignore: ...` at the end must not be wrapped

**Comment by munificent** [comment]
> I think lines with // ignore: ... at the end must not be wrapped

I don't think we can feasibly do that in the formatter. The decision to split or not may affect many other lines, and the rules encoding those decisions would become magnificently complex if they had to support not splitting on some random subset of lines.

For example, a named argument list either splits before each argument, or before none of them:

```dart
// allowed:
someMethod(one: 1, two: 2, three: 3);
someMethod(
    one: 1,
    two: 2,
    three: 3);

// not allowed:
someMethod(
    one: 1, two: 2,
    three: 3);
```

But if we couldn't split before ignore lines, it would have to handle that, which in turn affects things like the indentation of subexpressions, etc.

A simpler solution is for the user to just copy the `// ignore:` and add it to the new lines if dartfmt splits something up. In your example, those shows *should* be each on one line anyway. That's how the formatter formats them.

**Comment by zoechi** [comment]
It doesn't bother me too much.
Thanks for your explanation.
