### ISSUE TITLE
JSON format has apparently unnecessary "selection" field

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dart_style#547]
When running dartfmt -m, it outputs JSON describing each file. "path" and "source" are simple enough, but "selection" is apparently useless. (Both offset and length are -1.)

Is this a bug? Or if not, maybe the schema should be documented somewhere?

**Comment by munificent** [comment]
It's not used much, but you can pass `--preserve=12:34` to the formatter to tell it the range of the current selection. When you do that, it will track and update the selection through the formatting changes and include the result in the JSON output.

I think analyzer uses this. It's documented in the usage text, but not widely known. Documenting the JSON schema isn't a bad idea. :)

**Comment by skybrian** [comment]
Okay, I did see the preserve option but I didn't understand what it was preserving.

**Comment by munificent** [comment]
Yeah, the name leaves something to be desired. I'm not sure how it ended up named that.

**Comment by munificent** [comment]
This is working as intended.
