### ISSUE TITLE
Using a lambda expression with trailing commas...

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart_style#552]
... returns a less readable manner than not using a lambda.

**What I thought I'd get**

```dart
toJson() => {
  'headers': headers,
  'method': method,
   'url': url,
};
```

**What I actually got**

```dart
toJson() => {
        'headers': headers,
        'method': method,
        'url': url,
      };
```

**What it looks like without a lambda**

```dart
toJson() {
  return {
    'headers': headers,
    'method': method,
    'url': url,
  };
}
```

**Comment by munificent** [comment]
When I try this, I get:

```dart
toJson() => {
      'headers': headers,
      'method': method,
      'url': url,
    };
```

(The map is +4, not +6 as in yours.)

That's what I'd expect to get. I've considered trying to special case `=>` methods that have map/list literal bodies to avoid the extra indentation, but my worry is that it will harm readability. If we indent the map like a block, it's really easy for users to miss the `=>` and think the `{ ... }` is a *block* and not a *map*.

If we make `;` optional (which I hope we do for 2.0), it will make your above example even easier to misread. I'm tempted to give your suggestion a try, but I think it might be best to just stick with what we have.
