### ISSUE TITLE
Using constructor redirects versus `=>` results in different formatting

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart_style#557]
Similar formatting issue as https://github.com/dart-lang/dart_style/issues/548.

With a constructor redirect, nice!

```dart
const factory PublicType.constructor(
  String a,
  Type b,
) = PublicTypeImpl._;
```

With `=>`, sadface

```dart
factory PublicType.constructor(
    String a,
    Type b,
  ) =>
      new PublicTypeImpl._(a, b);
```

**Comment by munificent** [comment]
Ugh, I'm going to spend the rest of my life dealing with corner cases in the interactions between trailing commas and the rest of the language. :(

**Comment by srawlins** [comment]
FWIW I think this is fixed with the new tall style. Changing the examples a bit:

```dart
class PublicType {
  const factory PublicType.constructor1234567890121416182022242628303234363840(
    a,
    b,
  ) = PublicTypeImpl._;

  factory PublicType.constructor1234567890121416182022242628303234363840(
    a,
    b,
  ) => new PublicTypeImpl._(a, b);

  const factory PublicType.constructor(a, b) =
      PublicTypeImpl._1234567890121416182022242628303234363840;

  factory PublicType.constructor(a, b) =>
      new PublicTypeImpl._1234567890121416182022242628303234363840(a, b);
}
```

**Comment by munificent** [comment]
> FWIW I think this is fixed with the new tall style.

Once we're a little closer to shipping, I plan to go through the issue tracker and close out issues that are made irrelevant by the new style. Thanks for starting that work already. :)

**Comment by munificent** [comment]
As @srawlins notes, this is looking good in the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253).
