### ISSUE TITLE
Use a long annotation w/ parameters with trailing commas constructor

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart_style#558]
Apologies for the long issue name. The code will make it more clear, me thinks.

Nice, just using `@required`:

```dart
const factory RouteDefinition.fork(
  String path,
  List<RouteDefinition> children, {
  @required String defaultTo,
}) = ForkedRouteDefinition._;
```

Also works fine with something like `@Required('I told you so, Bob')`.

Less nice, using `@Required(... with a long enough string here...)`:

```dart
const factory RouteDefinition.fork(
  String path,
  List<RouteDefinition> children, {
  @Required('When `path` is navigated to, what path within `children` to use')
      String defaultTo,
//^^<-- What is this doing here?
}) = ForkedRouteDefinition._;
```

**Comment by munificent** [comment]
Ah, yes. In this case, the annotation and the parameter don't all fit on one line.

I had to figure out what to do in this case and there wasn't a lot of hand-formatted prior art in the corpus to go on, so I kind of just picked something that was reasonable to implement.

**Comment by srawlins** [comment]
Are you just expecting fewer spaces, Matan?

**Comment by matanlurey** [comment]
I mean yeah, I'm expecting it to line up nicely :-/

**Comment by srawlins** [comment]
This has been labelled trailing-commas, but it applies without commas as well. The formatter currently outputs code like:

```dart
void reallyLongFunctionName0(
    @Deprecated('This has been deprecated for many interesting reasons...')
        arg1) {
  return;
}

void fn1(
    {@Deprecated('This has been deprecated for many interesting reasons...')
        String argument1}) {
  return;
}
```

**Comment by munificent** [comment]
Thanks for pointing that out, Sam!

**Comment by munificent** [comment]
In the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253), these examples get formatted as:

```dart
class RouteDefinition {
  const factory RouteDefinition.fork(
    String path,
    List<RouteDefinition> children, {
    @Required('When `path` is navigated to, what path within `children` to use')
    String defaultTo,
  }) = ForkedRouteDefinition._;
}
```

And:

```dart
void reallyLongFunctionName0(
  @Deprecated('This has been deprecated for many interesting reasons...')
  arg1,
) {
  return;
}

void fn1({
  @Deprecated('This has been deprecated for many interesting reasons...')
  String argument1,
}) {
  return;
}
```

So I think we're good.
