### ISSUE TITLE
break at the last of the `=` in multi-assignments

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_style#56]
I find multi-assignment expressions interesting: in terms of precedence, they can be expressed as `(a = (b = (c = expr)))`, but in terms of communicating the effect of the expression, I like to read it more as `a = b = c = (expr)` (i.e., all these locations have the same value, the value of `expr`). 

The formatter currently uses the former for breaking long lines, I wonder if we could do the latter and keep as many `=` in the same line as possible.

For example, break this line:
```dart
      _sources[uri] = src = new _MockSdkSource(uri, 'library dart.${uri.path};');
```

as:
```dart
      _sources[uri] = src =
          new _MockSdkSource(uri, 'library dart.${uri.path};');
```

instead of:
```dart
      _sources[uri] =
          src = new _MockSdkSource(uri, 'library dart.${uri.path};');
```

**Comment by munificent** [comment]
On further thought, I think the formatter is doing the right thing here. Grammatically, the expression is structured like:

```dart
_sources[uri] = (src = (new _MockSdkSource(...)));
```

So I think it's good that the line split reflects that.
