### ISSUE TITLE
Implement support for generic function types

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dart_style#563]
This is the formatter issue for https://github.com/dart-lang/sdk/issues/27527.

At the moment we only really need the new syntax in typedefs. Eventually, we want to make this syntax usable for fields and locals, but it's not yet as high a priority. If you find the time to make it work there too, please guard it behind a (different) flag.

**Comment by munificent** [comment]
> If you find the time to make it work there too, please guard it behind a (different) flag.

Generally, for the formatter, I don't put new syntax behind explicit flags. Instead, if you throw an AST at dartfmt that uses the new syntax, it will try to handle it. Since all dartfmt does is rearrange whitespace, I don't think we have to worry too much about compatibility on experimental language features—if a feature is changed or removed, people will stop formatting code that uses it.

**Comment by floitschG** [comment]
That sounds reasonable. I copied this from the other bugs, but I agree that it doesn't really apply to the formatter.

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation, informal spec i linked from the meta-issue https://github.com/dart-lang/sdk/issues/27527

**Comment by munificent** [comment]
Thanks!

**Comment by mit-mit** [comment]
@munificent is this done? If so, was it merged to the sdk?

**Comment by munificent** [comment]
No, this is blocked on analyzer support. dart_style uses analyzer's parser so if there isn't a version of analyzer that parses some syntax, it can't format it. Once https://github.com/dart-lang/sdk/issues/27969 is done, I'll add support to dartfmt.

**Comment by mit-mit** [comment]
OK. Please note that https://github.com/dart-lang/sdk/issues/27969 was punted to 1.23!

**Comment by munificent** [comment]
Good to know, thanks!

**Comment by mit-mit** [comment]
@munificent any news on this?

**Comment by munificent** [comment]
Nope, there won't be any news until analyzer supports it in https://github.com/dart-lang/sdk/issues/27969. dartfmt can't format any syntax that it can't parse. :)

**Comment by mit-mit** [comment]
Analyzer is done!

**Comment by dgrove** [comment]
Bob - any updates? The last full push to trunk is Wednesday early morning.

**Comment by munificent** [comment]
No update yet, I just saw that analyzer support landed (I was out yesterday). I'll take a look as soon as I can.

@bwilkerson, is there a published version of analyzer that supports the new syntax? Are there AST changes?
