### ISSUE TITLE
Notify the user when the formatter is forced to break the style guide

### ISSUE THREAD

**Issue by nex3** [dart-lang/dart_style#564]
It's possible to force the formatter to break the style guide (for example, by writing long string literals or if statement bodies). As an author, it's not always obvious which cases the formatter will be able to format successfully and which will cause it to emit output that's contrary to the style guide. It would be nice if it notified the user in some way when it created output that was invalid so they don't feel obligated to scour their formatted code for style guide failures.

**Comment by munificent** [comment]
We have a really robust linter these days that has support for just about everything that can be mechanically checked from "Effective Dart" and more, so I think that's the right place for these kinds of diagnostics.
