### ISSUE TITLE
Allow undocumented private members to stay close to public members

### ISSUE THREAD

**Issue by nex3** [dart-lang/dart_style#565]
I often write memoized members like this:

```dart
class Foo {
  /// ...
  String get value {
    if (_valueMemo != null) return _valueMemo;
    _valueMemo = expensiveComputation();
    return _valueMemo;
  }
  String _valueMemo;
}
```

The formatter currently forces a newline between the implementation and its memo. I'd prefer it didn't add one if there wasn't one there already; keeping the private member physically close to the public getter helps to communicate that it's an implementation detail of that getter.

**Comment by munificent** [comment]
This is tricky. The formatter has no way of knowing which private fields following members are memoizers and which aren't. Keep in mind that dartfmt is often run on generated code which has no newlines between *any* members.

My feeling is that this use case is a minority one. Even here, the newline doesn't look harmful to me. The field is still adjacent to the member it memoizes, there's just a blank line between the two:

```dart
class Foo {
  /// ...
  String get value {
    if (_valueMemo != null) return _valueMemo;
    _valueMemo = expensiveComputation();
    return _valueMemo;
  }

  String _valueMemo;
}
```

I think the current behavior is OK and probably better than trying to come up with a clever rule to handle these cases which would confuse users when it was applied incorrectly.
