### ISSUE TITLE
scheduled_test descriptor pattern is indented very strangely

### ISSUE THREAD

**Issue by nex3** [dart-lang/dart_style#570]
The formatter doesn't play nicely at all with the following pattern from `scheduled_test`'s `descriptor` library:

```dart
void main() {
  d.file("test.dart", """
    import 'package:test/test.dart';
    
    void main() {
      test("failure", () => throw new TestFailure("oh no"));
    }
  """).create();
}
```

is formatted as:

```dart
void main() {
  d
      .file(
          "test.dart",
          """
    import 'package:test/test.dart';
    
    void main() {
      test("failure", () => throw new TestFailure("oh no"));
    }
  """)
      .create();
}
```

This is definitely a lot harder to read.

**Comment by munificent** [comment]
Yeah, that's pretty nasty.

I think this should be straightforward to fix. When formatting a method chain, it looks inside the argument lists to look for "block-like" things. Those are used to decide when those method calls (here `.file()` and `.create()`) need to be treated like peers that get aligned with each other, or whether they are separated by block-like constructs and can be treated independently.

We should just consider a multi-line string in there to be block-like.
