### ISSUE TITLE
test-style annotations should be allowed

### ISSUE THREAD

**Issue by nex3** [dart-lang/dart_style#571]
The `test` package supports annotations that semantically affect a given library, but syntactically are often attached to the first import so that users don't have to write an otherwise-useless library tag. For example:

```dart
@Timeout(const Duration(minutes: 1))

import "package:test/test.dart";
```

The formatter currently removes any newlines between the annotation and the first import:

```dart
@Timeout(const Duration(minutes: 1))
import "package:test/test.dart";
```

The newline is useful to express "this refers to the library" rather than "this refers to the import".

**Comment by zoechi** [comment]
This looks like a hack (convenient though). Shouldn't that be fixed at the language level?

**Comment by nex3** [comment]
I doubt it's a high enough priority to fix at the language level, especially when this workaround works pretty well.
