### ISSUE TITLE
Support `covariant` marker.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dart_style#572]
This is the formatter issue for https://github.com/dart-lang/sdk/issues/27486.

**Comment by mit-mit** [comment]
@munificent is this one done? And merged?

**Comment by mit-mit** [comment]
Thanks @munificent, do we meed a merge bug to bring this over to the SDK?

**Comment by munificent** [comment]
Done already: https://codereview.chromium.org/2655503003/

That brings it into master. Do I need to file a merge bug to bring it into the dev branch?

**Comment by mit-mit** [comment]
Nope, we will do one last full push. Thanks!
