### ISSUE TITLE
single line if-elses should either be unchanged or should have braces inserted

### ISSUE THREAD

**Issue by leiboldm** [dart-lang/dart_style#578]
For example, dartfmt currently formats these statements like so:

```
// unformatted
if (condition) print('true');
else print('false');

// after formatting
if (condition)
  print('true');
else
  print('false');
```

If you're going to remove the brevity of those two lines by expanding them into four, you might as well follow the style guide which says to use braces:  https://www.dartlang.org/guides/language/effective-dart/style#do-use-curly-braces-for-all-flow-control-structures

**Comment by munificent** [comment]
The formatter only formats your code, it doesn't make other syntax changes required to bring it into compliance with the style guide. For details, [see here](https://github.com/dart-lang/dart_style/wiki/FAQ#why-doesnt-the-formatter-add-curlies-or-otherwise-clean-up-code).
