### ISSUE TITLE
Indent=8 looks very confusing

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/dart_style#579]
```
  Future<File> _writeAsBytes(List<int> bytes,
          {FileMode mode: FileMode.WRITE, bool flush: false}) =>
      delegate.writeAsBytes(bytes, mode: mode, flush: flush).then(wrap);
```

This looks like it's in need of formatting, when it actuality the formatter has just been run on it.

**Comment by tvolkert** [comment]
@Hixie

**Comment by munificent** [comment]
This is working as intended. The +8 is so that you don't inadvertently think the `{FileMode...}` is part of the body of the method.
