### ISSUE TITLE
Newline immediately after `=>` looks wasteful & weird

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/dart_style#580]
e.g.

```
  Future<File> _writeAsBytes(
    List<int> bytes, {
    FileMode mode: FileMode.WRITE,
    bool flush: false,
  }) =>
      delegate.writeAsBytes(bytes, mode: mode, flush: flush).then(wrap);
```

That would look much better as:

```
  Future<File> _writeAsBytes(
    List<int> bytes, {
    FileMode mode: FileMode.WRITE,
    bool flush: false,
  }) => delegate.writeAsBytes(bytes, mode: mode, flush: flush).then(wrap);
```

And in the case of the code block being too long, it's currently:

```
  Future<File> _writeAsString(
    String contents, {
    FileMode mode: FileMode.WRITE,
    Encoding encoding: UTF8,
    bool flush: false,
  }) =>
      delegate
          .writeAsString(contents, mode: mode, encoding: encoding, flush: flush)
          .then(wrap);
```

But again, that wasted line looks wrong. Rather, this is more intuitive:

```
  Future<File> _writeAsString(
    String contents, {
    FileMode mode: FileMode.WRITE,
    Encoding encoding: UTF8,
    bool flush: false,
  }) => delegate
      .writeAsString(contents, mode: mode, encoding: encoding, flush: flush)
      .then(wrap);
```

**Comment by tvolkert** [comment]
@Hixie

**Comment by munificent** [comment]
This looks like an interaction between trailing commas in the parameter list and the `=>` body.
I agree it doesn't look super great.

At the same time, I don't have the resources to implement and test a second set of formatting rules for all of the things affected by trailing commas. The formatter tries to handle them well, but only in a local way.

In this case, I think a simple solution is to use `{}` for the body. If the parameter list is long enough to split across several lines, a braced body is probably easier to read anyway.
