### ISSUE TITLE
Line breaks should favor method chaining for long statements

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/dart_style#581]
This following was formatted by `dartfmt`:

```
          expect(
              events[0],
              invokesMethod('file').on(fs).withPositionalArguments(
                  <String>['/foo']).withResult(isFile));
```

But there's clearly a method chain happening here, and it would be significantly more readable if it were expressed as:

```
          expect(
              events[0],
              invokesMethod('file')
                  .on(fs)
                  .withPositionalArguments(<String>['/foo'])
                  .withResult(isFile));
```

(separate issue is why `events[0]` is put on its own line, but that's lower priority).

**Comment by tvolkert** [comment]
@Hixie

**Comment by munificent** [comment]
Yeah, it would be nice if it recognized the chain better here. I think the problem is the list literal. When you have collection literals in a method chain, it also considers formatting it like:

```dart
method([
  stuff...
].method([
  more stuff...
]);
```

In theory, it can handle both styles, but determining which to choose is difficult for it and there may be some interaction between the two.

**Comment by munificent** [comment]
The [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) handles this better and gives you:

```dart
          expect(
            events[0],
            invokesMethod('file')
                .on(fs)
                .withPositionalArguments(<String>['/foo'])
                .withResult(isFile),
          );
```
