### ISSUE TITLE
redundant newline after `<`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart_style#589]
my top-level method
```dart
List<dynamic> _generateUsedComponentReferences(
    Globals globals, FormComponent component) {
  return component.children == null
      ? <dynamic>[]
      : component.children.map<List<dynamic>>((c) {
          final globalComponent = globals.components.firstWhere(
              (c) => c.id == component.component.componentId,
              orElse: () => null);
          <
              dynamic>[
            reference(globalComponent.className, globalComponent.importPath)
          ]..addAll(_generateUsedComponentReferences(globals, c));
        }).toList();
}
```

Have you considered renaming the GitHub repository to dartfmt?

**Comment by zoechi** [comment]
Actually the code should be `return <dynamic>[ ...` this way `dartfmt` formats it properly for me. 
Feel free to close if you don't want to tackle this case.

**Comment by srawlins** [comment]
probably a dup of #543

**Comment by munificent** [comment]
> Have you considered renaming the GitHub repository to dartfmt?

It's not just the GitHub repo. The pub package itself is called "dart_style" as well. The initial idea was that it would include other style-related tools like the linter in addition to dartfmt, hence the more open-ended name.

At this point, it's probably too much work to rename it.

**Comment by zoechi** [comment]
I see. I was searching for the GitHub repo for dartfmt and only after I failed I remembered that it has a different name. Perhaps a GitHub repo named dartfmt with a readme only pointing to this repo would be enough.
