### ISSUE TITLE
Obfuscates cascade and ternary precedence

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart_style#590]
Take this code:

```dart
void main() {
  print('ternary true:');
  fn(true);

  print('ternary false:');
  fn(false);
}

void fn(bool b) {
  var one = ['one'];
  var list = (b ? one : new List()..add('xxxxxxxxxxxxxxxx'))
    ..add('yyyyyyyyyyyyyyyy');
  print(list);
}
```

Here's the result of running it:

```
$ dart a.dart
ternary true:
[one, xxxxxxxxxxxxxxxx, yyyyyyyyyyyyyyyy]
ternary false:
[xxxxxxxxxxxxxxxx, yyyyyyyyyyyyyyyy]
```

You'd think that `..add('x...')` is applied to `new List()`. It's not. It's applied to the result of `b ? one : new List()`. The formatter however leaves the above text alone, further encouraging your instinct. The second function should maybe be formatted like:

```dart
void fn(bool b) {
  var one = ['one'];
  var list = (b ? one : new List()
        ..add('xxxxxxxxxxxxxxxx'))
    ..add('yyyyyyyyyyyyyyyy');
  print(list);
}
```

or maybe 4 less spaces on the `.add('x...')` line.

This should probably be checked also with another operator that has lower precedence than `?:`, as `..` might not be the only one.

**Comment by munificent** [comment]
I think there's a simple fix: if the receiver of a cascade is a ternary expression, force a split before the `..`.

**Comment by munificent** [comment]
Consider these examples too:

```dart
print(2 * 3..toString()); // 6
print(false && true..toString()); // false
```

Based on that, maybe split if the receiver is any infix expression too.

**Comment by MichaelRFairhurst** [comment]
I wrote more on the expanded cases [here](https://github.com/dart-lang/linter/issues/86), would be nice if they matched behavior (and feel free to correct any errors I made in that comment)
