### ISSUE TITLE
Formatter crashes when parsing = instead of : as a separator for named parameter default values

### ISSUE THREAD

**Issue by micahbeeman-wf** [dart-lang/dart_style#609]
Dart 1.21.0 [introduced](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#1210---2016-12-07) the ability to use `=` as well as `:` as a separator for named parameter default values. E.g.

`enableFlags({bool hidden: false}) { … }`

can now be replaced by

`enableFlags({bool hidden = false}) { … }`

I have a function utilizing this new syntax which causes the formatter to crash:

```
Future click(
      {WaitCallback waitBefore =  _defaultWait,
      WaitCallback waitAfter =  _defaultWait,
      Duration sleepBefore,
      Duration sleepAfter}) async {
    ...
  }
```

Formatter output:

```
Could not format because the source could not be parsed:
line 121, column 32 of lib/src/element.dart: 
The default value of a named parameter should be preceeded by ':'
          {WaitCallback waitBefore =  _defaultWait,
```

I encountered this using latest dart_style (1.0.1), so has this package not been updated to support this new syntax yet?

**Comment by munificent** [comment]
Did you install dart_style yourself? You may need to run pub upgrade on it to get it to pull in the latest version of analyzer.

I'm closing this because it should be possible to get it working, but let me know if you want more help getting it sorted out.

**Comment by micahbeeman-wf** [comment]
I'm using dart_style 1.0.1 and analyzer 0.29.9, both are latest.

**Comment by munificent** [comment]
Interesting. I guess the latest published version of Analyzer doesn't support "=" for named parameters yet. @bwilkerson 

For now, you may have to use the version of dartfmt that ships with the SDK. That uses the latest version of analyzer in the Dart repo which does have support for this. Sorry for the trouble!

**Comment by munificent** [comment]
Fixed now that the latest dart_style uses a new analyzer.

**Comment by micahbeeman-wf** [comment]
Looks like that's in version 1.0.5, is that going to get tagged soon?

**Comment by munificent** [comment]
Yup, I'll kick out a new version today.
