### ISSUE TITLE
Print original file when unable to format code

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/dart_style#612]
I've created an [Emacs mode hook](https://gist.github.com/peter-ahe-google/9d6a6f9b80286aa79c73cf512660e387) that runs `dartfmt` before saving a dart file.

However, if the file contains syntax errors, I end up saving an empty file. For this reason, it would be convenient if `dartfmt` would print the input file in case of errors.

Obviously, I could implement a more robust solution in Emacs, but it does seem convenient.

**Comment by munificent** [comment]
No plans to do this.
