### ISSUE TITLE
Generic callback parameters lose their type parameters

### ISSUE THREAD

**Issue by asgerf** [dart-lang/dart_style#613]
Example:
```dart
// before dartfmt
void takeIdentityFunction(T id<T>(T x)) {}

// after dartfmt
void takeIdentityFunction(T id(T x)) {}
```

If the syntax is not supported yet, it should at least refuse to format it.

**Comment by munificent** [comment]
> If the syntax is not supported yet, it should at least refuse to format it.

There's no automatic way to do that in general. This is just a bug. It should be supported.
