### ISSUE TITLE
Dartfmt not able to parse regress_29243_test.dart

### ISSUE THREAD

**Issue by crelier** [dart-lang/dart_style#616]
regis@belenos:~/dart2/sdk$ git cl upload
Using 50% similarity for rename/copy detection. Override with --similarity.
Running presubmit upload checks ...
Could not format because the source could not be parsed:

line 8, column 39 of tests/language/regress_29243_test.dart: Expected to find ')'.
int Function(int Function()) y = (int Function() x) => x();
                                      ^^^^^^^^
line 8, column 39 of tests/language/regress_29243_test.dart: Expected to find ';'.
int Function(int Function()) y = (int Function() x) => x();
                                      ^
line 8, column 50 of tests/language/regress_29243_test.dart: A function body must be provided.
int Function(int Function()) y = (int Function() x) => x();
                                                 ^
line 8, column 51 of tests/language/regress_29243_test.dart: Expected a method, getter, setter or operator declaration.
int Function(int Function()) y = (int Function() x) => x();
                                                  ^
line 8, column 51 of tests/language/regress_29243_test.dart: Expected a method, getter, setter or operator declaration.
int Function(int Function()) y = (int Function() x) => x();
                                                  ^
line 8, column 51 of tests/language/regress_29243_test.dart: Unexpected text ')'.
int Function(int Function()) y = (int Function() x) => x();
                                                  ^
line 8, column 59 of tests/language/regress_29243_test.dart: A function body must be provided.
int Function(int Function()) y = (int Function() x) => x();
                                                          ^
Done processing /usr/local/google/home/regis/dart2/sdk/runtime/vm/parser.cc

** Presubmit ERRORS **
File output does not match dartfmt.
Fix these issues with:
/usr/local/google/home/regis/dart2/sdk/tools/sdks/linux/dart-sdk/bin/dartfmt -w \
/usr/local/google/home/regis/dart2/sdk/tests/language/regress_29243_test.dart

Presubmit checks took 6.0s to calculate.

Was the presubmit check useful? If not, run "git cl presubmit -v"
to figure out which PRESUBMIT.py was run, then run git blame
on the file to figure out who to ask for help.
regis@belenos:~/dart2/sdk$

**Comment by srawlins** [comment]
I'd for sure love to see what `regress_29243_test.dart` looks like.

**Comment by crelier** [comment]
You can see the line in the bug report, but here is the full test:
```
import "package:expect/expect.dart";
int Function() x = () => 42;
int Function(int Function()) y = (int Function() x) => x();
List<int Function()> l = <int Function()>[()=>42, x];
main() {
  Expect.equals(42, y(l[1]));
}

```
I was finally able to upload the test git cl upload --bypass-hooks
So here you go: https://codereview.chromium.org/2812323002/
