### ISSUE TITLE
Dartfmt loses typedef-type argument

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dart_style#619]
Even after the #614 fix typedef arguments are lost after a `dartfmt`:

Before dartfmt:
``` dart
typedef F<T> = void Function(T);
```

After:
``` dart
typedef F = void Function(T);
```

**Comment by munificent** [comment]
Yeah, #614 is for an unrelated feature -- generic method support in function-typed parameters. This is a bug that I missed in the initial implementation of generic typedefs. :sad:
