### ISSUE TITLE
Unnecessary line breaks in new typedef syntax

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/dart_style#627]
On bleeding edge, this code:

```dart
typedef F = int Function(Null);
```

gets formatted to this:

```dart
typedef F
    = int Function(Null);
```

is this really intended?

**Comment by munificent** [comment]
Definitely not. I can't repro this locally against the latest. Are you sure you're up to date? If so, is there any surrounding code that may affect this?

**Comment by leafpetersen** [comment]
Looks like this is fixed, but not rolled into the sdk repo.  I'll file a bug separately there.
