### ISSUE TITLE
Line break between import namespace and member

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart_style#631]
If a method chain is forced to line-break, dartfmt will also line break between an import namespace and the import member, which I think is visually very confusing. Example:

```dart
import 'i.dart' as i;

void main() {
  foo.bar(i.variable('hey').setSomething('x').setSomethingElse('y').setAnotherThing('z'));
}
```

is formatted as:

```dart
import 'i.dart' as i;

void main() {
  foo.bar(i
      .variable('hey')
      .setSomething('x')
      .setSomethingElse('y')
      .setAnotherThing('z'));
}
```

I like that dartfmt's policy is to keep the first expression on the same line as the `(` (e.g. `foo.bar(i`, but I `i.variable('hey')` should be considered one non-breakable expression in this case. So I want:

```dart
import 'i.dart' as i;

void main() {
  foo.bar(i.variable('hey')
      .setSomething('x')
      .setSomethingElse('y')
      .setAnotherThing('z'));
}
```

**Comment by munificent** [comment]
Unfortunately, dartfmt doesn't know what's an import prefix and what's a variable reference. Consider:

```dart
part of some_lib;

main() {
  i.foo();
}
```

Is `i` an import prefix or a top-level variable in some_lib? There's no way to know without finding, parsing, and analyzing some_lib. dartfmt works on single files, and needs to be able to format a file even if it contains static analysis errors.

That makes it hard to distinguish these cases. We could make some assumptions:

* Only handle library files and not parts.
* Assume import prefixes are never shadowed.

With those assumptions, it's fairly easy to build up a list of the import prefixes for the current file and check for those identifiers when used to the left of a `.`. I'm not sure if those assumptions are reliable enough, but my hunch is that they do cover most cases.

I'll leave this bug open for that, though I have some reservations about this.

**Comment by srawlins** [comment]
Gah parts again. It's like an achilles heal. I think dartfmt should continue to format part files, so feel free to close.

\*shakes fist* parts...

**Comment by munificent** [comment]
/me closes issue as a tear rolls slowly down his cheek.
