### ISSUE TITLE
Drop use of "grinder" and bump args to <2.0.0

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart_style#638]
Otherwise it's impossible to use `args 1.0.0` in some packages.

**Comment by matanlurey** [comment]
I tried to fix this myself, but it's not possible because of `grinder`, which in turn depends on an abandoned package `unscripted`. I'd like to suggest we drop use of `grinder` in this package since `dart_style` is so important and adding this set of transitive dependencies is expensive to maintain.

**Comment by munificent** [comment]
The grinder step is handy because it ensures that the version of dart_style printed by `--version` is the same as the package's actual version. We could get rid of grinder, but I would like some automated script — even a little hand-rolled one — that does what bump and validate do.

**Comment by matanlurey** [comment]
That seems fair, maybe it makes sense to have some sort of shared tool to do this via pub global activate @munificent? /cc @kevmoo and @natebosch

**Comment by natebosch** [comment]
I think we can hand roll something pretty easily. Would be nice to have in pub but probably high effort to payoff compared to other work we could do.

**Comment by munificent** [comment]
> maybe it makes sense to have some sort of shared tool to do this via pub global activate

Uh, isn't that what grinder *is*?

**Comment by natebosch** [comment]
Do we still use grind.dart to publish to npm?
Looks like it's been a while since it was published...

**Comment by munificent** [comment]
@jacob314 is the only one who's published dart_style to npm. I don't consider it part of the regular publish step. He'd know more about that.

**Comment by jacob314** [comment]
It isn't critical to publish. As we aren't actively working on auto-converting TS to Dart files at the moment. Until we can make all the runtimes support converting futures to promises automatically or we support extension methods there isn't much of a point as too many new APIs are using promises.

**Comment by munificent** [comment]
Closing this because I don't think it's blocking any more.
