### ISSUE TITLE
[feature request] auto wrap if-statement

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/dart_style#647]
_From @JFixby on August 8, 2017 10:27_

Example:
```
if (confition) action();
```
or 
```
if (confition)
action();
```

On ```Reformat Code``` should become:
```
if (confition) {
       action();
}
```

With explicit braces it easier to tell what actually belongs in the if block, it saves others from adding the braces later (or creating a bug by forgetting to), and it makes all your if statements uniform instead of some with braces and some without.

No braces is error-prone. For example, let's say you are temporarily commenting out code to debug something:
```
if(condition) 
//      statement;
otherStatement;
```

Or adding code:
```
if(condition) 
    statement;
    otherStatement;
}//some brace that may look like it belongs here but actually is from another statement above the IF
```

_Copied from original issue: dart-lang/sdk#30358_

**Comment by munificent** [comment]
This probably wouldn't end up working out well for the formatter. See [here](https://github.com/dart-lang/dart_style/wiki/FAQ#why-doesnt-the-formatter-add-curlies-or-otherwise-clean-up-code) for some context.

**Comment by JFixby** [comment]
So basically you assume it is a formatter issue and then close it because it is not a formatter issue by design.

**Comment by JFixby** [comment]
Could you please move it back to the https://github.com/dart-lang/sdk/issues/30358

**Comment by munificent** [comment]
I'm not sure who you mean by "you". @anders-sandholm moved the bug here because the feature request is related to the formatter, which is maintained in this repo. I closed the bug because the specific request isn't something we likely want to support in the formatter. There is not another tool in the Dart repo where this feature would make sense.
