### ISSUE TITLE
dartfmt: Support generalized void

### ISSUE THREAD

**Issue by eernstg** [dart-lang/dart_style#649]
This is the dartfmt specific issue for dart-lang/sdk#30176, which has the details.

**Comment by zoechi** [comment]
seems to be a blocker now

**Comment by munificent** [comment]
I just tried this with both the version of dart_style in the Dart SDK (which means using the bleeding edge analyzer) and the external dart_style package using analyzer 0.31.1 and this was formatted fine:

```dart
main() {
  List<void> nothings;
}
```

I still need to add tests but as far as I can tell, it's working. Is there something I'm missing?

**Comment by leafpetersen** [comment]
Re-opening: the following fails to parse and format:

```dart
typedef G2 = void Function([void]);
```

**Comment by munificent** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/34008.

**Comment by natebosch** [comment]
This is working on the given example and the linked SDK issue is resolved.
