### ISSUE TITLE
support formatting code with syntax errors

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart_style#654]
It would be useful to be able to format code even if it had syntax errors. Esp. in the context of Flutter build methods, where when refactoring the nested widgets, it's easy to end up with unmatched parens. I believe the analyzer can generally recover in these situations and create synthetic nodes. The user flow would be something like:

- work on build method
- realize parens are unbalanced (via analysis issues)
- format code
- add missing parens, or fix nesting issues

See https://github.com/flutter/flutter-intellij/issues/1413 for context (though, in that issue, the formatting is done by IntelliJ's internal formatter as a fall-back).

**Comment by munificent** [comment]
Yeah, that workflow makes sense. I've occasionally wished I could do that too. Though, it's probably worth noting that if your parentheses are unbalanced, there's no guarantee that the way dartfmt formats your code will actually correctly tell you *where* they are unbalanced. All it can do is guess and it may guess wrong.

**Comment by devoncarew** [comment]
Totally. Good recovery may help here if the braces are not unbalanced. And if things are really out of wack, the format could fail, or the user can essentially use dartfmt to try and preview what the change might be, and hit undo if it doesn't recover well.

**Comment by zoechi** [comment]
What IntelliJ does should be prevent thought.
After a syntax error it creates a new line for every following token.
In this case it would be better to just not change the formatting.

In IntelliJ:
- Ctrl+Alt+L ("fu..") 
- Ctrl+Z 
- [Do you want to reload from disk] ("don't ask stupid questions Grrr!") 
- click yes
- ("phew, back to sane state")

**Comment by devoncarew** [comment]
> In this case it would be better to just not change the formatting

Yup, I agree here. /cc'ing @alexander-doroshko. In the past we've been looking to improve the error recovery of IntelliJ's Dart parser, but we may want a solution that handles more cases; I opened https://youtrack.jetbrains.com/issue/WEB-31074 to track.

**Comment by munificent** [comment]
I'm going to close this because I think it's unlikely that we'll be able to define "erroneous but good enough to format" well enough to rely on it in the formatter.
