### ISSUE TITLE
Linewrap comments

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dart_style#656]
It would be nice if dartfmt could automatically line-wrap comments in Dart code. This need not be especially clever; just wrapping at spaces is sufficient to handle the kinds of comments seen in the Dart core libs and in Flutter's framework.

**Comment by munificent** [comment]
I've hesitated to do this because I think it's a rathole in terms of what kind of behavior users expect it to have. I agree it would be really useful, but it might need to be behind an opt-in flag since there's a real chance it would make surprising, incorrect changes.

**Comment by munificent** [comment]
De-duping some issues that are similar enough that I think it makes sense to track them as one: #655.
