### ISSUE TITLE
Crashes upon seeing "covariant void"...

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart_style#659]
which is supported AFAICT in the analyzer/DDC/Dart2JS/VM.

This came up when trying to migrate off `@checked`:

https://github.com/dart-lang/angular/blob/1f44a6625d077d221bdaff4b0d12809c08108a60/angular/lib/src/platform/dom/events/dom_events.dart#L9-L23

In this case, changing `@checked` on line 14 to `covariant` causes dartfmt to crash.

I was able to temporarily work around by dropping `void`.

**Comment by munificent** [comment]
The underlying error is coming from the parser in the analyzer package that dart_style depends on:

```
  Could not format because the source could not be parsed:

  line 14, column 15: Expected to find ','.
      covariant void callback(Event event),
                ^^^^
```

It looks like latest public stable version of the analyzer package, 0.30.0, doesn't parse this syntax. The alpha version does. So the version of dart_style that ships in the SDK, which uses the bleeding edge analyzer package also in the SDK is probably fine. But if you're using dart_style yourself externally, you'll get an older analyzer with this problem.

I'm not sure if the analyzer folks are planning to push out any more stable releases before 2.0, so this may need to wait until dart_style is on the new kernel front end.

**Comment by matanlurey** [comment]
Then maybe the dartfmt internally is old

**Comment by munificent** [comment]
I can't repro this internally, so as far as I can tell, dartfmt has a version of analyzer now that's fixing this.
