### ISSUE TITLE
Warn if dartfmt wasn't able to fully follow the style guide

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart_style#667]
The code:
```dart
if (start == null || start == null || start >= this.length) start = this.length - 1;
```
(which was apparently slightly too long, and also stupid, so good catch) was reformatted to
```
if (start == null || start == null || start >= this.length)
    start = this.length - 1;
```
which is a multi-line if without braces. That's replacing one wrongness with another, without giving any warning.

Would it make sense to at least print a warning in this case?

**Comment by munificent** [comment]
Yeah, I think it should notify the user in some way if it fails to produce output that fully satisfies its goals. A similar case is when you have a string literal that doesn't fit in the line length.

**Comment by srawlins** [comment]
Duplicate of #564 ?

**Comment by munificent** [comment]
Oops, yes!
