### ISSUE TITLE
Multi-line method call nested inside constructor call has unnecessary extra indent

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/dart_style#679]
I wrote the following _beautiful_ code:

```dart
class UnitConverterApp extends StatelessWidget {
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        textTheme: Theme.of(context).textTheme.apply(
          bodyColor: Colors.black,
          displayColor: Colors.grey[600],  // <-- carefully placing a trailing comma here
        ),  // <-- and here
      ),
    );
  }
}
```

Then dartfmt made it less beautiful:

```dart
class UnitConverterApp extends StatelessWidget {
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        textTheme: Theme.of(context).textTheme.apply(
              bodyColor: Colors.black,
              displayColor: Colors.grey[600],
            ),
//      ^^^^ :/
      ),
    );
  }
}
```

(disclaimer: I actually didn't write that code; someone else did; but had _I_ written that code, dartfmt would still format it the same way 😉)

**Comment by munificent** [comment]
Yet another case where trailing commas interact poorly with other formatting rules. :(

**Comment by munificent** [comment]
The [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) does exactly what you want here and preserves the original formatting. In fact, you don't even have to be careful about the trailing commas because it does that for you too.
