### ISSUE TITLE
dartfmt should not prefer empty bodies in the if part of if...else...

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/dart_style#680]
While I was refactoring some stuff I came up with this code:
```dart
    if (receiver != null &&
        receiver is! ThisExpression &&
        interfaceMember is Procedure &&
        interfaceMember.isGenericContravariant) {
    } else if (identical(interfaceMember, 'call')) {
    } else if (interfaceMember == null) {
    } else if (interfaceMember is Procedure &&
        interfaceMember.isGenericContravariant) {
      return MethodContravarianceCheckKind.checkMethodReturn;
    }
```
The formatter seems to have an unhealthy desire to keep the empty bodies all on the same line even in the presence of the `else`s, so it gave me:
```dart
    if (receiver != null &&
        receiver is! ThisExpression &&
        interfaceMember is Procedure &&
        interfaceMember
            .isGenericContravariant) {} else if (identical(interfaceMember,
        'call')) {} else if (interfaceMember == null) {} else if (interfaceMember
            is Procedure &&
        interfaceMember.isGenericContravariant) {
      return MethodContravarianceCheckKind.checkMethodReturn;
    }
```
Subjectively, this does not seem like an improvement.

**Comment by munificent** [comment]
I agree the resulting output is pretty bad, but the input also looks alarming to me. As series of empty then bodies is a strange idiom. If I was reading that code, I would wonder why the cases aren't all combined into one. Did the author forget to put code in the bodies? What do all of these condition expressions *mean?*

I can make dartfmt handle this code better, but I don't know if it helps overall readability to encourage this pattern.

If I were reviewing this code, I would suggest that you define a helper function with a good name to explain what the code is doing:

```dart
bool whateverItIsThoseConditionsMean(receiver, interfaceMember) {
   if (receiver != null &&
        receiver is! ThisExpression &&
        interfaceMember is Procedure &&
        interfaceMember.isGenericContravariant) {
      return false;
    }

    if (identical(interfaceMember, 'call')) return false;
    if (interfaceMember == null) return false;

    return true;
}

mainThing() {
    if (whateverItIsThoseConditionsMean() &&
        interfaceMember is Procedure &&
        interfaceMember.isGenericContravariant) {
      return MethodContravarianceCheckKind.checkMethodReturn;
    }
}
```

(Also, until writing this suggested code, I didn't realize there were *three* states this code cares about — all of the empty body states, the non-empty if state, and the case where all of the conditions are false.)

Barring that, I would at least suggest putting comments in the empty bodies like `// Do nothing.`` to make it clear that's what the intent is. If you do that, dartfmt will also format it like you want.

But I'll go ahead and leave this bug open and try to get dartfmt to not go wacky if you do choose to use this pattern.

**Comment by srawlins** [comment]
Side suggestion for @kmillikin to get formatting nicer today: I've had times where I want to write `if ((strangely && arranged) || condition) {} else { doThings(); }` because it's easier for a human to read than `if (!((strangely && arranged) || condition)) { doThings(); }`, but in these cases a comment is warranted I think. A second benefit, dartfmt leaves the newlines alone when you comment each empty block:

```dart
  if (receiver != null &&
      receiver is! ThisExpression &&
      interfaceMember is Procedure &&
      interfaceMember.isGenericContravariant) {
    /* comment */
  } else if (identical(interfaceMember, 'call')) {
    /* comment */
  } else if (interfaceMember == null) {
    /* comment */
  } else if (interfaceMember is Procedure &&
      interfaceMember.isGenericContravariant) {
    return MethodContravarianceCheckKind.checkMethodReturn;
  }
```

**Comment by munificent** [comment]
Sorry, I read "I came up with this code" to mean "this is the code I wanted to have", not "this is code that was still being changed". Your observation that dartfmt needs to gracefully handle code that's still in flux is a good one.

I did leave this issue open and intend to fix it.

**Comment by kmillikin** [comment]
Thanks!
