### ISSUE TITLE
Long ternary bodies formatted poorly

### ISSUE THREAD

**Issue by alanrussian** [dart-lang/dart_style#705]
Example (as formatted by dartfmt):

```
final _appUrl = Platform.isIOS
    ? 'https://itunes.apple.com/us/app/google-adwords/id1037457231'
    : 'https://play.google.com/store/apps/details?id=com.google.android.apps.'
    'adwords';
```

I would expect this to be formatted as:

```
final _appUrl = Platform.isIOS
    ? 'https://itunes.apple.com/us/app/google-adwords/id1037457231'
    : 'https://play.google.com/store/apps/details?id=com.google.android.apps.'
          'adwords';
```

**Comment by munificent** [comment]
Ah, interesting. I think this is an interaction between adjacent strings (which are generally tricky to format) and the conditional operator. I agree that your expected output is what I'd want to see here too.

**Comment by munificent** [comment]
With some later changes to adjacent string handling, you now get:

```dart
final _appUrl = Platform.isIOS
    ? 'https://itunes.apple.com/us/app/google-adwords/id1037457231'
    : 'https://play.google.com/store/apps/details?id=com.google.android.apps.'
        'adwords';
```

That's not *exactly* what you wanted, but I think it works well and makes sense. It's +4 relative to the beginning of the `:`.
