### ISSUE TITLE
dartfmt --fix doesn't remove `new` from string interpolation expression

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart_style#707]
_From @chalin on June 26, 2018 18:58_

`dartfmt --fix` is a wonderful feature!

Note that it currently fails to remove `new` from the following string interpolation expression:

```dart
    sink.write('FILE ACCESSED ${new DateTime.now()}\n');
```

cc @munificent @kwalrath 

_Copied from original issue: dart-lang/sdk#33635_

**Comment by munificent** [comment]
Aww, dang. That's right. Dartfmt doesn't currently do anything to interpolated expressions (#226). I didn't consider that that means that `--fix` won't either. It really should.

**Comment by chalin** [comment]
I suspect that `new` and `const` don't appear very often in interpolated expressions (I found only one such case in the site-www examples).
