### ISSUE TITLE
Nested conditional operators become hard to read

### ISSUE THREAD

**Issue by michaelspiss** [dart-lang/dart_style#713]
When using nested conditional operators, dart format applies a rule that makes sense for a single, but not multiple operators.

Example:
```
String type = status == 'OK'  ? 'notices'
            : status == 'NO'  ? 'warnings'
            : status == 'BAD' ? 'errors'
            : '';   
```
becomes:
```
String type = status == 'OK'
    ? 'notices'
    : status == 'NO' ? 'warnings' : status == 'BAD' ? 'errors' : '';
```

**Comment by munificent** [comment]
It doesn't produce the exact formatting you suggest here because dartfmt doesn't generally hang conditionals at the end of lines. But as of #1012, it now chains the cases directly, so I think this is probably where it will stay.

**Comment by munificent** [comment]
Re-opening this because I'm going to undo the change. I got enough pushback from users that it's not clear that this is a change for the better. At the very least, I don't want it to go out in Dart 2.13 before we've had more time to evaluate it.

**Comment by michaelspiss** [comment]
I would like to give some feedback regarding issue #1012: The problem I had when opening this issue, was the way the formatter made a sort-of readable piece of code into a one-lined mess that even I, the author, had trouble understanding.
The example above shows how I tend to write my code for simple nested conditionals:
"if ... then ...
or ... if ... then ...
or ... if ... then ...
or ..."
In my opinion this is easy to read (for short conditionals!) as line breaks appear where I would pause in spoken english as well.

If
```dart
String type = status == 'OK'
      ? 'notices'
      : status == 'NO'
        ? 'warnings'
        : status == 'BAD'
          ? 'errors'
          : '';

```
is what the formatter currently produces, I prefer it to #1012. It is close enough to my proposal and stays readable no matter how long the conditionals are.
#1012 removes indention completely, which makes those nested conditionals extremely hard to read, as ?/: are not easily distinguishable when skimming the lines. Additionally I would close this issue, as the code above is very readable and no longer produces a single line output.

**Comment by munificent** [comment]
Right now, the formatter gives you:

```dart
String type = status == 'OK'
    ? 'notices'
    : status == 'NO'
        ? 'warnings'
        : status == 'BAD'
            ? 'errors'
            : '';
```

I'll close this issue. Thank you for the feedback!
