### ISSUE TITLE
dartfmt should have an option to run silently

### ISSUE THREAD

**Issue by abarth** [dart-lang/dart_style#715]
We're running dartfmt as part of a complex build system.  Generally, we prefer that steps in the build do not produce any output when they succeed because we have tens of thousands of steps in the build and they mostly all succeed.

Currently, dartfmt produces output even upon success:

```
$ dartfmt -w foo.dart 
Formatted foo.dart
$ dartfmt -w foo.dart 
Unchanged foo.dart
```

That might be a good default behavior, but we'd like an option to be able to suppress output in non-failure scenarios:

```
$ dartfmt -q -w foo.dart 
$ dartfmt -q -w foo.dart 
```

We'd still like output upon failure to help diagnose why the build is failing:

```
$ dartfmt -q -w garbage
Could not format because the source could not be parsed:
[...]
```

@munificent

**Comment by munificent** [comment]
The new `dart format` command has a revised CLI that now supports completely quiet output if you want:

```sh
dart format --show none --summary none <paths...>
```

**Comment by abarth** [comment]
Thanks!
