### ISSUE TITLE
Drop `const` inside library annotations with --fix

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dart_style#720]
This will give better alignment with the `unnecessary_const` lint.

**Comment by munificent** [comment]
It [should already be doing that](https://github.com/dart-lang/dart_style/blob/master/test/fixes/optional_const.unit#L89-L92). Do you have a case where it isn't?

**Comment by natebosch** [comment]
looks like it's only a problem when the annotation is on the library directive, or before the first import if there is no library directive.
