### ISSUE TITLE
Ternary preference

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/dart_style#722]
My preference for chained ternaries

```dart
child: 
    project.locked ? Icon(Icons.lock)
  : project.fav ? Icon(Icons.star)
  : project.taps == null ? Icon(Icons.notifications)
  : Text(
      suffixNumber(project.taps),
      textAlign: TextAlign.center,
      style: TextStyle(
        fontSize: 18.0, 
        fontWeight: FontWeight.w600,
      ),
    ),
```

`dartfmt` preference
```dart
child: project.locked
    ? Icon(Icons.lock)
    : project.fav
        ? Icon(Icons.star)
        : project.taps == null
            ? Icon(Icons.notifications)
            : Text(
                suffixNumber(project.taps),
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 18.0,
                  fontWeight: FontWeight.w600,
                ),
              ),
```

Is there a reason why the second format has been selected? Is there any room for discussion to adopt the aforementioned style?

**Comment by munificent** [comment]
There's no particular reason for the current formatting. Chained conditionals are rare so when I was tweaking the rules, I don't think I ran into many cases to make me think about it.

Your preferred style is looks reasonable to me, though I don't know if it would interfere with other formatting rules. How would you format:

```dart
child: 
    project.locked ? Icon(Icons.lock)
  : project.fav.nowThisConditionIsTooLong + toFitInOneLineSoYouHaveToWrap ? Icon(Icons.star)
  : project.taps == null ? Icon(Icons.notifications).nowThisThenIsTooLong + toFitInOneLineSoYouHaveToWrap
  : Text(
      suffixNumber(project.taps),
      textAlign: TextAlign.center,
      style: TextStyle(
        fontSize: 18.0, 
        fontWeight: FontWeight.w600,
      ),
    ),
```

?

**Comment by lukepighetti** [comment]
I'll take a stab at it, but I have never run into that problem with flutter since I usually keep all work outside of the templating literals

```dart
child: 
    project.locked ? Icon(Icons.lock)
  : project.fav.nowThisConditionIsTooLong + toFitInOneLineSoYouHaveToWrap ? 
    Icon(Icons.star)
  : project.taps == null ? 
    Icon(Icons.notifications).nowThisThenIsTooLong + toFitInOneLineSoYouHaveToWrap
  : Text(
      suffixNumber(project.taps),
      textAlign: TextAlign.center,
      style: TextStyle(
        fontSize: 18.0, 
        fontWeight: FontWeight.w600,
      ),
    ),
```

**Comment by lukepighetti** [comment]
Also I might add that dartfmt rules may be flexed by the upcoming horde of Flutter users, especially those moving from React Native. I'm sure you're already aware of this, but the community might have a new set of requirements that didn't exist before Flutter became production ready... just a thought...

**Comment by lukepighetti** [comment]
Also, I will concede that a lot of people would yell at me for not using a switch here. :D

**Comment by srawlins** [comment]
If this makes it into a round up of formatting changes, I'll just comment that https://github.com/dart-lang/dart_style/issues/705 and https://github.com/dart-lang/dart_style/issues/713 are both similar, dealing with the ternary conditional.

**Comment by munificent** [comment]
Re-opening this because I'm going to undo the change. I got enough pushback from users that it's not clear that this is a change for the better. At the very least, I don't want it to go out in Dart 2.13 before we've had more time to evaluate it.

**Comment by lukepighetti** [comment]
Yeah, if I'm being totally honest when I saw activity on this I was going to say I don't think it's a good idea anymore, but then I saw it was already merged.

**Comment by lukepighetti** [comment]
Bob, I'm going to close this. I don't think the style change is a good idea. Perhaps this is more a discussion of using switch clauses outside of a block, or potentially a future when clause.

**Comment by SirusCodes** [comment]
@lukepighetti I honestly feel that this format is more readable and better to look. But I would like to what others think.

**Comment by lukepighetti** [comment]
I think at this point the cost of breaking what people are used to is higher than the subjective gains in readability. Personally I think this issue should be closed and a new one opened for control flow outside of blocks/collections.


```dart
child: 
  if(project.locked) Icon(Icons.lock)
  else if (project.fav) Icon(Icons.star)
  else if (project.taps == null) Icon(Icons.notifications)
  else
    Text(
      suffixNumber(project.taps),
      textAlign: TextAlign.center,
      style: TextStyle(
        fontSize: 18.0, 
        fontWeight: FontWeight.w600,
      ),
    ),

```
