### ISSUE TITLE
If statement with operator strageness

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart_style#728]
```dart
void main() {
  dynamic element;
  if (element is MethodElement) {
    if (element.parameters
            .where((p) => p.isPositional && !p.isOptional)
            .length >
        1) {
    // ^^^^^^^^^^^^ What?
    }
  }
}
```

**Comment by munificent** [comment]
This is working as intended. The `1)` is indented +4 to ensure it's farther than the body of the if. The `.where()` and `.length` are indented to show that they are subexpressions of the left operand of the `<`.

**Comment by srawlins** [comment]
Er, I think @matanlurey's issue was not with the indentation, but the line split that puts `1) {` on its own line. I would expect:

```dart
//  5   10   15   20   25   30   35   40   45   50   55   60   65   70   75   80
void main() {
  dynamic element;
  if (element is MethodElement) {
    if (element.parameters
        .where((p) => p.isPositional && !p.isOptional)
        .length > 1) {
    }
  }
}

/// Or...
void main() {
  dynamic element;
  if (element is MethodElement) {
    if (element.parameters
        .where((p) => p.isPositional && !p.isOptional).length > 1) {
    }
  }
}
```

Maybe the rules of splitting method chains are confusing me on how the outer relation expression gets handled...

**Comment by matanlurey** [comment]
Yes, that was my intention. Thanks @srawlins!

**Comment by munificent** [comment]
That looks sort of nice in this example, but it's hard to generalize from that. It's important to keep in mind that the left operand to that `>` is not `length`, it's the entire `element.parameters.where((p) => p.isPositional && !p.isOptional).length` expression. Allowing the `>` to fit on the same line when its operand takes three lines can lead people to believe that `>` has higher precedence than it does.

Consider this similar example:

```
void main() {
  dynamic element;
  if (element is MethodElement) {
    if (element.parameters +
        where((p) => p.isPositional && !p.isOptional) +
        length > 1) {
    }
  }
}
```

This makes it look like the `>` binds tighter than `+`. We could maybe special-case method chains while forcing the above example to split, but having special formatting rules for each *pair* of precedence levels is a road to madness.

Another example of how keeping the `>` on the same line doesn't scale is:

```dart
void main() {
  dynamic element;
  if (element is MethodElement) {
    if (element.parameters
        .where((p) => p.isPositional && !p.isOptional)
        .length > someOtherThing.findStuff().anotherMethod().aThird().maximumAllowedLength) {
    }
  }
}
```

How would you break that right operand? It's hard to find a good answer that doesn't involve splitting on the `>`. If you're going to do that when the right operand is long, it's consistent to do so when the left operand is too.

```dart
/// Or...
void main() {
  dynamic element;
  if (element is MethodElement) {
    if (element.parameters
        .where((p) => p.isPositional && !p.isOptional).length > 1) {
    }
  }
}
```

That doesn't look too bad, but it also violates a general rule that it prefers to split at looser precedence levels. The `.where()` call is higher precedence than `>`, so splitting on the former can mislead the reader into thinking it has lower precedence.

**Comment by srawlins** [comment]
Thanks for the explanation!
