### ISSUE TITLE
roll a new version of dart_style into the SDK

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dart_style#729]
We'll need to roll a new version of dart_style into the sdk repo in order to capture the updates to account for the analyzer parser --> fasta change. We have a long line of dependencies queued up behind the parser change (analyzer CFE integration, super-mixins support, ...), so would love for the dart_style roll to happen soon. That will unblock the analyzer switching its default parser.

I see from https://github.com/dart-lang/sdk/blob/master/DEPS#L69 that a dart_style roll is more involved than a typical package roll. @munificent, do you mind taking on the roll?

/cc @danrubel, @JekCharlsonYu

**Comment by leafpetersen** [comment]
@munificent is out this week.  @whesse @athomas should be able to help with rolling the infrastructure part.  It's not 100% clear to me that this needs to happen simultaneously though.  Do we expect changes in the way that code formats?  If not, then I don't *think* version skew matters.

**Comment by devoncarew** [comment]
> @munificent is out this week

Ah, thanks for the heads up.

> Do we expect changes in the way that code formats? 

I don't know, but with Bob out, we likely can't publish a new version of dart_style. We can try to reference a specific commit in the sdk DEPs file, and / or disable the failing dart_style tests via status file updates.

**Comment by leafpetersen** [comment]
@kevmoo probably has the keys to publish if we need to.  But referencing with a hash is fine in DEPS.

**Comment by athomas** [comment]
For the SDK part: first step would be to prepare the CL with the version bump.

Then we land the change, include in a dev release and then bump the checked-in SDK version to that dev release. That's the usual process. If you prepare the CL today (but don't land it, I will do that), I can do the rest tomorrow or Thursday.

**Comment by devoncarew** [comment]
For posterity, we'd want all the commits up to and including 6f3efd209ff1828835936397b64be79265cc0c19 .

**Comment by devoncarew** [comment]
https://dart-review.googlesource.com/c/sdk/+/70940, to see the impact

**Comment by kevmoo** [comment]
Are there are functional changes to dart_style? Or is this just plumbing changes?

**Comment by devoncarew** [comment]
> Are there are functional changes to dart_style

I don't know what's in the last set of commits since the previous roll. For the purposes of switching the default parser, we need to capture 3 recent fixes from @danrubel.

**Comment by athomas** [comment]
Done.
