### ISSUE TITLE
Fix to convert from /** */ comments to ///

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart_style#730]
Since `///` comments is the style-guide recommendation for doc-comments, maybe add a fix to convert `/** */`-style doc-comments to `///`-style.

It's not absolutely trivial since `///` allows one less character per line, so converting existing documentation will end up with 81 character lines. The fix might need to print a notice with file and line-number for each line that is now too long, so the user can go back and fix that.

Maybe it's not really necessary because everybody already switched to `///` (and I'll just go back to my Perl script).

**Comment by srawlins** [comment]
Where's the darn +20 button on this thing? 😁 +💯 

Unless its a lot of effort, and a perl script exists. I think at this point its huge and stable-so-not-frequently-maintained packages that still use `/** */`. Would you mind posting your perl script, @lrhn if its short? 😁

**Comment by lrhn** [comment]
The script is ... primitive, and a valid entry in the "looking most like random line noise" category. (I never claimed I was *good* at Perl).
Definitely a "use at your own risk" thing. 
```perl
#! /usr/bin/perl -i -p                                                              
my $orig = $_;
s"/\*\*((?:(?!\s*\*/)\s*.)*?)\s*\*/\s*\n"///\1\n";
s"^\s*/\*\*\s*\n"";
s"^\s*\*/\s*\n"";
s"^(\s*) \*([^\n]*)"\1///\2";
s"\[:(.*?):\]"\`\1\`"g;
s"\s+$"\n";
if ($orig ne $_ && length($_) > 81) {
  my $ln = length($_) - 1;
  print STDERR "LONG LINE:$ARGV($ln): $_"
}
```
It still somehow seems to work for all the SDK library files.

**Comment by munificent** [comment]
Yeah, now that we have `--fix`, I think this is a great idea.

I'm not too worried about the lines getting a character longer. dart_style already does not wrap long comments so you can get into that situation today. #667 would help for this case too.

**Comment by zoechi** [comment]
http://dart-lang.github.io/linter/lints/lines_longer_than_80_chars.html might also help to fix longer lines

**Comment by munificent** [comment]
Fixed by @a14n in https://github.com/dart-lang/dart_style/commit/623ff9122b8023332a776dd157a12a1464ea002e. (Sorry, I accidentally squashed your commit when I merged my changes in.)
