### ISSUE TITLE
Unsplit list literal in method chain formats poorly

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/dart_style#731]
Whe using fluent function calls the results of dartfmt isn't optimal Especially when using RxDart this produces real ugly results like:

```Dart
    filterUpdateSubscription = sl
        .get<EventManager>()
        .updateFilterCommand
        .results
        .mergeWith([sl.get<PlaceManager>().updateFilterCommand.results]).listen(
            (filterState) async {
      AppKeys.mapView?.currentState?.activateMapOverlay();
      await Future.delayed(Duration(milliseconds: 100));
      setState(() {
        filterIsActive = filterState;
      });
    });
```

Where this

```Dart
    filterUpdateSubscription = sl.get<EventManager>().updateFilterCommand
        .results
          .mergeWith([sl.get<PlaceManager>().updateFilterCommand.results])
            .listen( (filterState) async {
                AppKeys.mapView?.currentState?.activateMapOverlay();
                await Future.delayed(Duration(milliseconds: 100));
                setState(() {
                  filterIsActive = filterState;
                });
              });
```

Would be much easier to read.

I know that dartfmt has the goal of making all dart code look the same but if this works against readability of the intent it's not a good philosophy.

I would propose a simple option to be able to tell dartfmt to not touch lines beginning with a '.'

**Comment by escamoteur** [comment]
Perhaps this could be an option? https://github.com/dart-lang/dart_style/issues/731

**Comment by zoechi** [comment]
For fluent-like use `..` should be used anyway.

**Comment by sir-boformer** [comment]
I actually prefer the first format where every `.` line starts with the same indentation.

**Comment by escamoteur** [comment]
I could live with the same indentation but look where it put the `.listen()` also directly making a line-break after the `sl` is not what is intended the first method call returns the value on that is the start of the execution pipeline.

**Comment by srawlins** [comment]
I do find it puzzling to see that `.listen(` not on its own line... I think there is a dartfmt "bug" here with the list literal, @munificent. If we pull the list literal out into a variable (even a crazy one whos name is the same length as the literal), the formatting gets all better:

```dart
var placeManagerUpdateResults___________________________ = [
  sl.get<PlaceManager>().updateFilterCommand.results
];

var filterUpdateSubscription = sl
    .get<EventManager>()
    .updateFilterCommand
    .results
    .mergeWith(placeManagerUpdateResults___________________________)
    .listen((filterState) async {
  AppKeys.mapView?.currentState?.activateMapOverlay();
  await Future.delayed(Duration(milliseconds: 100));
  setState(() {
    filterIsActive = filterState;
  });
});
```

**Comment by escamoteur** [comment]
@srawlins That would make it much better although I wished the handler function block of the listen would be indented more than the .`listen` and chance to achieve that?

**Comment by escamoteur** [comment]
Could it be a solution to give dartfmt a hint where to break a line by inserting a space before a '.' ? Like we do with trailing ','

**Comment by munificent** [comment]
It is [a non-goal to let users opt out of formatting](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-tell-the-formatter-to-ignore-a-region-of-code).

I agree the output in this particular case is not great. :( Like @srawlins notes, it has to do with the list literal. dartfmt has some surprisingly complex rules to handle function and collection literals inside arguments in order to more gracefully handle cases like:

```dart
function([
  element,
  element,
  element,
  element,
  element,
  element,
]).method();
```

Most users prefer that over:

```dart
function([
      element,
      element,
      element,
      element,
      element,
      element,
    ])
    .method();
```

Unfortunately, due to some limitations in the line splitting algorithm, it can't currently gracefully switch between allowing a trailing method call on the same line when the list literal does split while preventing it when it doesn't.

So in your example, it sees the list literal, and prepares to format it like:

```dart
    filterUpdateSubscription =
        sl.get<EventManager>().updateFilterCommand.results.mergeWith([
      sl.get<PlaceManager>().updateFilterCommand.results
    ]).listen((filterState) async {
      AppKeys.mapView?.currentState?.activateMapOverlay();
      await Future.delayed(Duration(milliseconds: 100));
      setState(() {
        filterIsActive = filterState;
      });
    });
```

But, then, because the list literal does all fit in one line, it switches things around, *but still leaves the `.listen()` on the same line.*

It's something I'd really like to improve, but I haven't been able to yet.

**Comment by escamoteur** [comment]
What about the idea to give dartfmt a hint like we can do by adding a trailing comma? So that by adding a space dartfmt knows where to break the line?

Another question: Why does dartfmt not indent the block of anonymous functions so that its end brace is not on the same depth as the rest of the surrounding code?

**Comment by munificent** [comment]
> What about the idea to give dartfmt a hint like we can do by adding a trailing comma? So that by adding a space dartfmt knows where to break the line?

I consider the trailing comma "hint" to be a major *problem* in dartfmt. I increasingly see code that inconsistently applies trailing commas and ends up with wildly inconsistent formatting in a single file.

> Why does dartfmt not indent the block of anonymous functions so that its end brace is not on the same depth as the rest of the surrounding code?

It looks better to format it like a block in a lot of common cases. Consider:

```dart
  group('textBeforeSelection', () {
    test('gets substring before selection', () {
      expect(selection.textBeforeSelection, equals("123"));
    });

    test('gets entire string if no selection', () {
      expect(noSelection.textBeforeSelection, equals("123456;"));
    });
  });
```

Versus:

```dart
  group(
      'textBeforeSelection',
      () {
        test(
            'gets substring before selection',
            () {
              expect(selection.textBeforeSelection, equals("123"));
            });

        test(
            'gets entire string if no selection',
            () {
              expect(noSelection.textBeforeSelection, equals("123456;"));
            });
      });
```

**Comment by munificent** [comment]
Why are the bodies of `test()` indented but `group()` is not? Why is this better than how it currently formats it?

**Comment by escamoteur** [comment]
Sorry, the example was wrong. I was more thinginh about the block of anonymous function blocks like

```Dart
    return Observable(_databaseService.getChatEntries(
      event,
    )).map((entryList) {
      entryList.forEach(
          (entry) => entry.isFromCurrentUser = (entry.userId == _userManager.currentUser.id));
      return entryList;
    });
````

vs.

```Dart
    return Observable(_databaseService.getChatEntries(
      event,
    )).map((entryList) {
        entryList.forEach(
            (entry) => entry.isFromCurrentUser = (entry.userId == _userManager.currentUser.id));
        return entryList;
      });
```

**Comment by zoechi** [comment]
The 2nd variant would make me very nervous.
It is a complete statement that ends with closing paren but not with the indentation of the beginning. It's completely unclear what it closes.

Adding `,` between `});` like `},); might be closer to what you want.

**Comment by munificent** [comment]
It's pretty common to chain higher-order functions. In your example, would they march farther and farther to the right?

```dart
    return Observable(_databaseService.getChatEntries(
      event,
    )).map((entryList) {
        entryList.forEach(
            (entry) => entry.isFromCurrentUser = (entry.userId == _userManager.currentUser.id));
        return entryList;
      }).where((entry) {
          return entry != null;
        }).map((entry) {
            return entry.toString();
          });
```

I don't think many users would be happy with that.

**Comment by munificent** [comment]
Earlier, I said:

> Unfortunately, due to some limitations in the line splitting algorithm, it can't currently gracefully switch between allowing a trailing method call on the same line when the list literal does split while preventing it when it doesn't.

One of my main goals with designing the new intermediate represention and line splitter was to fix this exact limitation. With the [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253), you get:

```dart
    filterUpdateSubscription = sl
        .get<EventManager>()
        .updateFilterCommand
        .results
        .mergeWith([sl.get<PlaceManager>().updateFilterCommand.results])
        .listen((filterState) async {
          AppKeys.mapView?.currentState?.activateMapOverlay();
          await Future.delayed(Duration(milliseconds: 100));
          setState(() {
            filterIsActive = filterState;
          });
        });
```

That looks pretty good to me.
