### ISSUE TITLE
Add option to preserve consecutive number of blank lines

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/dart_style#732]
Hi,

I really like how much work dartfmt saves me each day. One thing though really makes my live hard and that is that I'm not able to structure my code adding blank lines which can enhance readablilty and understanding a lot. Reducing any block of blank lines to one blank line makes dart files often hard to read.

It's clear to my that deciding what is an intentional blank line and what not possible, so I propose an formatting option to set the maximum number of consecutive blank lines that are allowed to remove. 

Thanks
Thomas

**Comment by aidandavis** [comment]
I agree. I wouldn't use this - I think it's a good thing that dartfmt is opinionated. 
However, you should be able to play with the options if that's what you want - as long as it doesn't remove from the simplicity of dartfmt as it is now.

**Comment by escamoteur** [comment]
Default should be the behavior as it is now

**Comment by sir-boformer** [comment]
I agree with this one. Especially at the beginning of a block, it is impossible to add a blank line.

**Comment by srawlins** [comment]
I'd like to see an example of when >1 blank lines increases readability or understanding a lot.

As far as configuration options, see [**Why can't I configure it?**](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it).

**Comment by escamoteur** [comment]
Ok, I did closer inspection of cases where I miss the space:

1. Beginning and end of blocks like here

```Dart
      child: StreamBuilder<List<Event>>(
          stream: sl.get<EventManager>().getEvents(
              constraints: constraints, filters: filters, useGlobalFilter: useGlobalFilter),
          builder: (context, snapShot) {
            if (snapShot == null || !snapShot.hasData) {
              return Center(child: Text("Seems like you haven't created any event yet"));
            }

            return ListView.builder(
              itemBuilder: (context, index) => buildEventTile(context, snapShot.data[index]),
              itemCount: snapShot.data.length,
            );
          }),
```

vs. 

```Dart
          stream: sl.get<EventManager>().getEvents(
              constraints: constraints, filters: filters, useGlobalFilter: useGlobalFilter),
          builder: (context, snapShot) {
            
            if (snapShot == null || !snapShot.hasData) {
              return Center(child: Text("Seems like you haven't created any event yet"));
            }

            return ListView.builder(
              itemBuilder: (context, index) => buildEventTile(context, snapShot.data[index]),
              itemCount: snapShot.data.length,
            );

          }),
```

Also if you declare a local function it's not possible to place a blank line before it.

2. between functions and classes to make the boundaries easier to spot while scrolling.

I agree inside a function it's better to place a comment to group parts of code. Any other idea how to deal with that.

**Comment by munificent** [comment]
I'm sorry, but *not* being configurable [is an explicit goal of dartfmt](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it). Dartfmt's primary job is to make the entire ecosystem more readable to all members, not to make any given corpus of code look the way some users prefer.

Imagine there are N Dart users, which means there are N×N pairs where Dart user A is reading code written by Dart user B. Say that the readability for any given pair is some combination of how *familiar* the style is to the reader and how much they *like* it.

The goal of dartfmt is to maximize the sum readability of all of those pairs. We can't easily change what people like and they don't all like the same thing, so that's hard to optimize for. We *can* change familiarity, though. The way we do that is with consistency. So dartfmt applies the *same* style to *all* code. That way, for each N×N pair, at least the reader will be seeing familiar code.

**Comment by escamoteur** [comment]
@munificent I complete understand the reasoning behind dartfmt. Still there should be room for discussion especially with the many devs coming in from other languages with Flutter.

Could could tell me what speaks against preserving one blank line at the beginning of blocks?

Also is there any reason that speaks against using 2 instead of one line between functions and classes which would enhance readability a lot?

**Comment by munificent** [comment]
> Could could tell me what speaks against preserving one blank line at the beginning of blocks?

dartfmt has been preventing a blank line there for years now. There are millions of lines of code formatted that way and I don't recall user complaints about it, so I believe there is very clear consensus that not having a blank line there is OK.

> Also is there any reason that speaks against using 2 instead of one line between functions and classes which would enhance readability a lot?

Same reason as above. Users seem happy without it and it's one less thing they have to think about.

**Comment by Pluto1219** [comment]
On behalf of 120,000 Flutter developers, I solemnly request, please add the option to support blank lines! ! ! Please respect the wishes of users! ! !

@escamoteur 

@aidandavis

**Comment by stefv** [comment]
> I'm sorry, but _not_ being configurable [is an explicit goal of dartfmt](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it). Dartfmt's primary job is to make the entire ecosystem more readable to all members, not to make any given corpus of code look the way some users prefer.

Ok, I will disable dartfmt.
