### ISSUE TITLE
Inconsistent line breaks

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/dart_style#733]
dartfmt produced
```
    BlocProvider.of(context).homeView.listen((HomeView view) {
      if (view == HomeView.trash)
        _controller.animateTo(0);
      else if (view == HomeView.inbox)
        _controller.animateTo(1);
      else if (view == HomeView.favorites) _controller.animateTo(2);
    });
```

expected

```
    BlocProvider.of(context).homeView.listen((HomeView view) {
      if (view == HomeView.trash)
        _controller.animateTo(0);
      else if (view == HomeView.inbox)
        _controller.animateTo(1);
      else if (view == HomeView.favorites) 
        _controller.animateTo(2);
    });
```

**Comment by munificent** [comment]
"Effective Dart" [disallows multi-line if statements that don't have braced bodies](https://www.dartlang.org/guides/language/effective-dart/style#do-use-curly-braces-for-all-flow-control-structures). When an if statement *can't* fit within the page width, it tries to make it not look horrible, but its ultimate goal is to follow the style guide.

The easiest fix here is to put `{}` on all of those bodies.

**Comment by lukepighetti** [comment]
Sounds like the trailing comma problem. Could produce reasonable output but because I'm omitting an optional format from the Google guides it's a broken and wont fix. Nice.
