### ISSUE TITLE
[Constants-Phase1]  Dartfmt Issue for Constants Implementation

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/dart_style#748]
Request: As per [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/implementation-plan.md), 

***Intellij/Grok/Dartfmt
Support for the new constant expressions is added to the relevant tooling.

It is very likely that no changes are needed here, as long as the analyzer supports the new expressions. All the affected expressions are already valid non-constant expressions.

Phase 1 ETA: please see issue [tracker] (https://github.com/dart-lang/language/issues/60)

**Comment by munificent** [comment]
Triple-shift is supported as of #1011.
