### ISSUE TITLE
Specify type annotations. vs Avoid annotating types for function expression parameters

### ISSUE THREAD

**Issue by swavkulinski** [dart-lang/dart_style#749]
Observed on Flutter project in IntelliJ

`converter: (store) => store.state.customerOrderModel,` marks `(store)` as **Specify type annotations**.

adding the annotation e.g.

`converter: (Store<TillState> store) => store.state.customerOrderModel,` marks `Store<TillState> store` as **Avoid annotating types for function expression parameters**

**Comment by swavkulinski** [comment]
Or is this more linter issue?

**Comment by munificent** [comment]
Sorry, this is not a formatter issue. (The formatter doesn't show any warnings or diagnostics unless it's completely unable to parse a file.) That sounds like it's coming from the linter: https://github.com/dart-lang/linter

**Comment by natebosch** [comment]
Note that the linter does _not_ guarantee that all lints are mutually compatible.

Also note that "specify type annotations" is not recommended unless you're working on the flutter framework itself as that team has peculiar style guides that the rest of the Dart ecosystem doesn't use. If you're writing a project using flutter it isn't typical to use that lint.
