### ISSUE TITLE
Line not broken up

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart_style#752]
```dart
class FieldSelectionMergingValidator extends NodeValidator {
  @override
  void onNodeEnter(Node node, ValidationContext context) {
    if (!algorithms.fieldsInSetCanMerge(nodeToValidate.selections)) {
      addValidationResult(ValidationResult<HasSelectionSet>(nodeToValidate,
          '5.3.2 The fields "${nodeToValidate.selections}" can not be merged.'));
    }
  }
}
```

![image](https://user-images.githubusercontent.com/405837/48539169-b305e500-e8b6-11e8-9fe2-135122477b09.png)

**Comment by natebosch** [comment]
https://github.com/dart-lang/dart_style/wiki/FAQ#why-does-the-formatter-only-touch-whitespace-by-default

See the comment about not splitting string literals. You probably need to split the string manually.

**Comment by zoechi** [comment]
I wouldn't expect it to break up the string literal, but it could move `));` to the next line.

**Comment by munificent** [comment]
The canonical style that dartfmt enforces never puts `)` on the next line unless there is a preceding trailing comma, so this is working as intended.
