### ISSUE TITLE
Implement --fix for avoid_single_cascade_in_expression_statements lint

### ISSUE THREAD

**Issue by cpelling** [dart-lang/dart_style#757]
It would be useful for dartfmt --fix to automatically fix violations of the lint avoid_single_cascade_in_expression_statements.

**Comment by matanlurey** [comment]
It is extremely unlikely `dartfmt` would have knowledge of or how to fix lints (separate ecosystem).

**Comment by munificent** [comment]
Closing since we're getting rid of `dart format --fix` in favor of `dart fix`: #1153
