### ISSUE TITLE
Function argument linebreaks are inconsistent compared to lists

### ISSUE THREAD

**Issue by dstaley** [dart-lang/dart_style#764]
I feel that `dartfmt` produces inconsistent results. The following lines are the same exact length, but 
result in different linebreaks.

```dart
main() async {
  _circleOfLife('Nants ingonyama bagithi Baba', 'Sithi uhm ingonyama',
      'Nants ingonyama bagithi baba', 'Sithi uhhmm ingonyama', 'Ingonyama');
  var lyrics = [
    'Nants ingonyama bagithi Baba',
    'Sithi uhm ingonyama',
    'Nants ingonyama bagithi baba',
    'Sithi uhhmm ingonyama',
    'Ingonyama'
  ];
}
```

For comparison, the JavaScript version of this code looks like this when run through Prettier:
```js
async function main() {
  _circleOfLife(
    "Nants ingonyama bagithi Baba",
    "Sithi uhm ingonyama",
    "Nants ingonyama bagithi baba",
    "Sithi uhhmm ingonyama",
    "Ingonyama"
  );
  var lyrics = [
    "Nants ingonyama bagithi Baba",
    "Sithi uhm ingonyama",
    "Nants ingonyama bagithi baba",
    "Sithi uhhmm ingonyama",
    "Ingonyama"
  ];
}
```

I expected function arguments to be treated in the same way as list elements, with each element appearing on a new line. However I do understand that there might be a preference for the function's style. If that's the case I would expect lists to be consistent with the function call, like this:

```dart
main() async {
  _circleOfLife('Nants ingonyama bagithi Baba', 'Sithi uhm ingonyama',
      'Nants ingonyama bagithi baba', 'Sithi uhhmm ingonyama', 'Ingonyama');
  var lyrics = ['Nants ingonyama bagithi Baba', 'Sithi uhm ingonyama',
      'Nants ingonyama bagithi baba', 'Sithi uhhmm ingonyama', 'Ingonyama'];
}
```

**Comment by munificent** [comment]
Yes, the styles are deliberately different here. When the formatting rules were first implemented, almost all Dart code I saw in the wild used different line-wrapping and indentation styles for argument lists compared with collections.

This is not the style some on the Flutter team prefer where they format (most) argument lists the same way they do collections. But Flutter didn't exist when dartfmt was first created, and at this point it's not clear what the consensus preference is among the userbase.
