### ISSUE TITLE
Line break in return type (inline function)

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/dart_style#766]
Actual:
```dart
  Future<
      List<
          String>> fetchColors() async => json.decode(await downloadUrlAsString(
```
I would have expected something like this:
```dart
  Future<List<String>> fetchColors() async => 
        json.decode(await downloadString(
```
Reducing the method name characters gives a nicer output:
```dart
  Future<List<String>> fetchColors() async => json.decode(await downloadString(
```

**Comment by munificent** [comment]
Can you show the full body of the function? Often, when you get weird formatting, it's because something farther in is forcing it to split earlier.

**Comment by jimmyff** [comment]
You were correct @munificent -it was a long string that was causing the weirdness
