### ISSUE TITLE
No setter without getter-rule encourages bad naming.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart_style#769]
The rule [https://www.dartlang.org/guides/language/effective-dart/design#dont-define-a-setter-without-a-corresponding-getter] says that if you would have a setter, and no getter, you should instead make the setter a method.

People follow that and write code like:
```dart
void setFoo(int length) { ... };
void setBar(String name) { ... };
void setBaz(bool Function(test)) { ... };
```
That is not an improvement.
Maybe the rule should also say that you must find a proper name for the method, like:
```dart
void filterFooByLength(int length) { ... };
void matchBarByName(String name) { ... };
void testBaz(bool Function(test)) { ... };
```
which would depend on the meaning of setting that particular property of the object.

(Or drop the rule if that's not possible, because it's better to have a lone setter with a good name than a method with a name that screams "I should have been a setter").

**Comment by munificent** [comment]
This is a valid point, but filed in the wrong repo. :) "Effective Dart" lives on the website and the issue tracker for its repo is [here](https://github.com/dart-lang/site-www/issues). Mind filing this over there?
