### ISSUE TITLE
Respect new lines when there's no good reason to not do so

### ISSUE THREAD

**Issue by renatoathaydes** [dart-lang/dart_style#773]
Take this code sample:

```dart

@immutable
class GameState {

  static const empty = [
    SquareState.EMPTY, SquareState.EMPTY, SquareState.EMPTY,
    SquareState.EMPTY, SquareState.EMPTY, SquareState.EMPTY,
    SquareState.EMPTY, SquareState.EMPTY, SquareState.EMPTY,
  ];

  final squares;

  GameState([this.squares = empty]);
}
```

I think anyone would agree, it's perfectly formatted. However, dartfmt spoils it like this:

```dart
@immutable
class GameState {
  static const empty = [
    SquareState.EMPTY,
    SquareState.EMPTY,
    SquareState.EMPTY,
    SquareState.EMPTY,
    SquareState.EMPTY,
    SquareState.EMPTY,
    SquareState.EMPTY,
    SquareState.EMPTY,
    SquareState.EMPTY,
  ];

  final squares;

  GameState([this.squares = empty]);
}
```
In this case, the new-lines matched the tic-tac-toe board game layout... in a lot of cases, the programmer will have good reasons, as in this example, to know where to break lines that a formatter will never be able to figure out.

For this reason, the formatter should be extremely cautious before changing line breaks, it should have strong reasons to do so.... like a line exceeding a default per-line character limit... in this example, this did not happen.

The IntelliJ Java formatter is perfect in my opinion, it always seems to do the right thing, and one thing it almost never does is change line-breaks. It only does it if configured to do so (and you must configure each special occasion where you want that to happen). This is the way to go in my opinion.

**Comment by munificent** [comment]
For collection literals that have some internal structure, you can have dartfmt preserve it by [having a comment inside the literal](https://github.com/dart-lang/dart_style/wiki/FAQ#why-does-the-formatter-mess-up-my-collection-literals).

**Comment by renatoathaydes** [comment]
But why change line breaks in the first place except for when some rule is being broken?

**Comment by munificent** [comment]
> But why change line breaks in the first place except for when some rule is being broken?

This is the formatter's job: it fixes your whitespace so you don't have to think about it. Line breaks are part of the whitespace. If the formatter didn't fix it, that means humans would have to spend more time thinking about them, arguing about them in code reviews, fixing them after refactoring, etc.
