### ISSUE TITLE
dartfmt --fix hangs

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/dart_style#776]
Hi there, 

I'm in a project folder and i typed `dartfmt --fix` and it just hangs. 

Is this taking a long time or is it doing nothing?

**Comment by srawlins** [comment]
A million dollars to anyone who can [answer this](https://en.wikipedia.org/wiki/Halting_problem)! 👅

**Comment by lukepighetti** [comment]
Hahaha that's pretty good. However, if dartfmt doesn't do anything with no args, it should probably provide a message and halt, no?

**Comment by kevmoo** [comment]
It's waiting for `stdin` –  which is pretty common.

**Comment by lukepighetti** [comment]
alright ` ¯\_(ツ)_/¯`

**Comment by munificent** [comment]
Yeah, @kevmoo is right. I agree the behavior is confusing. However, that's how it behaved from the early days before I took over dartfmt, and changing it is a breaking change. It's doable, but it's not clear that it's worth the effort and possible pain to do so.

**Comment by lukepighetti** [comment]
If its any consolation, a quick check of `dartfmt -h` got me going

**Comment by exts** [comment]
Oh I'm an idiot, for those finding this thread and confused on why it's not working.

`dartfmt -w --fix PATH` should help you where PATH is `lib` for instance.
