### ISSUE TITLE
Indent chained method calls to align on "."

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_style#78]
From @kwalrath:

When all of the following are true:

* the first `.` in a bunch of chained calls is on the first line of a statement (no matter what column)
* the `.`s for the following calls are aligned under the first line's `.`
* the line length isn't too long

Could you please leave the `.`s aligned? It's especially important in the following example, where the current output makes it easy to misread that `runQuery()` returns `result`, rather than the future returned by catchError (if I remember this right).

Input (which I'd like to be the output, as well):

```dart
Future runQuery() {
  Future result = costlyQuery();

  return result.then((value) => expensiveWork())
               .then((value) => lengthyComputation())
               .then((value) => print('done!'))
               .catchError((exception) => print('DOH!'));
}
```

Output:

```dart
Future runQuery() {
  Future result = costlyQuery();

  return result
      .then((value) => expensiveWork())
      .then((value) => lengthyComputation())
      .then((value) => print('done!'))
      .catchError((exception) => print('DOH!'));
}
```

**Comment by sigmundch** [comment]
FYI I personally prefer the current output on this one
