### ISSUE TITLE
Would like dartfmt to leave a blank line after shebang lines

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dart_style#782]
_From @jamesderlin on March 18, 2019 8:30_

Currently (as of dartfmt version 1.2.2) if I make a `.dart` script that's meant to be executable:

    #!/usr/bin/env dart

    import 'dart:io';
    // More code...    

Then `dartfmt` will remove the blank line after the shebang line.  I dislike this because it puts Dart code up against a line that isn't legal Dart.  I also suspect that putting a blank line between the shebang and code (or between the shebang with copyright notice and code) is a more common practice than not, but I haven't collected data to back that up.

(I suppose I should be encouraged to add a dartdoc comment near the top of the script since `dartfmt` will insert a blank line above it.)

_Copied from original issue: dart-lang/sdk#36246_

**Comment by munificent** [comment]
It's been working this way without complaint for some time, so I don't know if most users would agree with this change. In practice, my guess is few enough users use shebang lines in Dart to have even noticed. I'm sympathetic to the idea.

**Comment by jamesderlin** [comment]
A blank line is inserted/preserved in some cases:

```dart
#!/usr/bin/env dart

void main() {}
```

```dart
#!/usr/bin/env dart

/// dartdoc comment.
```

```dart
#!/usr/bin/env dart

var someGlobal = 0;
```
But it's removed in these cases:
```dart
#!/usr/bin/env dart
import 'dart:io';
```

```dart
#!/usr/bin/env dart
// Normal comment.
```

so arguably there's a consistency issue as well.

**Comment by munificent** [comment]
That's good data, thanks! This may not be intentional behavior.
