### ISSUE TITLE
method call with single instance creation (with trailing comma)

### ISSUE THREAD

**Issue by a14n** [dart-lang/dart_style#804]
Acutal:

```dart
Navigator.push(
    context,
    MaterialPageRoute<DismissDialogAction>(
      builder: (BuildContext context) => FullScreenDialogDemo(),
      fullscreenDialog: true,
    ));
```

expected:

```dart
Navigator.push(context, MaterialPageRoute<DismissDialogAction>(
  builder: (BuildContext context) => FullScreenDialogDemo(),
  fullscreenDialog: true,
));
```

**Comment by munificent** [comment]
In general, my impression is that users want dartfmt to move *away* from applying this block-like formatting to argument lists. When I first wrote dartfmt, users seem to like a pretty dense style, but especially with Flutter now, users seem to like simpler, more regular formatting even if it's vertically taller.

So, in this case, I think the current output is fine, except for the fact that the trailing commas aren't applied consistently. Ideally, you'd write:

```dart
Navigator.push(
    context,
    MaterialPageRoute<DismissDialogAction>(
      builder: (BuildContext context) => FullScreenDialogDemo(),
      fullscreenDialog: true,
    ),);
```

Which it would then format as:

```dart
void main() {
  Navigator.push(
    context,
    MaterialPageRoute<DismissDialogAction>(
      builder: (BuildContext context) => FullScreenDialogDemo(),
      fullscreenDialog: true,
    ),
  );
}
```

**Comment by a14n** [comment]
>When I first wrote dartfmt, users seem to like a pretty dense style, but especially with Flutter now, users seem to like simpler, more regular formatting even if it's vertically taller.

Actually this PR was done to reduce the differences between how Flutter code is formatted and what dartfmt outputs (in flutter/flutter#30138 I used a patched version of dartfmt with this PR - and some additionnal changes).

As you notice if a user wants to put every arguments on their own lines he can add a trailling comma:

```dart
// without comma
Navigator.push(context, MaterialPageRoute<DismissDialogAction>(
  builder: (BuildContext context) => FullScreenDialogDemo(),
  fullscreenDialog: true,
));

// with comma
Navigator.push(
  context,
  MaterialPageRoute<DismissDialogAction>(
    builder: (BuildContext context) => FullScreenDialogDemo(),
    fullscreenDialog: true,
  ),
);
