### ISSUE TITLE
Separate the control structure expression from its statement

### ISSUE THREAD

**Issue by blasten** [dart-lang/dart_style#814]
Single statements like these:
```dart
if (result.exitCode != 0) 
    throw 'Gradle exited with error';

 if (javaHome == null)
      return TaskResult.failure('Could not find Java');
```

are formatted into:
```dart
if (result.exitCode != 0) throw 'Gradle exited with error';
if (javaHome == null) return TaskResult.failure('Could not find Java');
```

which causes:
```
Separate the control structure expression from its statement.dart(always_put_control_body_on_new_line)
```

**Comment by munificent** [comment]
Yeah, the linter is non-opinionated and supports a wide variety of lints, some of which are in conflict with "Effective Dart", dartfmt's output, and even each other. The easy fix here is to disable that lint.

"Effective Dart" says that unbraced control flow statements should only be used if they fit on a single-line so dartfmt does its best to honor that.

**Comment by natebosch** [comment]
`always_put_control_body_on_new_line` was written specifically for the flutter SDK which does not follow general Dart style.
