### ISSUE TITLE
Incorrect re-ordering analyzer line ignore comments in imports section

### ISSUE THREAD

**Issue by Lisenish** [dart-lang/dart_style#817]
Dartfmt breaks analyzer "ignore rule in next line" comments because it re-orders them to the end of the imports section.

Example:

**Before**

```
import 'package:some_package/some_lib.dart';
// ignore: deprecated_member_use
import 'package:some_deprecated_package/some_lib.dart';
```

**After**

```
import 'package:some_package/some_lib.dart';
import 'package:some_deprecated_package/some_lib.dart';
// ignore: deprecated_member_use
```

And now we get analyzer error.

**Comment by natebosch** [comment]
Probably similar to https://github.com/dart-lang/dart_style/issues/812 - are you sure this is coming from `dartfmt` or is it possible your IDE is formatting some other way? How are you running the formatter - if it's through your IDE are you able to repro on the command line?

**Comment by munificent** [comment]
Nate is correct. dartfmt doesn't do any code reordering (in large part to avoid tricky edge cases like this). The import reordering is either coming from the IDE or some other tools.

**Comment by Lisenish** [comment]
Oh, I see, thank you.
My apologies for the incorrect issue
