### ISSUE TITLE
`dartfmt` should fix formatting issues reported by Pub website / `pana` package

### ISSUE THREAD

**Issue by cedx** [dart-lang/dart_style#818]
Pub website has started to lower the score of packages with some formatting issues.

Me, and probably a lot of developers, will not change their coding style just because the Dart team has decided that our code was not properly formatted.

So, `dartfmt` should fix these errors in order to help package publishers to meet the new requirements of Pub website / `pana` analyzer.

See: dart-lang/pub-dev#2322

**Comment by natebosch** [comment]
The pub-dev issue calls out braces around line-wrapped conditional bodies and included links to issues in this repo discussing it. I don't see other specific questions in that thread.

I reopened #664 to start a discussion about whether we can add a `--fix` flag for that one specifically. If there are other formatting issues that are checked by pana that you believe would fit as a `--fix` please open specific issues for them - a blanket issue isn't actionable.
