### ISSUE TITLE
Function parameter spacing

### ISSUE THREAD

**Issue by duzenko** [dart-lang/dart_style#820]
Coming from C++/C# I'm used to auto-formatting my code like this
```
    const screenPosition = new Vec2( e.offsetX, webgl2.canvas.height - e.offsetY )
    this.MouseDownPos.copy( position.minus( this.Camera.position ) )
```
Note the spaces inside parenthesis. Even Typescript that I recently played with has this formatter option.
Can I somehow have this in Dart please?

**Comment by a14n** [comment]
See https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it
