### ISSUE TITLE
Parent to child indents the wrong way when using =>

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dart_style#824]
From @cable729
https://github.com/flutter/flutter-intellij/issues/3593

## Steps to Reproduce

Here is the code:
```
import 'package:flutter/material.dart';
import 'package:volleyballmeetup/src/containers/auth_button/google_auth_button_container.dart';

class AppDrawer extends StatelessWidget {
  final Function onProfileTapCallback;
  final String profilePicUrl;
  final String userName;

  AppDrawer({this.onProfileTapCallback, this.profilePicUrl, this.userName});

  @override
  Widget build(BuildContext context) => Drawer(
        child: ListView(children: _getListItems()),
      );

  List<Widget> _getListItems() {
    final list = <Widget>[
      _getHeader(),
      ListTile(
        leading: Icon(Icons.person),
        title: Text('Profile'),
        onTap: onProfileTapCallback,
      ),
    ];
    return list;
  }

  Widget _getHeader() => DrawerHeader(
          child: Container(
        height: 500,
        child: _isLoggedIn()
            ? Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  CircleAvatar(
                    maxRadius: 40,
                    backgroundImage: NetworkImage(profilePicUrl),
                  ),
                  Padding(
                    padding: EdgeInsets.symmetric(horizontal: 6),
                  ),
                  Text(userName)
                ],
              )
            : GoogleAuthButtonContainer(),
      ));

  bool _isLoggedIn() => profilePicUrl != null && userName != null;
}
```

Android Studio sees the indent as going from right to left when going from a parent to a child, which should not happen (see child height child):

![Image of formatting](https://i.imgur.com/Dcci8Oz.png)

## Version info

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
    en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/caleb/dev/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Caleb/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/Caleb/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/Caleb/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 99646FD6-20EF-4696-8853-B4B87DDBB19F • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by jacob314** [comment]
It would be ideal if build methods like this formatted as
<img width="384" alt="Screen Shot 2019-06-18 at 8 15 59 AM" src="https://user-images.githubusercontent.com/1226812/59697036-ffddd100-91a1-11e9-9275-62f57d1e8788.png">
or at least didn't format with child widgets indented less than their parents which leads to hard to read code.

**Comment by munificent** [comment]
The issue here is just:

```dart
      ));
```

The DrawHeader argument list doesn't have a trailing comma, so you're getting a mixture of formatting styles. Put a comma in there and it should look like you want.

**Comment by cable729** [comment]
Is it really the design the users MUST put a trailing comma on everything in order to get correct formatting? This seems like the real issue.

**Comment by natebosch** [comment]
> the users MUST put a trailing comma on everything in order to get correct formatting

It's unfortunate that there are now 2 definitions of "correct" when it comes to formatting, but we pretty much have to live with.

It's not true that the user _must_ put in a trailing comma, they can make a choice. It's also not true that omitting the comma results in "incorrect" formatting - some users prefer that.

What is true is that in order to get _consistent_ formatting the users must use _consistent_ commas. I don't think that should be surprising.

**Comment by munificent** [comment]
> Is it really the design the users MUST put a trailing comma on everything in order to get correct formatting?

Yes, unfortunately.

> This seems like the real issue.

You're absolutely right. Unfortunately, it's mostly a social/political one. We have a giant corpus of Dart code all formatted a different way and a large number of users who are happy with it, so it's not a simple matter of changing how dartfmt works.

**Comment by cable729** [comment]
One solution that appeases both groups would be to give the formatter a setting:

1. Prefer trailing commas: the formatter would add trailing commas if you forget to add them, and will format the file correctly.
2. Prefer no trailing commas: the formatter would remove trailing commas and format correctly based on that.
3. Add commas when necessary: the formatter would remove commas until expanding to a new line is needed, then add commas and format in this way. This is similar to the way java-google-format tries to group content together on as few lines as possible..

**Comment by munificent** [comment]
See [this FAQ entry](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it).

In particular, imagine you're doing a large-scale refactoring across the entire Google codebase. (This happens more often than you might expect.) To keep code formatted correctly, you run dartfmt after the refactoring. If different parts of the codebase are formatted with different settings, somehow you have to figure out which parts use which setting and preserve that.
