### ISSUE TITLE
bump an analyzer 0.37.0 compat version?

### ISSUE THREAD

**Issue by pq** [dart-lang/dart_style#827]
Hi!

There's a new version of `analyzer` and `linter` and other clients of `dart_style` could use a fresh version with compatible constraints.

```
Because dart_style >=1.2.8 depends on analyzer ^0.36.3 and dart_style >=1.2.5 <1.2.8 depends on analyzer ^0.36.0, dart_style >=1.2.5 requires analyzer ^0.36.0.
So, because linter depends on both analyzer ^0.37.0 and dart_style ^1.2.5, version solving failed.
```

Chatting w/ @stereotype441, this could likely be a minor version bump with only broadened deps so hopefully no more work than a pubspec update?

Thanks in advance!

/cc @munificent

**Comment by munificent** [comment]
1.2.9 takes care of this: 713971a3d884ad969738670cac511afe34a891d8
