### ISSUE TITLE
Poor formatting of collection-if

### ISSUE THREAD

**Issue by har79** [dart-lang/dart_style#831]
dartfmt version: 1.2.8

the following code is formatted:

```dart
foo() {
  final bar = [
    if (longVariableName == 'do nothing but be long') ...[] else if (longVariableName ==
        'show the welcome message')
      'Hello'
  ];
}
```

this is not as readable as it should be; it hides the if-element and the else-condition by collapsing them onto the same line as the if-condition.

*   the line is broken inside the if condition rather than between the if and else blocks
*   the if-element is not on a separate line but the else-element is
*   line 3 is longer than 80 characters

expected:

```dart
foo() {
  final bar = [
    if (longVariableName == 'do nothing but be long')
      ...[]
    else if (longVariableName == 'show the welcome message')
      'Hello'
  ];
}
```

As an aside, is there a better way of doing nothing for an if-element? In this example it could just be removed, but in the actual code (internal) it was followed by 3 else-if conditions and it was cleaner to do, effectively, an early return.

Thanks!

**Comment by a14n** [comment]
I'd expect something a little different regarding spread inside if:

```dart
foo() {
  final bar = [
    if (longVariableName == 'do nothing but be long') ...[
    ] else if (longVariableName == 'show the welcome message')
      'Hello'
  ];
}
```

**Comment by munificent** [comment]
Yeah, I agree this output isn't ideal. I think I just overlooked this case. The corresponding statement version is formatted similar to what you'd like:

```dart
if (longVariableName == 'do nothing but be long') {
} else if (longVariableName == 'show the welcome message') 'Hello';
```

**Comment by munificent** [comment]
OK, I have a fix that isn't exactly what I initially planned but I think it's simple and works pretty well. With that fix, the result you get on the example here is:

```dart
foo() {
  final bar = [
    if (longVariableName == 'do nothing but be long')
      ...[]
    else if (longVariableName == 'show the welcome message')
      'Hello'
  ];
}
```

> As an aside, is there a better way of doing nothing for an if-element?

Not that I can think of.
