### ISSUE TITLE
dartfmt crashes when annotations have type arguments

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/dart_style#836]
Found via fuzz testing, not necesarily a priority.

@danrubel 

```
The formatter produced unexpected output. Input was:

@ap<int, String> f90() {/* aaaaaaaaaaaaaa */

// aaaaaaaaaaaaaaaaaaaaaa
Set<intcovariant> var00 = Uri.decodeQueryComponent('');


}


Which formatted to:
@ap
f90() {
  /* aaaaaaaaaaaaaa */

// aaaaaaaaaaaaaaaaaaaaaa
  Set<intcovariant> var00 = Uri.decodeQueryComponent('');
}
```

See the difference? `@ap<int, String> f90()` becomes `@ap\nf90()`.

It looks like annotations are _not_ supposed to have type arguments, but the parser expects this to be caught by the implementations. I could also imagine this restriction being lifted in the future. So I'm not sure whether the fix belongs in the parser or in dartfmt.

**Comment by danrubel** [comment]
The parser reports the error but passes the type argument information onto the listeners. The AstBuilder drops the type argument information as part of building the AST. I believe the formatter uses the AST to output source, and thus does not see the dropped type argument information. IMO this is reasonable behavior for now seeing as type arguments are not allowed on annotations.

I'll leave this open for now to allow others to suggest a different course of action.

**Comment by munificent** [comment]
> @bwilkerson Should the ANNOTATION_WITH_TYPE_ARGUMENTS error code be changed to a syntax error so that dartfmt does not run?

Yes, please. I think this is what I would consider a syntax error.

**Comment by munificent** [comment]
With the latest analyzer, which dartfmt now requires, a parse error is correctly reported.
