### ISSUE TITLE
dartfmt is line-breaking on a generic argument list

### ISSUE THREAD

**Issue by hterkelsen** [dart-lang/dart_style#857]
Look at this PR in `flutter/plugins`: https://github.com/flutter/plugins/pull/2112/files

*BEFORE*:
```dart
  Future<PurchasesResultWrapper> queryPurchaseHistory(SkuType skuType) async {
    assert(skuType != null);
    return PurchasesResultWrapper.fromJson(await channel
        .invokeMapMethod<String, dynamic>(
            'BillingClient#queryPurchaseHistoryAsync(String, PurchaseHistoryResponseListener)',
            <String, dynamic>{'skuType': SkuTypeConverter().toJson(skuType)}));
  }
```

*AFTER*:
```dart
  Future<PurchasesResultWrapper> queryPurchaseHistory(SkuType skuType) async {
    assert(skuType != null);
    return PurchasesResultWrapper.fromJson(await channel.invokeMapMethod<String,
            dynamic>(
        'BillingClient#queryPurchaseHistoryAsync(String, PurchaseHistoryResponseListener)',
        <String, dynamic>{'skuType': SkuTypeConverter().toJson(skuType)}));
  }
```

**Comment by munificent** [comment]
This is working as intended. darfmt will do anything it possibly can to try to fit the code in the line length, even if that means breaking at some really strange location. The long string literal here is putting it into a weird position, so it does its best.

To fix this, just split that string into a couple of adjacent strings so it has more to work with.

**Comment by hterkelsen** [comment]
Sounds good. I was thinking if breaking the generic argument allows the formatter to avoid pushing the arguments in by one-indentation level, then it could lead to ugly formatting where it prefers to break the generic arguments if it can format the arguments in a nicer way, but I'm guessing there is a very "high cost" to breaking generic arguments, so this will only happen if you have an argument that is over the line limit.

**Comment by munificent** [comment]
> I'm guessing there is a very "high cost" to breaking generic arguments

Indeed, it's the highest numeric cost.
