### ISSUE TITLE
indent changes depending on method chain

### ISSUE THREAD

**Issue by a14n** [dart-lang/dart_style#861]
with Dart-2.5.1 the following code:

```dart

f() {
  a.b().m(
    t: '',
  );
  a.b.m(
    t: '',
  );
  a.m(
    t: '',
  );
}
```

is formatted as:

```dart

f() {
  a.b().m(
        t: '',
      );
  a.b.m(
    t: '',
  );
  a.m(
    t: '',
  );
}
```

As you can notice there are extra-indent only with a method call in the previous chain-call.

**Comment by a14n** [comment]
I forgot to notice that those extra-indent shouldn't be there :)

**Comment by munificent** [comment]
Ugh, another weird interaction between trailing commas and other formatting rules. :-/

**Comment by munificent** [comment]
The [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) does the right thing and yields the same indentation for all three calls:

```dart
f() {
  a.b().m(
    t: '', // comment to force split
  );
  a.b.m(
    t: '', // comment to force split
  );
  a.m(
    t: '', // comment to force split
  );
}
```
