### ISSUE TITLE
🙏publish a version compatible w/ analyzer 0.39.0?

### ISSUE THREAD

**Issue by pq** [dart-lang/dart_style#866]
The linter's pana baseline testing is failing since we're not on the latest analyzer:

https://travis-ci.org/dart-lang/linter/jobs/601269527

However, the latest `dart_style` has too low of a lower-bound:

```
Because dart_style >=1.3.0 depends on analyzer ^0.38.3 and linter depends on analyzer ^0.39.0, dart_style >=1.3.0 is forbidden.
So, because linter depends on dart_style ^1.3.2, version solving failed.
```

@munificent: would you be up for pushing a new one?

Thanks in advance!

**Comment by pq** [comment]
Some more context here: https://github.com/dart-lang/linter/pull/1781#issuecomment-544962641

**Comment by munificent** [comment]
Will do, but it looks like there isn't a version of package test that supports 0.39.0, so it may not help you until that's revved too.

**Comment by pq** [comment]
> Will do, but it looks like there isn't a version of package test that supports 0.39.0, so it may not help you until that's revved too.

Oh, you're right. 😢 

@grouma: would you be up for helping with this?

/fyi @stereotype441 (not sure you're tracking these follow-on tasks independently)

**Comment by pq** [comment]
`test` just landed so I think we're good to publish?

**Comment by pq** [comment]
Thank you!
