### ISSUE TITLE
Should we force nested for/if elements to separate lines in collection literals

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dart_style#869]
Things can feel a little dense when there are multiple conditions or loops on the same line. It might work out for readers accustomed to generators in Python, but coming from chains of iterable calls or non-element for loop it can be hard to read.

Should we break these up? If we do break them up, should the inner one be forced to separate lines, or can it be all one line?

Today:

```dart
    var failed = [
      for (var e in _restResultEvents) if (!e.isSuccess) e.message,
    ];
```

Option 1:

```dart
    var failed = [
      for (var e in _restResultEvents)
        if (!e.isSuccess)
          e.message,
    ];
```

Option 2:

```dart
    var failed = [
      for (var e in _restResultEvents)
        if (!e.isSuccess) e.message,
    ];
```

**Comment by craiglabenz** [comment]
I also come from a Python background, but it didn't even trigger that part of my brain until I read your callback to Python's inline generators. Possibly, the part of my brain that quickly reads that in Python is more specifically trained than I'd ever appreciated.

At any rate, I do strongly prefer Options 1 and 2 over today's default. Between those two, I would vote for Option 1.

**Comment by munificent** [comment]
I like option 2. Option 1 feels a little gratuitous to me.
