### ISSUE TITLE
Conflict with analysis option?

### ISSUE THREAD

**Issue by glhrmv** [dart-lang/dart_style#875]
I am using the official Flutter repo's linting rules ([`analysis_option.yaml`](https://github.com/flutter/flutter/blob/master/analysis_options.yaml)). I have the following code snippet:
```dart
if (dataToJson == null) 
      return 'Success';
```
When I run `flutter format lib/*`, the code is changed to
```dart
if (dataToJson == null) return 'Success';
```
Which raises the following error message:
```
Separate the control structure expression from its statement. dart(always_put_control_body_on_new_line)
```

I am wondering if this is expected behaviour, I had the impression the formatter would adjust to the analysis options. Maybe I missed a configuration step. Any comment is appreciated.

**Comment by natebosch** [comment]
Yes this is expect. The Flutter SDK does not follow Effective Dart style, and they format code by hand. We recommend that users _don't_ use `always-put_control_body_on_new_line`, it was written specifically for the Flutter SDK and the unusual style within.

The formatter has no configuration and does not change behavior based on the analysis options. This is also expected. See https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it

If you choose to follow Flutter SDK internal code style you likely won't be able to use `dartfmt`.
