### ISSUE TITLE
The autoformat should have other options

### ISSUE THREAD

**Issue by Likewizedog** [dart-lang/dart_style#882]
I'm using a Flutter template for this demo.

I have raised this issue here: 
https://github.com/dart-lang/dart-pad/issues/1431
And the cool dude redirected me to this project.

---

The autoformat takes on this style, that I don't think everyone agrees with.

![1](https://user-images.githubusercontent.com/10816102/71237005-0e4fa580-2309-11ea-9f6d-88f30a43b6e9.png)

---

For me, this next style is much easier to read and work with. I'm sure some will agree. So, an alternate
formatting option would be really awesome. And maybe later on allow us to create custom format
templates.

![2](https://user-images.githubusercontent.com/10816102/71237006-0ee83c00-2309-11ea-878e-31f30e6203e7.png)

**Comment by munificent** [comment]
Please see here: https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it
