### ISSUE TITLE
feature:  dartfmt to auto-fix ';' insertion for better editor developer experience, PR included.

### ISSUE THREAD

**Issue by AnnotatedAsterisk** [dart-lang/dart_style#884]
It is annoying dartfmt does not fix code with missing semi-colon.

current `dartfmt` 

```dart
    import 'thing.dart'
    void main() {
      print()
      thing
      ..onClick.listen(() {
        window.alert('clicked')
      })
    }
```

yields
```
1 │ import 'thing.dart'
  │        ^^^^^^^^^^^^
  ╵
line 3, column 13 of <stdin>: Expected to find ';'.
  ╷
3 │       print()
  │             ^
  ╵
line 6, column 31 of <stdin>: Expected to find ';'.
  ╷
6 │         window.alert('clicked')
  │                               ^
  ╵
line 7, column 8 of <stdin>: Expected to find ';'.
  ╷
7 │       })
  │        ^
  ╵
```

It is clear and obvious what will be desirable from the diagnostics,
just use that list of errors and add ';' there, re-feed the code to the formatter.

few edge cases like endline following brackets(property access or array) would produce improper fix(due to syntax definition). 

such risk during editing session is low, since it breaks everything, undo and manually add the required ';'.

I understand that this is *not* a style-fix, and feeding "invalid" code to a formatter should fail.

popular formatter like `prettier`(granted js ';' is optional), `refmt` have auto ';'.

while the optional ';' proposal is stale please consider this.

P.S. vscode/webstorm dart plugin do not use the `dartfmt` binary, and provide no override option, you will need to build a custom SDK or editor plugin.

**Comment by AnnotatedAsterisk** [comment]
ahh..., didn't run the test locally properly, since it just worked for my editor. 

ci failed case 'herp derp i are a dart', no perfect way to avoid those, but I can make sure all ';' must be on separate lines.

```
Could not format because the source could not be parsed:

line 1, column 6 of <stdin>: Expected to find ';'.
  ╷
1 │ herp derp i are a dart
  │      ^^^^
  ╵
line 1, column 13 of <stdin>: Expected to find ';'.
  ╷
1 │ herp derp i are a dart
  │             ^^^
  ╵
line 1, column 19 of <stdin>: Expected to find ';'.
  ╷
1 │ herp derp i are a dart
  │                   ^^^^
  ╵
```

**Comment by munificent** [comment]
This is not a bad idea, but doing this would very significantly change the scope and charter of dartfmt. Right now, the formatter's policy — which users know and take for granted — is:

1. If you give dartfmt a valid Dart program, it will change the whitespace characters in it to a standardized format.

2. It makes no other changes to anything else in the code.

3. If you give it a program with a syntax error, it does nothing.

This very limited scope gives users the confidence to let them run dartfmt in automated presubmits, automatically before committing, on large corpuses after massive refactorings, and even before every single file save in their editor.

If we change the charter to "It will accept *some* invalid Dart programs and transform them to valid Dart programs for you," then we would need to be very explicit about *which* invalid Dart programs and *how*. I think that would be really difficult. Instead, I think it's better for another tool to do these kinds of fixes.
