### ISSUE TITLE
FAQ should explain what to do when Dartfmt isn't the right tool. SPOILER: It can't be not using a formatter.

### ISSUE THREAD

**Issue by marcglasberg** [dart-lang/dart_style#894]
I've never seen such an authoritarian formatting policy as in Dart.

I do mainly agree with the 4 points you described in your [FAQ](https://github.com/dart-lang/dart_style/wiki/FAQ). But within our own code, which will never be seen by anyone outside of our corporation, we'd like to have our own rules that would be the same for all of our developers. This would ensure your 4 FAQ points within our own code.

You say "The primary goal of dartfmt is to improve the quality of the Dart ecosystem." I do have some published packages, and I wouldn't want to format them differently than the default. But not all code is part of the "Dart ecosystem". Some of it is internal code.

The problem is I'd like to make small tweaks to DartFmt but the IntelliJ plugin doesn't let me choose another one. I am not talking about the formatter itself: if you don't want to include tweakable settings in DartFmt that's OK, but why go the extra mile and make it extremely difficult for someone to tell the IDE to use a modified DartFmt? This goes against all that open source stands for. You are working hard to remove all of our freedom.

I think DartFmt is a wonderful piece of software, and I think your work is great. But I don't think you, or even the Dart Team, have the right to just decide how every single Dart programmer in the world is going to format their code.

This part of your FAQ is what I think is the authoritarian part: "If you don't buy that, that's OK. It just means dartfmt probably isn't the right tool for you." You are right it isn't. But at the same time we can't go without a formatter. A formatter is essencial, there is no way around it. We can't function without one. Dartfmt is not the right tool for me, but you are making sure I have no other option, or else...

I ask you, please, allow us to have the small freedom of using a forked, modified, Dartfmt (without having to recompile the IDE Plugin). I suggest the aforementioned FAQ sentence should be modified to: 

_"If you don't buy that, that's OK. It just means dartfmt probably isn't the right tool for you, and then you can modify it and go to Settings > Editor > Code Style > Dart in your IDE and point to your modified formatter."_

**Comment by natebosch** [comment]
cc @jwren  - where is the best place to track this? It sounds like a request for the intellij plugin.

**Comment by jwren** [comment]
This came up on dart-misc@dartlang.org recently, my original response is below.  Nothing is stopping the community from forking the dartfmt tool or writing their own formatter to be executed on the command line.  Another option would be to create your own formatter that is built into IntelliJ.  The Dart project and the Dart Plugin for IJ are both open source.

----
Yes, after much thought and deliberation between the JetBrains and Dart teams, the IntelliJ-Dart  formatter was removed from the Dart Plugin for IntelliJ.

The reason was two-fold: ongoing UX confusion with developers with multiple Dart formatters in the Dart Plugin and the ongoing collective burden of the maintenance costs of having two Dart formatters.

I can assure you that we did deliberate and try to be thoughtful here.  We made many attempts to fix the UX confusion in the Dart Plugin.  Also, we understood the maintenance costs as we have maintained both features in the Dart Plugin for many years.
----

Jaime

**Comment by marcglasberg** [comment]
@jwren 

Thanks for your response, but I don't understand it. I thought there was only one formatter that can be run from inside IntelliJ, which is to be turned on/off in Settings > Editor > Code Style > Dart.

Where is this second Dart formatter you talk about? What do you refer as "both features"?

"The IntelliJ-Dart  formatter was removed from the Dart Plugin for IntelliJ" — So you mean you have removed it from Settings > Editor > Code Style > Dart?

Maybe you are right that there is a UX confusion, since I have no idea what you are talking about. Could you please explain, or point me to some documentation that will help me understand?

**Comment by natebosch** [comment]
> Where is this second Dart formatter you talk about? What do you refer as "both features"?

There used to be two formatters, one built directly in intellij as well as `dartfmt`. The former was removed and now only `dartfmt` is support _by the Dart plugin_.


We don't plan on supporting the configuration to pick something other than dartfmt, but you should be able to disable formatting with dartfmt entirely and configure a different formatter (assuming someone builds one for dart) using other mechanisms. I don't use intellij so I don't know what those mechanisms are, something like https://plugins.jetbrains.com/plugin/1605-external-code-formatter might work, or you might need to set up formatting outside your editor.
