### ISSUE TITLE
Git Hook for dartfmt

### ISSUE THREAD

**Issue by psygo** [dart-lang/dart_style#895]
> This post has been originally created in [this StackOverflow question](https://stackoverflow.com/q/60468804/4756173). But I thought it was very useful to have a standardized, practical way of doing it in the docs somewhere &mdash; if there's one already, please point me to it.

Ideally, I would like to have `dartfmt` to format my code on every commit, and I think that `git hooks` are ideal for this. So far, I've tried the code found in [this link](http://blog.sethladd.com/2015/04/formatting-dart-code-before-every-git.html), but with no success, despite it appearing on multiple other websites &#8212; maybe it's outdated.

In the end, I think nothing much more complicated than this should work in most cases (inside the `.git/hooks/pre-commit` file):

```bash
#!/bin/bash

dartfmt -w . # or maybe `flutter format .` for Flutter
```

The errors I get are:

- For `dartfmt -w .`: `dartfmt: command not found`
- For `flutter format .`:  `find: ‘>     bin [’: No such file or directory`

Both of those commands do work if placed directly in the terminal.

**Comment by munificent** [comment]
This may be some kind of PATH issue, but I'm not very familiar with Git hooks, so I probably can't be of much assistance, sorry.

**Comment by natebosch** [comment]
If you are using a GUI application to make commits then the hooks might not be running with the same `$PATH` as when you are in the terminal. See, for instance, https://www.git-tower.com/help/mac/faq-and-tips/faq/hook-scripts

This does sound more like a question about git hooks than about `dartfmt` - you might try asking on stackoverflow for help specifically with writing git hooks.

**Comment by psygo** [comment]
@munificent I did try a bazillion combinations of alternative `PATH`s to see if that was the problem. I don't know if you have it working on Windows, but almost everyone who told me this was a `PATH` problem did not have it solved on Windows but on Mac.

@natebosch, the SO post is referenced in the OP.

Anyway, I think it would be really nice to have a standardized Git Hook for `dartfmt` (for all OSs) since it would make formatting much easier and practical.

**Comment by natebosch** [comment]
> it would be really nice to have a standardized Git Hook for `dartfmt` (for all OSs) since it would make formatting much easier and practical.

This is a bit outside of our area of expertise and not the place where we can add the most value. If you find something that works I'd encourage you to share it with the community. Thanks!
