### ISSUE TITLE
Line Separator U+2028 in comment fails to format entire file

### ISSUE THREAD

**Issue by avioli** [dart-lang/dart_style#901]
Got a dart file with a Line Separator character U+2028 (hex: E2 80 A8) in a comment (copy and pasted extra text from a web page).

`dartfmt input.dart` fails with:

```
The formatter produced unexpected output. Input was:
... source file
Which formatted to:
... correctly formatted file with removed Line Separator
Please report at github.com/dart-lang/dart_style/issues.
```

`flutter format input.dart` fails with the same as `dartfmt` above, but with the added:

```
Formatting failed: 65
```

It would be nice if it points which line/character the unexpected output starts/ends.

**Comment by munificent** [comment]
What would expect this to do? Should it remove the line separator, or should it preserve it and then just not fail?

**Comment by avioli** [comment]
I think the formatter should not remove anything when it fails, but report the line and character position, so the developer can remove it themselves.

If the guard is specifically about a Line Separator character in comments (which I consider an invisible/hidden character) then I would expect it being removed without failure.

**Comment by munificent** [comment]
> what I meant is that I expect the LS in comments to be removed in my case

That sounds good to me too. The failure mode it's getting into now is that it *does* remove it, but then the sanity check it runs to make sure it did not make any incorrect changes does not expect to see that character removed, so complains. I'll fix that so that it allows the line separator to be stripped.
