### ISSUE TITLE
dartfmt doesn't support --enable-experiment=non-nullable

### ISSUE THREAD

**Issue by a-siva** [dart-lang/dart_style#915]
@mit-mit commented on [Mon Apr 06 2020](https://github.com/dart-lang/sdk/issues/41354)

```
bin mit$ ./dartfmt --enable-experiment=non-nullable bin/main.dart

Could not find an option named "enable-experiment".
```

**Comment by munificent** [comment]
This is by design. The formatter implicitly supports the NNBD syntax without any flag needed. This way, it does not need the complexity of determining which libraries are opted in or out. That would be very difficult for dartfmt to implement correctly since it formats on a per-file basis.
