### ISSUE TITLE
dartfmt -n exit status always 0 (even when some files need formatting)

### ISSUE THREAD

**Issue by ditman** [dart-lang/dart_style#925]
I've been integrating `dartfmt` in one of my packages with Github Actions, and `-n .` works, but I need to do some [bash gymnastics](https://github.com/ditman/google_sign_in_as_googleapis_auth/blob/master/.github/workflows/flutter-test.yaml#L32) around the `dartfmt` command to make my CI fail when any files need formatting. (Github Actions use the return value of the command that ran to determine success/failure.)

This is the current behavior:

```
dit@dit:~/github/google_sign_in_as_googleapis_auth$ dartfmt -n .
lib/google_sign_in_as_googleapis_auth.dart
dit@dit:~/github/google_sign_in_as_googleapis_auth$ echo $?
0
```

I understand that the program exited correctly (hence the 0), and that modifying `-n` can break lots of people's workflows, but... **can `dartfmt` have a flag that makes it exit with the number of files that need formatting?**

This is what I had to do to achieve (part of) what I need (nicer output, [`flutter analyze` style](https://github.com/ditman/google_sign_in_as_googleapis_auth/runs/637999901) would be great, the current one is a little bit [too utilitarian](https://github.com/ditman/google_sign_in_as_googleapis_auth/runs/637994863)):

```
dit@dit:~/github/google_sign_in_as_googleapis_auth$ dartfmt -n . ; (exit $(dartfmt -n . | wc -l))
lib/google_sign_in_as_googleapis_auth.dart
dit@dit:~/github/google_sign_in_as_googleapis_auth$ echo $?
1
```

**Comment by munificent** [comment]
I think what you want is `--set-exit-if-changed`. `dartfmt --help` explains it. If that doesn't work for you, feel free to reopen this. :)

**Comment by ditman** [comment]
```
    --set-exit-if-changed              Return exit code 1 if there are any formatting changes.
```

I can't read, thanks @munificent :'D
