### ISSUE TITLE
One size does not fit all

### ISSUE THREAD

**Issue by OBorce** [dart-lang/dart_style#926]
Why can't we have 2 formatting styles, 
One for local viewing and editing with a preference to the Developer. Everyone should read the code how they feel is the most readable to them, this is individual based not something that one size fits all. e.g. I might like 80 chars line width on my laptop but 120 on my desktop monitor.
or
`foo.split(dilim).where(cond).toList();`
vs
```
foo.split(dilim)
   .where(cond)
   .toList();
```

And another public one, which is run before pushing the code to the repository, can be the current monstrosity that everyone are stuck with, so that all code viewed on internet is the same.

**Comment by munificent** [comment]
People have been suggesting this model for decades, across many many languages. So far, it has never caught on. In practice, the formatting used affects things like variable names, which control flow structures are chosen, and which subexpressions get hoisted out to local variables.

I haven't seen much evidence that formatting can be done on a per-user basis and doing so is out of scope for this tool.
