### ISSUE TITLE
Special case NNBD migration tool comments

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/dart_style#929]
I notice that the NNBD migration tool might write:

```
String/*!*/ foo() {
  return 'foo';
}
```

and that dartfmt will change this to:

```
String /*!*/ foo() {
  return 'foo';
}
```

The `!` is a hint about the return type, so I think the former looks better.

WDYT, could/should dartfmt special case the NNBD hint comments so they stay next to types?

Thanks :)

**Comment by davidmorgan** [comment]
@stereotype441

**Comment by munificent** [comment]
I'm leaning towards leaving the current behavior alone. My hope/expectation is that these comments won't stick around in the code for long, so it doesn't matter that much how they are formatted. The current formatting doesn't look particularly bad to me, either. And I'd rather not add formatting rules to the formatter that will eventually "expire".

**Comment by munificent** [comment]
We're fairly far into the migration and I haven't heard any complaints, so I'm going to close this as unplanned.
