### ISSUE TITLE
Internal body is looking ugly when formatting using dartfmt. 

### ISSUE THREAD

**Issue by dark-chocolate** [dart-lang/dart_style#931]
This is minimal reproducible code:

```dart
final stream = StreamController().stream;

// Not properly formatted (default behavior)
stream.map((event) => null).listen((event) {
  print('something');
});
```
Let me try adding a dummy comment at the end of stream, this is how it looks now

```dart
stream // Dummy comment
    .map((event) => null) // looks good
    .listen((event) { // good
  print('something'); // bad
});
```
**Expected behavior:**

This is how it should be, no need to add any dummy comment and look at the `listen` body, it looks good
```dart
stream 
  .map((event) => null) // looks good
  .listen((event) { // good
    print('something'); // good
  })
  .onDone(() { // good
    print('done'); // good
  });
```

**Comment by munificent** [comment]
Hi, this is working as intended, though I understand it's not to everyone's preference in all cases. The block-like formatting you get for some uses of lambdas is designed to make code like this more readable:

```dart
test("description(), () {
  // Very large block of code...
});
```

It would be unfortunate if that entire lambda got shifted over.
