### ISSUE TITLE
how to config Dart line comment indent

### ISSUE THREAD

**Issue by xgqfrms** [dart-lang/dart_style#932]
# Android studio 4.0 & Flutter / Dart

> I just want to cancel `comment at first column` like Java, as below shows

![image](https://user-images.githubusercontent.com/7291672/84683256-87068600-af69-11ea-8985-e65941627ee4.png)

> bad

![image](https://user-images.githubusercontent.com/7291672/84683416-c1702300-af69-11ea-8a9c-0519dab453cf.png)

> good

![image](https://user-images.githubusercontent.com/7291672/84683448-cdf47b80-af69-11ea-8c43-13d55390381b.png)

**Comment by xgqfrms** [comment]
# not support `.editconfig`

![image](https://user-images.githubusercontent.com/7291672/84998290-38800400-b182-11ea-9292-5fcb49cfb1b2.png)

**Comment by munificent** [comment]
If you write a line comment at the beginning of the line, dartfmt will keep it there. But if there are any spaces before the `//`, then dartfmt will indent it to match the surrounding code.

dartfmt is not at all involved when you tell your IDE to comment or uncomment a line, so I can't do anything about that.
