### ISSUE TITLE
Adding a comment changes formatting several lines below

### ISSUE THREAD

**Issue by ncuillery** [dart-lang/dart_style#939]
Hey I found a strange behavior using dartfmt.

When adding a comment line above a Map entry, it changes the formatting on a conditional Map entry multiple lines below:

![dartfmt-issue](https://user-images.githubusercontent.com/4425455/88820516-65ff9a80-d18f-11ea-9fa2-fb95c32ecf91.gif)

Is it expected?

**Comment by munificent** [comment]
This looks like #888. That was fixed in 1.3.4. Are you using the latest dartfmt? If not, can you try that and see if it fixes it? Thanks!

**Comment by munificent** [comment]
I'm going to speculatively close this as a dupe just to not leave it hanging, but if you can repro this with the latest dartfmt, reply here and I'll reopen.
