### ISSUE TITLE
Travis task for dartfmt is broken in 2.9.0

### ISSUE THREAD

**Issue by jathak** [dart-lang/dart_style#940]
The formatter is crashing with the error `FileSystemException: writeFrom failed, path = '' (OS Error: Broken pipe, errno = 32)` when run on Travis using the 2.9.0 SDK.

[Example job](https://travis-ci.org/github/sass/dart-sass/jobs/715634124)

We've confirmed that this error happens reliably on multiple projects using the dartfmt Travis task, and that it only started when the stable channel was updated to 2.9.0 (the formatting task passed successfully 2 days ago).

**Comment by munificent** [comment]
Is this a dartfmt crash? In the linked job, it looks like the stack trace is coming from pub. Is there something I'm missing?

**Comment by jathak** [comment]
Yeah, it looks like it's actually coming from the core library. Opened a new issue there: https://github.com/dart-lang/sdk/issues/42989
