### ISSUE TITLE
Formatting chained methods in one long line, without proper line breaks

### ISSUE THREAD

**Issue by ChicoLin** [dart-lang/dart_style#943]
Input code
```
Creative convert(ApiCreative creative) {  
  return Creative.build((b) => b
    ..openAuctionStatus = StatusType.fromServingStatus(creative.creativeServingDecision.openAuctionServingStatus.status)
    ..dealsPolicyTopics.addAll(creative.creativeServingDecision.dealsServingStatus.topics.map(
        (topicEntry) => _toPolicyTopic(topicEntry, policyTopicMap, policyTopicDescriptionMap, policyTopicHelpCenterUrlMap)))
    ..dealsStatus = StatusType.fromServingStatus(creative.creativeServingDecision.dealsServingStatus.status);
}
```

Output code
```
Creative convert(ApiCreative creative) {  
  return Creative.build((b) => b
    ..openAuctionStatus = StatusType.fromServingStatus(creative.creativeServingDecision.openAuctionServingStatus.status)
    ..dealsPolicyTopics.addAll(creative.creativeServingDecision.dealsServingStatus.topics.map((topicEntry) => _toPolicyTopic(topicEntry, policyTopicMap, policyTopicDescriptionMap, policyTopicHelpCenterUrlMap)))
    ..dealsStatus = StatusType.fromServingStatus(creative.creativeServingDecision.dealsServingStatus.status);
}
```

Expected output code (Not necessarily exactly like this, just need it with proper line breaks)
```
Creative convert(ApiCreative creative) {  
  return Creative.build((b) => b
    ..openAuctionStatus = StatusType.fromServingStatus(
         creative.creativeServingDecision.openAuctionServingStatus.status)
    ..dealsPolicyTopics.addAll(
         creative.creativeServingDecision.dealsServingStatus.topics
         .map((topicEntry) => _toPolicyTopic(
             topicEntry, policyTopicMap, policyTopicDescriptionMap,
                policyTopicHelpCenterUrlMap)))
    ..dealsStatus = StatusType.fromServingStatus(
        creative.creativeServingDecision.dealsServingStatus.status);
}
```

**Comment by munificent** [comment]
I think you're not getting any changed output because the input code has a syntax error. If you add the missing `)` before the last `;`, dartfmt produces:

```dart
Creative convert(ApiCreative creative) {
  return Creative.build((b) => b
    ..openAuctionStatus = StatusType.fromServingStatus(
        creative.creativeServingDecision.openAuctionServingStatus.status)
    ..dealsPolicyTopics.addAll(creative
        .creativeServingDecision.dealsServingStatus.topics
        .map((topicEntry) => _toPolicyTopic(topicEntry, policyTopicMap,
            policyTopicDescriptionMap, policyTopicHelpCenterUrlMap)))
    ..dealsStatus = StatusType.fromServingStatus(
        creative.creativeServingDecision.dealsServingStatus.status));
}
```

dartfmt can only format valid Dart code. :)

**Comment by ChicoLin** [comment]
I made a mistake while copying and pasting because the original object has too many fields. The code did has that final `)`. BTW I'm a Googler, is there any internal ways to report the bug so I can paste the real original code?

**Comment by ChicoLin** [comment]
> I think you're not getting any changed output because the input code has a syntax error. If you add the missing `)` before the last `;`, dartfmt produces:
> 
> ```dart
> Creative convert(ApiCreative creative) {
>   return Creative.build((b) => b
>     ..openAuctionStatus = StatusType.fromServingStatus(
>         creative.creativeServingDecision.openAuctionServingStatus.status)
>     ..dealsPolicyTopics.addAll(creative
>         .creativeServingDecision.dealsServingStatus.topics
>         .map((topicEntry) => _toPolicyTopic(topicEntry, policyTopicMap,
>             policyTopicDescriptionMap, policyTopicHelpCenterUrlMap)))
>     ..dealsStatus = StatusType.fromServingStatus(
>         creative.creativeServingDecision.dealsServingStatus.status));
> }
> ```
> 
> dartfmt can only format valid Dart code. :)

I made a mistake while copying and pasting because the original object has too many fields. The original code does have that final ) and complies okay.

BTW I'm a Googler, is there any internal ways to report the bug so I can paste the real original code or link to code search?

**Comment by munificent** [comment]
> I made a mistake while copying and pasting because the original object has too many fields. The original code does have that final ) and complies okay.

Ah, if you only get this output in the context of a much larger cascade expression then you are almost certainly running into #811.

> BTW I'm a Googler, is there any internal ways to report the bug so I can paste the real original code or link to code search?

Yeah, you can file a buganizer issue. Though, if possible, I prefer issues here since dart_style is an open source project. I generally ask people to sanitize the code by replacing identifiers with equal-length substitutes and then file it here.
