### ISSUE TITLE
Request: add semicolon when necessary

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/dart_style#948]
I've been developing on Typescript for the past few months and the nice thing about [Prettier](https://prettier.io/) is that it automatically adds the ";" when I forget about it. Of course this is a "best effort" thing, but it works flawless 98% of the time - so much I completely forgot about adding ; to the end of expressions, I just write and command+l to format and add it.

I believe Dart community could benefit a lot:
- I've been loosing too much time "remembering" to add the ; in order to dartfmt work correctly and the app to compile.
- Many people complain about the existence of the ;, but if this were added, people could develop small expressions without it and let the formatter handle it.

Example

```dart
if (state is Fail) {
    return Text("fail"); // ok!
}
if (state is Success) {
    return Text("success") // missing a semicolon! Dartfmt, please add it!
}
```

**Comment by munificent** [comment]
I can definitely understand the desire for this, but I think it's out of scope for what the formatter should do. The formatter's job is to take valid Dart code and tweak its whitespace. If it starts accepting things that are *not* valid Dart code, then it puts the formatter in the business of defining what that other Dart-like input format is, and what the rules are for where it inserts semicolons. Doing that well is *very* hard.

See also: #884
