### ISSUE TITLE
too much violence when code is slightly wrong

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/dart_style#949]
For the following expression:
```dart
class TestWidget extends StatefulWidget {

  final double initial;

  final TestWidget(this.initial);
}
```

dartfmt outputs
```dart
class TestWidget extends StatefulWidget {

  final double initial;

  final TestWidget

  (

  this

      .

  initial

  );
}
```

This is too wrong and makes the code too hard to fix. The issue was just the `final TestWidget` that needed to be replaced with `const TestWidget`.

**Comment by munificent** [comment]
This output isn't coming from dartfmt. It looks like a bug in the IntelliJ or the IDE integration.
