### ISSUE TITLE
str.slice is not a function from dart-style npm package

### ISSUE THREAD

**Issue by softmarshmallow** [dart-lang/dart_style#956]
> index.js:268 Uncaught TypeError: str.slice is not a function     at Object.matchGrammar (<anonymous>:47606:30)     at Object.tokenize (<anonymous>:47651:9)     at Highlight.render (<anonymous>:47310:53)     at finishClassComponent (<anonymous>:68102:31)     at updateClassComponent (<anonymous>:68052:24)     at beginWork (<anonymous>:69562:16)     at HTMLUnknownElement.callCallback (<anonymous>:51130:14)     at Object.invokeGuardedCallbackDev (<anonymous>:51179:16)     at invokeGuardedCallback (<anonymous>:51234:31)     at beginWork$1 (<anonymous>:74145:7)

when running

``` ts
import { formatCode } from "dart-style"
const raw = "Widget tet(){ return null }"
const code = formatCode(raw);
```

**Comment by munificent** [comment]
@jacob314, do you remember anything about the node integration of dartfmt?

**Comment by munificent** [comment]
The dart_style package doesn't support being compiled to JavaScript anymore. (Users are certainly welcome to do so on their own, of course. But the package itself doesn't support it.)
