### ISSUE TITLE
Separation and indenting issues with autoformatter

### ISSUE THREAD

**Issue by MohammadAlHajj** [dart-lang/dart_style#963]
- Where can i post the below image to help you fix formatting?
-  is there a way (annotation or otherwise) to disable formatting on a single class/method/variable/scope (especially manual maps)?

before autoformat
![image](https://user-images.githubusercontent.com/9088242/95983291-0af25100-0e2a-11eb-9c4c-64b14784ddfc.png)

after autoformat
![image](https://user-images.githubusercontent.com/9088242/95982921-77b91b80-0e29-11eb-9d94-2109ccbf6f92.png)

the code:
 ```
 /// transform function to valid value and unit (above [x.min] min and 0) or
  /// 'N/A'
  ///
  /// [round] <= 0 implies round to nearest whole number
  static final String Function(Measurement x,
      {int round}) nABelowMinOrValue = (Measurement x, {int round = 2}) => x
                  .value <
              x.min ||
          x.value < 0
      ? 'N/A'
      : round <= 0
          ? '${x.value.round()}${HtmlUnescape().convert(x.unit)}'
          : '${x.value.toStringAsFixed(round)}${HtmlUnescape().convert(x.unit)}';
```
- is there a way to change the spacing (2 instead of 4) introduced by the ternary (conditional) statements seen below?

![image](https://user-images.githubusercontent.com/9088242/95985346-27dc5380-0e2d-11eb-863a-13e60bdcf3fb.png)

_Originally posted by @MohammadAlHajj in https://github.com/Dart-Code/Dart-Code/issues/914#issuecomment-708342660_

**Comment by munificent** [comment]
> * Where can i post the below image to help you fix formatting?

Here in GitHub is fine. Thank you for including the code as text too.

> is there a way (annotation or otherwise) to disable formatting on a single class/method/variable/scope (especially manual maps)?

In general, no, but you have some control over formatting collection literals. See [here](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-tell-the-formatter-to-ignore-a-region-of-code) and [here](https://github.com/dart-lang/dart_style/wiki/FAQ#why-does-the-formatter-mess-up-my-collection-literals).

> is there a way to change the spacing (2 instead of 4) introduced by the ternary (conditional) statements seen below?

No. See [here](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it) for context.

The formatter does the best job it can with the code you give it, but there's only so much it can do. Often, the way to get the best looking code is to tweak it in concert with the formatter. In the example here, I would change the code to:

```dart
  /// transform function to valid value and unit (above [x.min] min and 0) or
  /// 'N/A'
  ///
  /// [round] <= 0 implies round to nearest whole number
  static String nABelowMinOrValue(Measurement x, {int round = 2}) {
    if (x.value < x.min || x.value < 0) return 'N/A';
    if (round <= 0) {
      return '${x.value.round()}${HtmlUnescape().convert(x.unit)}';
    }
    return '${x.value.toStringAsFixed(round)}${HtmlUnescape().convert(x.unit)}';
  }
```

**Comment by MohammadAlHajj** [comment]
Thanks for the reply

I will not argue with the general part of your philosophy, but you have to take into consideration the following. 

**A formatter is a tool to make life easier. It loses it's usefulness when it becomes a hindrance.** 

[this](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-tell-the-formatter-to-ignore-a-region-of-code) is a hindrance. 

> Yes, maybe you can hand-format some things better than the formatter. [...] But does doing that really add enough value to make up for re-opening that can of worms?

Definitely!!! you will not be hand-formatting everything. (You won't be using the formatter then). You will use it in very specific situations. If the user wants to shoot themselves in the foot, then so be it.

why should i be forced to change this:
![image](https://user-images.githubusercontent.com/9088242/97744520-0e572f00-1af0-11eb-8616-83f057e377c8.png)

int this:
![image](https://user-images.githubusercontent.com/9088242/97744800-87ef1d00-1af0-11eb-84a8-3c4488aa36f1.png)


code:
```
  static final Map<String, Map<String, String Function(Measurement x)>> functionMap = {
    _measurementsCategory: {
      'upstream water level'    : (x) => nABelowMinOrValue(x),
      'downstream water level'  : (x) => nABelowMinOrValue(x),
      'water level'             : (x) => nABelowMinOrValue(x),
      'discharge'               : (x) => valueAndUnit(x, round: 0),
      'upstream discharge'      : (x) => valueAndUnit(x, round: 0),
      'downstream discharge'    : (x) => valueAndUnit(x, round: 0),
      'left canal discharge'    : (x) => valueAndUnit(x, round: 0),
      'right canal discharge'   : (x) => valueAndUnit(x, round: 0),
      'water temperature'       : (x) => valueAndUnit(x, round: 1),
      'water esd'               : (x) => valueAndUnit(x),
      'air temperature'         : (x) => valueAndUnit(x, round: 1),
      'relative humidity'       : (x) => valueAndUnit(x),
      'CO2 level'               : (x) => valueAndUnit(x),
    },
}
```

> The formatter does the best job it can with the code you give it, but there's only so much it can do. Often, the way to get the best looking code is to tweak it in concert with the formatter. 

The formatter works for me, not the other way around. Also, if it fails (which the quoted FAQ granted happens), i want the power to fix the issue.
