### ISSUE TITLE
Can't format with comment above in-lined conditional in List

### ISSUE THREAD

**Issue by kristini-ho** [dart-lang/dart_style#966]
In a list literal created with a for-loop (with conditionals) inside, having a comment placed directly above a conditional caused the formatter to fail

```
return [
      for (final x in exampleList)
        if (conditionA)
          ItemConstructorA(...)
       // Sample multi-line comment
      // which broke the formatter
        else if (conditionB)
           ItemConstructorB(...)
     else
       ItemConstructorC(...)
];
```

Error message was `Exception from the Dart analysis server: The formatter produced unexpected output. Input was: [...]`

Moving the comment to below the conditional and above the statement like so:

```
return [
      for (final x in exampleList)
        if (conditionA)
          ItemConstructorA(...)
        else if (conditionB)
       // Sample multi-line comment
      // which no longer breaks formatter
           ItemConstructorB(...)
     else
       ItemConstructorC(...)
];
```

caused the formatter to be able to format the file once again.

**Comment by munificent** [comment]
Thanks, I'll take a look.
