### ISSUE TITLE
Need some line space

### ISSUE THREAD

**Issue by karthickramanathan95** [dart-lang/dart_style#975]
Need some line space between the class declaration and the next first line.

I want this

```
class _HomePageState extends State<HomePage>
    with SingleTickerProviderStateMixin {
  
  AnimationController _animationController;
  Animation<double> _flipAnimation;
  Animation<double> `_fabIconAnimation;
```

but when format it come like this

```
class _HomePageState extends State<HomePage>
    with SingleTickerProviderStateMixin {
  AnimationController _animationController;
  Animation<double> _flipAnimation;
  Animation<double> _fabIconAnimation;
```

This style is not good

**Comment by munificent** [comment]
This is working as intended, sorry. In general, dartfmt want's to control as much of the whitespace in the file as it can and format it as consistently as possible. In almost all cases it seems that users are happy with not having any blank lines between the `{` and the first declaration in a class.

More context here: https://github.com/dart-lang/dart_style/wiki/FAQ
