### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by vanlooverenkoen** [dart-lang/dart_style#978]
I am upgrading my package (Kiwi) vanlooverenkoen/kiwi#51

But it seems that dart_style is not yet migrated to support nullsafety. Is there a timeline on when this could be added?

**Comment by munificent** [comment]
No concrete timeline yet, sorry. dart_style depends (very heavily) on analyzer, so I won't be able to migrate it to null safety until analyzer has migrated. I know that team is looking into the migration now, but it's a very large amount of work, so it might be a while. As soon as their migration is done, I expect the migration of dart_style to be fairly quick.

**Comment by vanlooverenkoen** [comment]
@munificent yes just created github issues everywhere to better track the nullsafe migration of all the packages

**Comment by lzoran** [comment]
Not sure if pre-release is what we are waiting for, but the null-safety version of the `analyzer` package is now available - [link](https://pub.dev/packages/analyzer/versions/0.42.0-nullsafety.0/changelog).

**Comment by marcschw** [comment]
Seems like null-safety is stable now for analyzer 1.1.0 - any timeline when dart_style can be migrated?
https://pub.dev/packages/analyzer/changelog

**Comment by zmtzawqlp** [comment]
any update?

**Comment by munificent** [comment]
Oops, sorry for the delay. Yes, this is done now. dart_style 2.0.0 is null safe.
