### ISSUE TITLE
Implement non-function type alias support in dart format

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/dart_style#993]
This issue tracks support of the [non-function type alias feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/44951) for details.

cc @munificent @mit-mit @franklinyow

**Comment by leafpetersen** [comment]
@munificent any updates here?

**Comment by franklinyow** [comment]
@munificent What is the status on this? Thx

**Comment by lukepighetti** [comment]
Looks like this is blocking formatting on projects using non-function type aliasing with SDK bottom constraint of `2.13.0-162.0.dev`.

**Comment by munificent** [comment]
Gonna start on it this week. Google IO took over my life temporarily.

**Comment by lukepighetti** [comment]
I have been using the enclosed PR for a few hours and it's working beautifully, FWIW.
