### ISSUE TITLE
Nested cascades don't nest indentation

### ISSUE THREAD

**Issue by munificent** [dart-lang/dart_style#999]
The formatter currently produces:

```dart
void main() {
  final object = outer(inner()
    ..innerProperty1 = 1
    ..innerProperty2 = 2)
    ..outerProperty = 3;
}
```

Note that `innerProperty` and `outerProperty` are at the same indentation depth even though there are cascades on different objects. I'd expect something like:

```dart
void main() {
  final object = outer(inner()
      ..innerProperty1 = 1
      ..innerProperty2 = 2)
    ..outerProperty = 3;
}
```

**Comment by natebosch** [comment]
Is this related at all to https://github.com/dart-lang/dart_style/issues/760

**Comment by munificent** [comment]
Probably.

**Comment by srawlins** [comment]
Drive by: WIP tall style formatter outputs this, which I think is working as intended:

```dart
void main() {
  final object = outer(
    inner()
      ..innerProperty1 = 1
      ..innerProperty2 = 2,
  )..outerProperty = 3;
}
```

**Comment by munificent** [comment]
The [forthcoming](https://github.com/dart-lang/dart_style/issues/1403) [tall style](https://github.com/dart-lang/dart_style/issues/1253) handles argument lists and cascades differently. With the new style, you get:

```dart
void main() {
  final object = outer(
    inner()
      ..innerProperty1 = 1
      ..innerProperty2 = 2,
  )..outerProperty = 3;
}
```

That fixes the ambiguous nesting problem and looks pretty good to me.
